//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

#import "_TtP16TMTimelineObject18DictionaryUpdating_-Protocol.h"

@interface _TtC16TMTimelineObject32DictionaryUpdatableManagedObject : NSManagedObject <_TtP16TMTimelineObject18DictionaryUpdating_>
{
}

- (void)updateWithDictionary:(id)arg1;
- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;
- (id)initWithContext:(id)arg1 dictionary:(id)arg2;

@end

