//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr27DefaultBlogPreviewPresenter : _TtCs12_SwiftObject
{
    MISSING_TYPE *navigationController;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *session;
    MISSING_TYPE *clientSideAdSources;
}

@end

