//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr18DataWipeController : NSObject
{
    MISSING_TYPE *crashRecorder;
    MISSING_TYPE *userDefaults;
    MISSING_TYPE *metricProvider;
    MISSING_TYPE *wipeDatabaseFlag;
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)determineIfADataWipeIsRequiredAndClearOldCrashes;
- (id)initWithMetricProvider:(id)arg1 userDefaults:(id)arg2 crashRecorder:(id)arg3 wipeDatabaseFlag:(id)arg4;

@end

