//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC10CoreTumblr29CoreDataTimelineObjectFactory : NSObject
{
}

+ (id)createOrUpdateResponseTimelineObjects:(id)arg1 context:(id)arg2;
- (id)init;

@end

