//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Tumblr19PanelViewController.h"

#import "TMFormTextFieldCellDelegate-Protocol.h"

@interface _TtC6Tumblr19PanelViewController (Tumblr2) <TMFormTextFieldCellDelegate>
- (_Bool)textFieldCellShouldReturn:(id)arg1;
- (_Bool)textFieldCellIsEditable:(id)arg1;
@end

