//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr29CarouselTableViewCellProvider : NSObject
{
    MISSING_TYPE *tableView;
    MISSING_TYPE *parentViewController;
    MISSING_TYPE *screenIdentifier;
    MISSING_TYPE *postViewConfiguration;
    MISSING_TYPE *impressionReceiver;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *session;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *timelineScrollUpdater;
    MISSING_TYPE *exploreHeroCarouselTableViewCellDelegate;
}

- (void).cxx_destruct;
- (id)init;
- (id)cellWithCarouselTimelineObject:(id)arg1 spacerHeight:(double)arg2 appColorScheme:(id)arg3;
- (void)updatePostViewConfigurationWithPostViewConfiguration:(id)arg1;
- (id)initWithTableView:(id)arg1 parentViewController:(id)arg2 screenIdentifier:(id)arg3 postViewConfiguration:(id)arg4 impressionReceiver:(id)arg5 coreDataController:(id)arg6 analyticsBuffer:(id)arg7 linkRouter:(id)arg8 session:(id)arg9 clientSideAdSources:(id)arg10 timelineScrollUpdater:(id)arg11 exploreHeroCarouselTableViewCellDelegate:(id)arg12;

@end

