//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8TumblrUI19BlogHeaderConstants : NSObject
{
}

+ (struct UIEdgeInsets)edgeInsets;
+ (struct UIEdgeInsets)edgeInsetsRetina;
+ (double)visibleEditableViewAlpha;
+ (double)hiddenEditableViewAlpha;
+ (double)individualSubviewFadeAnimationDuration;
+ (double)editableFadeAnimationDuration;
+ (double)nonStretchHeaderImageInset;
+ (double)descriptionParagraphSpacingBefore;
+ (double)descriptionFontSize;
+ (double)titleFontSize;
+ (double)titleBottomMargin;
+ (double)avatarBottomMargin;
+ (double)avatarTopMargin;
+ (double)noViewTopMargin;
+ (double)avatarBottomMarginWithDescription;
+ (double)avatarBottomMarginWithTitle;
+ (double)titleWithDescriptionBottomMargin;
+ (double)titleTopMargin;
+ (double)descriptionBottomMargin;
+ (double)descriptionTopMargin;
+ (double)descriptionHorizontalMargin;
+ (double)avatarDimension;
+ (double)takeoverHeaderImageHeight;
+ (double)headerImageHeightWithImageWidth:(double)arg1;
+ (double)imageAspectRatio;
+ (double)avatarDimensioniPhone;
- (id)init;

@end

