//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSDictionary;

@interface _TtC14TelegraphSwift14PusherChannels : NSObject
{
    MISSING_TYPE *channels;
}

- (void).cxx_destruct;
- (id)init;
- (id)findPresenceWithName:(id)arg1;
- (id)findWithName:(id)arg1;
- (void)removeWithName:(id)arg1;
- (id)addPresenceWithChannelName:(id)arg1 connection:(id)arg2 auth:(id)arg3 onMemberAdded:(CDUnknownBlockType)arg4 onMemberRemoved:(CDUnknownBlockType)arg5;
- (id)addWithName:(id)arg1 connection:(id)arg2 auth:(id)arg3 onMemberAdded:(CDUnknownBlockType)arg4 onMemberRemoved:(CDUnknownBlockType)arg5;
@property(nonatomic, copy) NSDictionary *channels;

@end

