//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr19PanelViewController : UITableViewController
{
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *session;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *settingsReader;
    MISSING_TYPE *$__lazy_storage_$_guceConsentFlowCoordinator;
    MISSING_TYPE *$__lazy_storage_$_baseURLDeterminer;
    MISSING_TYPE *$__lazy_storage_$_preferences;
    MISSING_TYPE *$__lazy_storage_$_pushNotificationRegistrar;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithAppColorScheme:(id)arg1 analyticsBuffer:(id)arg2 session:(id)arg3 linkRouter:(id)arg4 coreDataController:(id)arg5 clientSideAdSources:(id)arg6;
@property(nonatomic, readonly) long long preferredStatusBarStyle;

@end

