//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr33ConversationViewControllerFactory : _TtCs12_SwiftObject
{
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *session;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *messageSender;
    MISSING_TYPE *reachabilityDeterminer;
    MISSING_TYPE *conversationBadgeController;
    MISSING_TYPE *bannerSuppressorManager;
    MISSING_TYPE *messagingAnalyticsLogger;
    MISSING_TYPE *backgroundProvider;
    MISSING_TYPE *messagingApplicationInstanceDelegate;
}

@end

