//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC9ComposeUI23GIFSearchViewController : UIViewController
{
    MISSING_TYPE *$__lazy_storage_$_handle;
    MISSING_TYPE *$__lazy_storage_$_searchToolbar;
    MISSING_TYPE *$__lazy_storage_$_collectionView;
    MISSING_TYPE *$__lazy_storage_$_emptyLabel;
    MISSING_TYPE *$__lazy_storage_$_searchDebouncer;
    MISSING_TYPE *$__lazy_storage_$_mediaPickerDelegate;
    MISSING_TYPE *delegate;
    MISSING_TYPE *gifSearcher;
    MISSING_TYPE *session;
    MISSING_TYPE *preferences;
    MISSING_TYPE *backgroundProvider;
    MISSING_TYPE *eventProvider;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *showCreateButton;
    MISSING_TYPE *currentSearchTerm;
    MISSING_TYPE *searchFilter;
    MISSING_TYPE *GIFsArray;
    MISSING_TYPE *isLoading;
    MISSING_TYPE *urlOpening;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
@property(nonatomic, readonly) _Bool shouldAutorotate;
- (id)initWithCoder:(id)arg1;
- (id)initWithGifSearcher:(id)arg1 session:(id)arg2 preferences:(id)arg3 backgroundProvider:(id)arg4 delegate:(id)arg5 appColorScheme:(id)arg6 composeGIFSearchEventProvider:(id)arg7 showCreateButton:(_Bool)arg8 urlOpening:(id)arg9;

@end

