//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC10GIFCreator9Operation.h"

@class MISSING_TYPE;

@interface _TtC10GIFCreator18AutoRetryOperation : _TtC10GIFCreator9Operation
{
    MISSING_TYPE *maximumNumberOfRetries;
    MISSING_TYPE *currentRetryNumber;
    MISSING_TYPE *delayGrowthBetweenRetries;
    MISSING_TYPE *queue;
}

- (void).cxx_destruct;
- (id)init;

@end

