//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, _TtC9Timelines14GroupChatTheme, _TtC9Timelines15DismissalOption;

@interface _TtC9Timelines14GroupChatModel : NSObject
{
    MISSING_TYPE *isSponsored;
    MISSING_TYPE *canDismiss;
    MISSING_TYPE *identifier;
    MISSING_TYPE *chatName;
    MISSING_TYPE *chatDescription;
    MISSING_TYPE *isSubscribed;
    MISSING_TYPE *chatSubscriptionNotificationsEnabled;
    MISSING_TYPE *ephemeralityHours;
    MISSING_TYPE *theme;
    MISSING_TYPE *participantsCount;
    MISSING_TYPE *maxParticipantsCount;
    MISSING_TYPE *chatTags;
    MISSING_TYPE *chatUnreadCount;
    MISSING_TYPE *details;
    MISSING_TYPE *dismissalOption;
    MISSING_TYPE *context;
    MISSING_TYPE *recommendationReason;
    MISSING_TYPE *deepLinkURL;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) _TtC9Timelines15DismissalOption *dismissalOption; // @synthesize dismissalOption;
@property(nonatomic, retain) _TtC9Timelines14GroupChatTheme *theme; // @synthesize theme;
@property(nonatomic, readonly) _Bool canDismiss; // @synthesize canDismiss;

@end

