//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, NSURL;

@interface _TtC10ShareSheet18PostValueContainer : NSObject
{
    MISSING_TYPE *preferences;
    MISSING_TYPE *postType;
    MISSING_TYPE *blogName;
    MISSING_TYPE *blogUUID;
    MISSING_TYPE *summary;
    MISSING_TYPE *isPrivateBlog;
    MISSING_TYPE *postURL;
    MISSING_TYPE *postID;
    MISSING_TYPE *rebloggedFromName;
    MISSING_TYPE *rebloggedFromID;
    MISSING_TYPE *reblogKey;
    MISSING_TYPE *hasNotes;
    MISSING_TYPE *noteCount;
    MISSING_TYPE *title;
    MISSING_TYPE *cleanBody;
    MISSING_TYPE *photos;
    MISSING_TYPE *displayTitle;
    MISSING_TYPE *displayArtistAlbum;
    MISSING_TYPE *dialogue;
    MISSING_TYPE *linkURL;
    MISSING_TYPE *question;
    MISSING_TYPE *askingURL;
    MISSING_TYPE *askingName;
    MISSING_TYPE *isAnswerPost;
    MISSING_TYPE *thumbnailURL;
    MISSING_TYPE *textWithQuotationMarks;
    MISSING_TYPE *source;
    MISSING_TYPE *isPinned;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSURL *url;
@property(nonatomic, readonly) NSString *postURL;
@property(nonatomic, readonly) NSString *blogUUID;

@end

