//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE;

@interface _TtC10GIFCreator23MediaAlbumTableViewCell : UITableViewCell
{
    MISSING_TYPE *imageLoader;
    MISSING_TYPE *albumItem;
    MISSING_TYPE *thumbOperation;
    MISSING_TYPE *selectedImageView;
    MISSING_TYPE *thumbImageView;
    MISSING_TYPE *collectionTitleLabel;
    MISSING_TYPE *collectionAssetCountLabel;
    MISSING_TYPE *separatorView;
}

- (void).cxx_destruct;
- (void)updateColors:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

