//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC10Starscream9WebSocket10WSResponse : _TtCs12_SwiftObject
{
    MISSING_TYPE *isFin;
    MISSING_TYPE *code;
    MISSING_TYPE *bytesLeft;
    MISSING_TYPE *frameCount;
    MISSING_TYPE *buffer;
    MISSING_TYPE *firstFrame;
}

@end

