//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr18SearchFollowButton : UIButton
{
    MISSING_TYPE *isFollowing;
    MISSING_TYPE *delegate;
    MISSING_TYPE *followedBackgroundColor;
    MISSING_TYPE *followedTitleColor;
    MISSING_TYPE *unfollowedBackgroundColor;
    MISSING_TYPE *unfollowedTitleColor;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)buttonPressed;
- (id)initWithCoder:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

