//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol _TtP6Tumblr19RuleTrackerDelegate_;

@interface _TtC6Tumblr17StaticRuleTracker : NSObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *timeTrackersByRules;
    MISSING_TYPE *beacons;
    MISSING_TYPE *beaconRules;
    MISSING_TYPE *updateTimer;
}

- (void).cxx_destruct;
- (id)init;
- (void)performUpdate;
- (void)stopTrackingEvents;
- (void)trackEvents;
@property(nonatomic) __weak id <_TtP6Tumblr19RuleTrackerDelegate_> delegate; // @synthesize delegate;

@end

