//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray;

@interface _TtC6Tumblr17PostTagsViewModel : NSObject
{
    MISSING_TYPE *contentHeight;
    MISSING_TYPE *contentInsets;
    MISSING_TYPE *tagList;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long hash;
@property(nonatomic, readonly) NSArray *tagList;
@property(nonatomic, readonly) struct UIEdgeInsets contentInsets; // @synthesize contentInsets;
@property(nonatomic, readonly) double contentHeight; // @synthesize contentHeight;

@end

