//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC10ShareSheet40HorizontalRecipientCollectionViewManager : NSObject
{
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *delegate;
    MISSING_TYPE *recipients;
}

- (void).cxx_destruct;
- (id)init;
- (void)updateColors:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;

@end

