//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, TMBlog;
@protocol _TtP9Timelines14TimelineObject_;

@interface _TtC8TumblrUI30BlogRowTimelineObjectViewModel : NSObject
{
    MISSING_TYPE *blogUUID;
    MISSING_TYPE *context;
    MISSING_TYPE *timelineObject;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithTimelineObject:(id)arg1 context:(id)arg2;
@property(nonatomic, readonly) TMBlog *blog;
@property(nonatomic, readonly) id <_TtP9Timelines14TimelineObject_> timelineObject; // @synthesize timelineObject;

@end

