//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC13CommunityHubs31CommunityHubEventConfigurations : NSObject
{
    MISSING_TYPE *communityHubDetails;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithContext:(id)arg1 source:(id)arg2;

@end

