//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC10GIFCreator20CanvasDataController : _TtCs12_SwiftObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *media;
    MISSING_TYPE *textStyles;
    MISSING_TYPE *effects;
    MISSING_TYPE *canvasState;
    MISSING_TYPE *canvasStateObservers;
    MISSING_TYPE *status;
    MISSING_TYPE *urls;
    MISSING_TYPE *frameDelay;
    MISSING_TYPE *$__lazy_storage_$_libraryLoader;
    MISSING_TYPE *currentTextStyleIndex;
    MISSING_TYPE *baseURLForSnapshots;
    MISSING_TYPE *libraryCachePaths;
}

@end

