//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7RxSwiftP33_B4E79ED897163AA84B94CE0A507A463012SinkDisposer : _TtCs12_SwiftObject
{
    MISSING_TYPE *_state;
    MISSING_TYPE *_sink;
    MISSING_TYPE *_subscription;
}

@end

