//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC10CoreTumblr16VideoURLMetaData : NSObject
{
    MISSING_TYPE *title;
    MISSING_TYPE *URL;
    MISSING_TYPE *providerID;
    MISSING_TYPE *providerName;
    MISSING_TYPE *providerURL;
    MISSING_TYPE *thumbnailURL;
    MISSING_TYPE *thumbnailSize;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithResponse:(id)arg1;
@property(nonatomic, readonly) struct CGSize thumbnailSize; // @synthesize thumbnailSize;
@property(nonatomic, readonly) NSString *thumbnailURL;
@property(nonatomic, readonly) NSString *providerURL;
@property(nonatomic, readonly) NSString *providerName;
@property(nonatomic, readonly) NSString *providerID;
@property(nonatomic, readonly) NSString *URL;
@property(nonatomic, readonly) NSString *title;

@end

