//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC13OnboardingKit27OnboardingTextFieldFormCell.h"

@interface _TtC13OnboardingKit24OnboardingEmailFieldCell : _TtC13OnboardingKit27OnboardingTextFieldFormCell
{
}

- (void)checkIfComplete;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidChangeWithTextField:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

