//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

#import "_TtP11ImageLoader14ImageOperation_-Protocol.h"

@class MISSING_TYPE;

@interface _TtC11ImageLoader23BackgroundFillOperation : _TtCs12_SwiftObject <_TtP11ImageLoader14ImageOperation_>
{
    MISSING_TYPE *backgroundColor;
}

- (id)transformWithImage:(id)arg1 referenceViewSize:(struct CGSize)arg2;

@end

