//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC9PostForms12ScheduleView : UIView
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *$__lazy_storage_$_dateFormatter;
    MISSING_TYPE *$__lazy_storage_$_itemView;
    MISSING_TYPE *$__lazy_storage_$_secondaryView;
    MISSING_TYPE *$__lazy_storage_$_label;
    MISSING_TYPE *$__lazy_storage_$_caret;
    MISSING_TYPE *$__lazy_storage_$_datePicker;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dateChanged;
- (void)secondaryViewTappedWithRecognizer:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

