//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE;

@interface _TtC9GroupChat18CustomizeImageCell : UITableViewCell
{
    MISSING_TYPE *$__lazy_storage_$_labeledImageView;
    MISSING_TYPE *$__lazy_storage_$_galleryIconImageView;
    MISSING_TYPE *$__lazy_storage_$_changeImageButton;
    MISSING_TYPE *$__lazy_storage_$_stackView;
    MISSING_TYPE *$__lazy_storage_$_stackViewHeightAnchor;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *delegate;
}

- (void).cxx_destruct;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)onChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

