//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSStreamDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC10Starscream16FoundationStream : NSObject <NSStreamDelegate>
{
    MISSING_TYPE *inputStream;
    MISSING_TYPE *outputStream;
    MISSING_TYPE *delegate;
    MISSING_TYPE *BUFFER_MAX;
    MISSING_TYPE *enableSOCKSProxy;
}

- (void).cxx_destruct;
- (id)init;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;

@end

