//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE;

@interface _TtC8TumblrUI13ListTableCell : UITableViewCell
{
    MISSING_TYPE *isBlueStyled;
    MISSING_TYPE *horizontalInset;
    MISSING_TYPE *bottomSeparator;
}

- (void).cxx_destruct;
- (void)updateColors:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

