//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIPopoverBackgroundView.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr26PopoverAlertBackgroundView : UIPopoverBackgroundView
{
    MISSING_TYPE *_arrowOffset;
    MISSING_TYPE *_arrowDirection;
    MISSING_TYPE *arrowImageView;
    MISSING_TYPE *backgroundView;
    MISSING_TYPE *popoverBackgroundColor;
}

+ (double)arrowHeight;
+ (double)arrowBase;
+ (struct UIEdgeInsets)contentViewInsets;
+ (_Bool)wantsDefaultContentAppearance;
- (void).cxx_destruct;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) double arrowOffset;
@property(nonatomic) unsigned long long arrowDirection;

@end

