//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TMBlogResultsHeaderViewDataSource-Protocol.h"
#import "TMBlogResultsHeaderViewDelegate-Protocol.h"
#import "TMDecoratedTitleViewDelegate-Protocol.h"
#import "TMTakeoverHeaderBannerViewControllerDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6Tumblr37ExploreTakeoverTimelineViewController : UIViewController <TMBlogResultsHeaderViewDelegate, TMBlogResultsHeaderViewDataSource, TMTakeoverHeaderBannerViewControllerDelegate, TMDecoratedTitleViewDelegate>
{
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *session;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *exploreTakeoverTimeline;
    MISSING_TYPE *exploreTakeoverDataService;
    MISSING_TYPE *exploreTakeoverOptions;
    MISSING_TYPE *timelineViewController;
    MISSING_TYPE *dataDisplayViewUpdaterDelegate;
    MISSING_TYPE *showsDecoration;
    MISSING_TYPE *sponsoredBadgeURL;
    MISSING_TYPE *blogResultsHeaderView;
    MISSING_TYPE *bannerViewController;
    MISSING_TYPE *decoratedTitleView;
    MISSING_TYPE *supplyLoggingManager;
    MISSING_TYPE *appColorScheme;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)stylingForNavigationBar;
- (void)updateChangedUI:(id)arg1;
- (void)updateColors:(id)arg1;
- (void)decoratedTitleView:(id)arg1 didTapSponsoredButton:(id)arg2;
- (void)headerBannerViewController:(id)arg1 didSelectUrl:(id)arg2;
- (_Bool)blogResultsHeaderViewHasPosts:(id)arg1;
- (id)blogsForBlogResultsHeaderView:(id)arg1;
- (void)blogResultsHeaderView:(id)arg1 didSelectBlog:(id)arg2;
- (void)viewSafeAreaInsetsDidChange;
@property(nonatomic, readonly) UIViewController *childViewControllerForStatusBarStyle;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

