//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMBannerView.h"

@class MISSING_TYPE;

@interface _TtC6Tumblr28HeaderNotificationBannerView : TMBannerView
{
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *statusBarHeight;
    MISSING_TYPE *iconImageView;
    MISSING_TYPE *bannerTitleLabel;
    MISSING_TYPE *bodyLabel;
    MISSING_TYPE *accessoryView;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 bannerVisibleDuration:(double)arg2;
- (void)updateColors:(id)arg1;
- (void)updateTheming:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithTitle:(id)arg1 body:(id)arg2 iconURL:(id)arg3 shouldPixelateImage:(_Bool)arg4 appColorScheme:(id)arg5;

@end

