//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP6Tumblr25TimelineHeightCalculating_-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6Tumblr24TimelineHeightCalculator : NSObject <_TtP6Tumblr25TimelineHeightCalculating_>
{
    MISSING_TYPE *timelineObjectHeightCalculator;
    MISSING_TYPE *postViewConfiguration;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *traitCollection;
}

- (void).cxx_destruct;
- (id)init;
- (double)heightFor:(id)arg1;
- (id)initWithTimelineObjectHeightCalculator:(id)arg1 postViewConfiguration:(id)arg2 coreDataController:(id)arg3 traitCollection:(id)arg4;

@end

