//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC10GIFCreator9GIFPlayer : _TtCs12_SwiftObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *gifReader;
    MISSING_TYPE *gifQueue;
    MISSING_TYPE *gifTimer;
    MISSING_TYPE *gifFrameIndex;
    MISSING_TYPE *repeatCount;
    MISSING_TYPE *currentRepeatIndex;
    MISSING_TYPE *lastTickTime;
}

@end

