//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC9GroupChat23GroupChatTooltipManager : NSObject
{
    MISSING_TYPE *userDefaults;
    MISSING_TYPE *customizeTooltipAnchor;
    MISSING_TYPE *memberTooltipAnchor;
    MISSING_TYPE *superviewForRenderTooltip;
    MISSING_TYPE *duration;
    MISSING_TYPE *themeColor;
    MISSING_TYPE *canceled;
    MISSING_TYPE *$__lazy_storage_$_tooltipPreferences;
    MISSING_TYPE *$__lazy_storage_$_customizeTooltip;
    MISSING_TYPE *$__lazy_storage_$_memberTooltip;
}

- (void).cxx_destruct;
- (id)init;

@end

