//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr33YahooSponsoredMomentsViewsManager : NSObject
{
    MISSING_TYPE *ad;
    MISSING_TYPE *clientSideAnaltyicsLogger;
    MISSING_TYPE *isVisible;
    MISSING_TYPE *firedEnterEvent;
    MISSING_TYPE *firedExitEvent;
    MISSING_TYPE *adView;
    MISSING_TYPE *adContainerView;
    MISSING_TYPE *tableCellView;
    MISSING_TYPE *$__lazy_storage_$_footer;
    MISSING_TYPE *$__lazy_storage_$_header;
}

- (void).cxx_destruct;
- (id)init;
- (void)updateColors:(id)arg1;
- (void)contentOffsetCalculator:(id)arg1 offsetChanged:(struct CGPoint)arg2 inView:(id)arg3;
- (void)didTapHeader;
- (void)dealloc;

@end

