//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSDate, NSString, _TtC9Timelines26TimelineObjectCommonValues, _TtC9Timelines30GroupChatBlogActionPermissions, _TtC9Timelines8APILinks;

@interface _TtC9Timelines32GroupChatBlogTimelineObjectModel : NSObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *type;
    MISSING_TYPE *commonValues;
    MISSING_TYPE *blogName;
    MISSING_TYPE *blogUUID;
    MISSING_TYPE *avatarURL;
    MISSING_TYPE *isGroupOwner;
    MISSING_TYPE *lastRead;
    MISSING_TYPE *isMember;
    MISSING_TYPE *permissions;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSDate *date;
@property(nonatomic, readonly) NSArray *supplyLogging;
@property(nonatomic, readonly) NSString *serveId;
@property(nonatomic, readonly) _TtC9Timelines8APILinks *links;
@property(nonatomic, readonly) NSArray *dismissalOptions;
- (_Bool)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 commonValues:(id)arg2 blogName:(id)arg3 blogUUID:(id)arg4 avatarURL:(id)arg5 isMember:(_Bool)arg6 isGroupOwner:(_Bool)arg7 permissions:(id)arg8 lastRead:(id)arg9;
@property(nonatomic, readonly) _TtC9Timelines30GroupChatBlogActionPermissions *permissions; // @synthesize permissions;
@property(nonatomic, readonly) _Bool isMember; // @synthesize isMember;
@property(nonatomic, readonly) _Bool hasPendingInvitation;
@property(nonatomic, readonly) _Bool hasPendingRequest;
@property(nonatomic, readonly) NSDate *lastRead;
@property(nonatomic, readonly) _Bool isGroupOwner; // @synthesize isGroupOwner;
@property(nonatomic, readonly) NSString *avatarURL;
@property(nonatomic, readonly) NSString *blogUUID;
@property(nonatomic, readonly) NSString *blogName;
@property(nonatomic, readonly) _TtC9Timelines26TimelineObjectCommonValues *commonValues; // @synthesize commonValues;
@property(nonatomic, readonly) int type; // @synthesize type;
@property(nonatomic, readonly) NSString *identifier;

@end

