//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "NSTextStorageDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC9PostForms21PostFormTextBlockView : UIView <NSTextStorageDelegate>
{
    MISSING_TYPE *textView;
    MISSING_TYPE *textBlock;
    MISSING_TYPE *scrollView;
    MISSING_TYPE *orderedLabel;
    MISSING_TYPE *placeholderLabel;
    MISSING_TYPE *blockQuoteVerticalBar;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *$__lazy_storage_$_topConstraint;
    MISSING_TYPE *updateFormattedString;
    MISSING_TYPE *forceHidePlaceholder;
    MISSING_TYPE *chatRightAnchor;
    MISSING_TYPE *$__lazy_storage_$_autoBoldRegex;
}

- (void).cxx_destruct;
- (void)updateColors:(id)arg1;
- (void)textStorage:(id)arg1 didProcessEditing:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4;
- (void)textStorage:(id)arg1 willProcessEditing:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

