//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12KanvasCamera14CameraRecorder : NSObject
{
    MISSING_TYPE *recordingDelegate;
    MISSING_TYPE *url;
    MISSING_TYPE *size;
    MISSING_TYPE *assetWriter;
    MISSING_TYPE *assetWriterVideoInput;
    MISSING_TYPE *assetWriterAudioInput;
    MISSING_TYPE *assetWriterPixelBufferInput;
    MISSING_TYPE *photoOutput;
    MISSING_TYPE *videoOutput;
    MISSING_TYPE *audioOutput;
    MISSING_TYPE *currentRecordingMode;
    MISSING_TYPE *segmentsHandler;
    MISSING_TYPE *photoOutputHandler;
    MISSING_TYPE *gifVideoOutputHandler;
    MISSING_TYPE *videoOutputHandlers;
    MISSING_TYPE *takingPhoto;
    MISSING_TYPE *settings;
}

- (void).cxx_destruct;
- (id)init;
- (void)appWillResignActive;
- (void)dealloc;

@end

