//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr28LoggedOutLinkRouterRegistrar : NSObject
{
    MISSING_TYPE *userAuthenticationController;
    MISSING_TYPE *session;
    MISSING_TYPE *preferences;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *notificationCenter;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *applicationCoordinator;
}

- (void).cxx_destruct;
- (id)init;
- (void)registerAllRoutesWithRouter:(id)arg1;
- (id)initWithUserAuthenticationController:(id)arg1 session:(id)arg2 preferences:(id)arg3 coreDataController:(id)arg4 notificationCenter:(id)arg5 analyticsBuffer:(id)arg6 applicationCoordinator:(id)arg7;

@end

