//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr24FacebookBiddableAdLoader : NSObject
{
    MISSING_TYPE *fbNativeAd;
    MISSING_TYPE *nativeAd;
}

- (void).cxx_destruct;
- (id)init;
- (void)nativeAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdDidLoad:(id)arg1;

@end

