//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC9Timelines21TimelineRepositoryKey : NSObject
{
    MISSING_TYPE *uniqueIdentifier;
}

+ (id)getKeyFor:(id)arg1;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *debugDescription;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;

@end

