//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8SharedUI25ColorPickerViewController : UIViewController
{
    MISSING_TYPE *PostFormColorPickerCellIdentifier;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *currentHighlightedIndexPath;
    MISSING_TYPE *colors;
    MISSING_TYPE *$__lazy_storage_$_collectionView;
    MISSING_TYPE *shadowLayer;
    MISSING_TYPE *addShadow;
    MISSING_TYPE *delegate;
    MISSING_TYPE *layout;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

