//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP10CoreTumblr24LinkAttributeTapHandling_-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6Tumblr19LinkAttributeRouter : NSObject <_TtP10CoreTumblr24LinkAttributeTapHandling_>
{
    MISSING_TYPE *navigationController;
    MISSING_TYPE *session;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *messagingCoordinator;
    MISSING_TYPE *supplyLoggingManager;
}

- (void).cxx_destruct;
- (id)init;
- (long long)handleBlogLinkTapForBlogNamed:(id)arg1 postID:(id)arg2 tag:(id)arg3 inCell:(id)arg4;
- (void)handleLinkTapFromAttribute:(id)arg1;

@end

