//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

#import "_TtP14TelegraphSwift10Authorizer_-Protocol.h"

@interface _TtCC6Tumblr19RealTimeCoordinatorP33_18BECA4C40A9FCAE3AC839F62A321DBF19TelegraphAuthorizer : _TtCs12_SwiftObject <_TtP14TelegraphSwift10Authorizer_>
{
}

- (void)fetchAuthValueWithSocketID:(id)arg1 channelName:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;

@end

