//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr32DashboardTimelinesViewController : UIViewController
{
    MISSING_TYPE *timelineViewController;
    MISSING_TYPE *dashboardDataService;
    MISSING_TYPE *timelineViewControllerFactory;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *session;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *dashboardPULTLogger;
    MISSING_TYPE *newPostIndicatorController;
    MISSING_TYPE *didFinishInitialDisplayOfDashboardTimeline;
    MISSING_TYPE *scrollToTopHandler;
    MISSING_TYPE *dashboardTimelineFetcher;
    MISSING_TYPE *supplyLoggingManager;
    MISSING_TYPE *liveUpdater;
    MISSING_TYPE *networkSpeedEstimateSender;
    MISSING_TYPE *frameDropRecorder;
    MISSING_TYPE *frameDropDelegate;
    MISSING_TYPE *dashboardHeaderManager;
    MISSING_TYPE *scrollEventHandler;
    MISSING_TYPE *headerView;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *dashboardPagingController;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)stylingForNavigationBar;
- (void)updateColors:(id)arg1;
- (void)updateChangedUI:(id)arg1;
- (void)dataDisplayViewUpdaterFinishedUpdating:(id)arg1 latest:(_Bool)arg2 userGenerated:(_Bool)arg3 error:(id)arg4 apiError:(id)arg5;
- (void)dataDisplayViewUpdaterStartedUpdating:(id)arg1 latest:(_Bool)arg2 userGenerated:(_Bool)arg3;
- (void)reselect;
- (void)updateTheming:(id)arg1;
@property(nonatomic, readonly) UIViewController *childViewControllerForStatusBarStyle;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (void)refreshWithAdditionalParameters:(id)arg1;
- (void)dashboardDidBecomeActive;
- (id)initWithCoreDataController:(id)arg1 analyticsBuffer:(id)arg2 linkRouter:(id)arg3 session:(id)arg4 preferences:(id)arg5 clientSideAdSources:(id)arg6 dashboardPULTLogger:(id)arg7 supplyLoggingManager:(id)arg8 liveUpdater:(id)arg9 appColorScheme:(id)arg10 dashboardPagingController:(id)arg11;

@end

