//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSDate, NSDictionary, NSString, _TtC9Timelines26TimelineObjectCommonValues, _TtC9Timelines8APILinks;

@interface _TtC9Timelines30ChatMessageTimelineObjectModel : NSObject
{
    MISSING_TYPE *identifier;
    MISSING_TYPE *commonValues;
    MISSING_TYPE *blogDictionary;
    MISSING_TYPE *content;
    MISSING_TYPE *type;
    MISSING_TYPE *isOwner;
    MISSING_TYPE *status;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSDate *date;
@property(nonatomic, readonly) NSArray *supplyLogging;
@property(nonatomic, readonly) NSString *serveId;
@property(nonatomic, readonly) _TtC9Timelines8APILinks *links;
@property(nonatomic, readonly) NSArray *dismissalOptions;
- (_Bool)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 commonValues:(id)arg2 isOwner:(_Bool)arg3 content:(id)arg4 blogInfo:(id)arg5 status:(long long)arg6;
@property(nonatomic, readonly) NSString *conversationalIdentifier;
@property(nonatomic, readonly) long long status; // @synthesize status;
@property(nonatomic, readonly) _Bool isOwner; // @synthesize isOwner;
@property(nonatomic, readonly) int type; // @synthesize type;
@property(nonatomic, readonly) NSDictionary *content;
@property(nonatomic, readonly) NSDictionary *blogDictionary;
@property(nonatomic, readonly) _TtC9Timelines26TimelineObjectCommonValues *commonValues; // @synthesize commonValues;
@property(nonatomic, readonly) NSString *identifier;

@end

