//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, NSURLSession;
@protocol _TtP14TelegraphSwift14PusherDelegate_;

@interface _TtC14TelegraphSwift12NativePusher : NSObject
{
    MISSING_TYPE *CLIENT_API_V1_ENDPOINT;
    MISSING_TYPE *LIBRARY_NAME_AND_VERSION;
    MISSING_TYPE *URLSession;
    MISSING_TYPE *failedRequestAttempts;
    MISSING_TYPE *maxFailedRequestAttempts;
    MISSING_TYPE *delegate;
    MISSING_TYPE *requestQueue;
    MISSING_TYPE *pusherAppKey;
    MISSING_TYPE *clientId;
}

- (void).cxx_destruct;
- (void)unsubscribeWithInterestName:(id)arg1;
- (void)setSubscriptionsWithInterests:(id)arg1;
- (void)subscribeWithInterestName:(id)arg1;
- (void)registerWithDeviceToken:(id)arg1;
- (void)setPusherAppKeyWithPusherAppKey:(id)arg1;
- (id)init;
@property(nonatomic, copy) NSString *clientId;
@property(nonatomic) __weak id <_TtP14TelegraphSwift14PusherDelegate_> delegate; // @synthesize delegate;
@property(nonatomic, retain) NSURLSession *URLSession; // @synthesize URLSession;

@end

