//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC10TMAudioKit15AudioController : _TtCs12_SwiftObject
{
    MISSING_TYPE *$__lazy_storage_$_audioView;
    MISSING_TYPE *remoteController;
    MISSING_TYPE *player;
    MISSING_TYPE *audioModels;
    MISSING_TYPE *progressTimer;
    MISSING_TYPE *presentationState;
    MISSING_TYPE *pivotPoint;
    MISSING_TYPE *expectedWidth;
    MISSING_TYPE *postModel;
    MISSING_TYPE *trackIndex;
    MISSING_TYPE *shouldAnimate;
    MISSING_TYPE *isDismissing;
    MISSING_TYPE *isHidden;
    MISSING_TYPE *delegate;
}

- (void)updateAudioControl;

@end

