//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr19NotesViewController : UIViewController
{
    MISSING_TYPE *timelineViewController;
    MISSING_TYPE *subscriptionCoordinator;
    MISSING_TYPE *dataDisplayViewUpdaterDelegate;
    MISSING_TYPE *postNoteConfiguration;
    MISSING_TYPE *titleUpdater;
    MISSING_TYPE *headerView;
    MISSING_TYPE *timelineTopAnchor;
    MISSING_TYPE *screenEventProvider;
    MISSING_TYPE *replyCoordinator;
    MISSING_TYPE *replyFooterController;
    MISSING_TYPE *replySender;
    MISSING_TYPE *replyMentionTypeaheadRequestController;
    MISSING_TYPE *replyMentionTypeaheadResultsController;
    MISSING_TYPE *disposeBag;
    MISSING_TYPE *keyboardNotificationObserver;
    MISSING_TYPE *visibleKeyboardFrame;
    MISSING_TYPE *visibilityStatusViewController;
    MISSING_TYPE *noteDataService;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *session;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *eventProvider;
    MISSING_TYPE *scrollToBottom;
    MISSING_TYPE *typingIndicatorEnabled;
    MISSING_TYPE *realtimeCoordinator;
    MISSING_TYPE *textStateManager;
    MISSING_TYPE *replyToBlogSubject;
    MISSING_TYPE *$__lazy_storage_$_eventsCoordinator;
    MISSING_TYPE *newNotesIndicatorController;
    MISSING_TYPE *draggingHandler;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *$__lazy_storage_$_bubbleGroupPositionUpdater;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)handleTableViewDidUpdateWithNotification:(id)arg1;
- (id)stylingForNavigationBar;
- (void)updateChangedUI:(id)arg1;
- (void)updateColors:(id)arg1;
@property(nonatomic, readonly) UIViewController *childViewControllerForStatusBarStyle;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) _Bool hidesBottomBarWhenPushed;
- (id)initWithCoder:(id)arg1;

@end

