//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr16BlogRowViewModel : NSObject
{
    MISSING_TYPE *customTitle;
    MISSING_TYPE *blogName;
    MISSING_TYPE *blogTitle;
    MISSING_TYPE *blogInfo;
    MISSING_TYPE *privateBlog;
    MISSING_TYPE *isNSFW;
    MISSING_TYPE *isFollowing;
    MISSING_TYPE *hideFollowButton;
    MISSING_TYPE *hideSnowmanButton;
    MISSING_TYPE *showLightningOnSnowman;
    MISSING_TYPE *avatarShape;
    MISSING_TYPE *avatarSize;
    MISSING_TYPE *hidesFollowButtonWhenFollowing;
    MISSING_TYPE *tappingFollowButtonAnimatesFollowedBlogAvatar;
}

- (void).cxx_destruct;
- (id)init;

@end

