//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSURL, _TtC9PostForms22PostFormAppAttribution;

@interface _TtC9PostForms18PostFormAudioBlock : NSObject
{
    MISSING_TYPE *provider;
    MISSING_TYPE *title;
    MISSING_TYPE *artist;
    MISSING_TYPE *album;
    MISSING_TYPE *mediaURL;
    MISSING_TYPE *externalURL;
    MISSING_TYPE *deepLinkURL;
    MISSING_TYPE *images;
    MISSING_TYPE *attribution;
    MISSING_TYPE *acceptsUserInput;
    MISSING_TYPE *isTransient;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (id)init;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic, readonly) long long hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) _TtC9PostForms22PostFormAppAttribution *attribution; // @synthesize attribution;
@property(nonatomic, readonly) NSURL *deepLinkURL;
@property(nonatomic, readonly) NSURL *externalURL;
@property(nonatomic, readonly) NSURL *mediaURL;

@end

