//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Tumblr16TabBarController.h"

@interface _TtC6Tumblr16TabBarController (Tumblr9)
- (void)updateTheming:(id)arg1 animated:(_Bool)arg2;
- (void)updateTheming:(id)arg1;
@end

