//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UISearchResultsUpdating-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6Tumblr36TMPanelServerFlagTableViewController : UITableViewController <UISearchResultsUpdating>
{
    MISSING_TYPE *features;
    MISSING_TYPE *filteredFeatures;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *session;
    MISSING_TYPE *searchController;
    MISSING_TYPE *EstimatedRowHeight;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadConfigWithRefreshControl:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithAppColorScheme:(id)arg1 coreDataController:(id)arg2 session:(id)arg3;

@end

