//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr23PostNotesNewReplySender : _TtCs12_SwiftObject
{
    MISSING_TYPE *shouldReloadObservable;
    MISSING_TYPE *disposeBag;
    MISSING_TYPE *providerUUID;
    MISSING_TYPE *newReplyStates;
}

@end

