//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC9GroupChat29GroupChatTimelineCellProvider : NSObject
{
    MISSING_TYPE *timelineContainer;
    MISSING_TYPE *groupID;
    MISSING_TYPE *hideCellControls;
    MISSING_TYPE *themeColor;
    MISSING_TYPE *invitationManager;
    MISSING_TYPE *cellViewModelDelegate;
    MISSING_TYPE *cellDelegate;
}

- (void).cxx_destruct;
- (id)init;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)updateRowIn:(id)arg1 at:(id)arg2 with:(id)arg3 animated:(_Bool)arg4;
- (long long)dataDisplayView:(id)arg1 numberOfRowsOrItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInDataDisplayView:(id)arg1;
- (id)fetchedResults;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)numberOfFetchedSections;
- (id)fetchedObjectAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;

@end

