//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, TMPostCell;

@interface _TtC6Tumblr24CensorWrapperContentView : UIView
{
    MISSING_TYPE *peekDelegate;
    MISSING_TYPE *peekLink;
    MISSING_TYPE *userIsFullOver18User;
    MISSING_TYPE *$__lazy_storage_$_censorView;
    MISSING_TYPE *postCell;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateColors:(id)arg1;
- (void)showAdultContentHelpCenter;
- (id)peekText;
- (void)showPreview;
@property(nonatomic) __weak TMPostCell *postCell; // @synthesize postCell;
- (void)prepareForReuse;
- (void)setupWithPostContentViewModel:(id)arg1 appColorScheme:(id)arg2 beaconCache:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

