//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TMEditableBlogHeaderSubview-Protocol.h"

@class MISSING_TYPE, _TtC6Tumblr20CustomizeColorButton;

@interface _TtC6Tumblr23CustomizeColorButtonRow : UIView <TMEditableBlogHeaderSubview>
{
    MISSING_TYPE *accentButton;
    MISSING_TYPE *backgroundButton;
}

- (void).cxx_destruct;
- (void)updateTheming:(id)arg1;
- (void)setCustomizationAlpha:(double)arg1;
- (void)deselectAllButtons;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _TtC6Tumblr20CustomizeColorButton *backgroundButton; // @synthesize backgroundButton;
@property(nonatomic, readonly) _TtC6Tumblr20CustomizeColorButton *accentButton; // @synthesize accentButton;

@end

