//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, UIColor;

@interface _TtC8TumblrUI24DashboardImageFailedView : UIView
{
    MISSING_TYPE *$__lazy_storage_$_defaultCameraIcon;
    MISSING_TYPE *$__lazy_storage_$_cameraIconView;
    MISSING_TYPE *$__lazy_storage_$_cameraXIconView;
    MISSING_TYPE *$__lazy_storage_$_retryLabel;
    MISSING_TYPE *$__lazy_storage_$_loadingView;
    MISSING_TYPE *isRetrying;
}

- (void).cxx_destruct;
- (void)updateConstraints;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 failedImage:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isRetrying; // @synthesize isRetrying;
@property(nonatomic, retain) UIColor *tintColor;

@end

