//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TMBlogUUID-Protocol.h"

@class MISSING_TYPE, NSString, _TtC6Tumblr16BlogDataProvider;
@protocol TMSession, TMTumblrCoreDataController, _TtP9Analytics14EventBuffering_;

@interface _TtC6Tumblr18BlogViewController : UIViewController <TMBlogUUID>
{
    MISSING_TYPE *style;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *session;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *blogHeaderCoordinator;
    MISSING_TYPE *blogNavigationOptionsManager;
    MISSING_TYPE *notificationObserver;
    MISSING_TYPE *eventualNavigationController;
    MISSING_TYPE *currentAlertController;
    MISSING_TYPE *blogDataProvider;
    MISSING_TYPE *preferences;
    MISSING_TYPE *supplyLoggingManager;
    MISSING_TYPE *context;
    MISSING_TYPE *followCoordinator;
    MISSING_TYPE *followCoordinatorObserver;
    MISSING_TYPE *eventProvider;
    MISSING_TYPE *screenEventProvider;
    MISSING_TYPE *submissionsCoordinator;
    MISSING_TYPE *associatedViewProvider;
    MISSING_TYPE *associatedViewPresentationCoordinator;
    MISSING_TYPE *blogCustomizationManager;
    MISSING_TYPE *blogHeaderViewControllerDelegate;
    MISSING_TYPE *blogPageSelectorViewController;
    MISSING_TYPE *blogPageTimelines;
    MISSING_TYPE *currentBlogPageType;
    MISSING_TYPE *blogPageSelectorYConstraint;
    MISSING_TYPE *censorViewToggler;
    MISSING_TYPE *blogTheme;
    MISSING_TYPE *isPrimary;
    MISSING_TYPE *blogBelongsToCurrentUser;
    MISSING_TYPE *beingPreviewed;
    MISSING_TYPE *showedStatusIndicatorPopover;
    MISSING_TYPE *canDisplayBlogPageSelector;
    MISSING_TYPE *blogPageSelectorIsExpanded;
    MISSING_TYPE *isDragging;
    MISSING_TYPE *lastOffsetY;
    MISSING_TYPE *loadingIndicator;
    MISSING_TYPE *blogNotificationCTAPopover;
    MISSING_TYPE *emptyView;
    MISSING_TYPE *presenterAnimator;
    MISSING_TYPE *screenIdentifier;
    MISSING_TYPE *blockManager;
    MISSING_TYPE *censorOverride;
    MISSING_TYPE *dummyTableView;
    MISSING_TYPE *blogNameChangeObserver;
    MISSING_TYPE *blogUUID;
    MISSING_TYPE *shareCoordinator;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)stylingForNavigationBar;
- (void)updateColors:(id)arg1;
- (void)updateChangedUI:(id)arg1;
@property(nonatomic, readonly) UIViewController *viewController;
- (void)headerDidTriggerRefresh;
- (void)stopPreview;
- (void)startPreviewingWithEventualContainerNavigationController:(id)arg1;
- (void)commitViewController:(id)arg1 sourceViewController:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, copy) NSString *blogUUID;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
@property(nonatomic, readonly) long long preferredStatusBarUpdateAnimation;
- (_Bool)shouldApplyTheme;
@property(nonatomic) _Bool censorOverride; // @synthesize censorOverride;
@property(nonatomic, copy) NSString *screenIdentifier;
@property(nonatomic, readonly) _TtC6Tumblr16BlogDataProvider *blogDataProvider; // @synthesize blogDataProvider;
@property(nonatomic, readonly) id <TMSession> session; // @synthesize session;
@property(nonatomic, readonly) id <_TtP9Analytics14EventBuffering_> analyticsBuffer; // @synthesize analyticsBuffer;
@property(nonatomic, readonly) id <TMTumblrCoreDataController> coreDataController; // @synthesize coreDataController;

@end

