//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr45ThemeableCollapsedNavigationBarViewController : UIViewController
{
    MISSING_TYPE *blogName;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *linkRouter;
    MISSING_TYPE *session;
    MISSING_TYPE *clientSideAdSources;
    MISSING_TYPE *timelineViewController;
    MISSING_TYPE *permalinkHeaderView;
    MISSING_TYPE *navigationItemTitleViewProvider;
    MISSING_TYPE *navigationItemRightBarButtonViewProvider;
    MISSING_TYPE *timelineTableViewHeaderViewUpdater;
    MISSING_TYPE *supplyLoggingManager;
    MISSING_TYPE *enterScreenEventProvider;
    MISSING_TYPE *showNavigationBar;
    MISSING_TYPE *beingPreviewed;
    MISSING_TYPE *isViewVisible;
    MISSING_TYPE *receivedTheme;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *followButton;
}

+ (id)appealableTimelineViewControllerForBlogWithName:(id)arg1 blogUUID:(id)arg2 coreDataController:(id)arg3 analyticsBuffer:(id)arg4 linkRouter:(id)arg5 session:(id)arg6 clientSideAdSources:(id)arg7 appColorScheme:(id)arg8;
+ (id)draftsTimelineViewControllerForBlogWithName:(id)arg1 coreDataController:(id)arg2 analyticsBuffer:(id)arg3 linkRouter:(id)arg4 session:(id)arg5 clientSideAdSources:(id)arg6 appColorScheme:(id)arg7;
+ (id)followersTimelineViewControllerForBlogWithUUID:(id)arg1 blogTheme:(id)arg2 coreDataController:(id)arg3 analyticsBuffer:(id)arg4 linkRouter:(id)arg5 session:(id)arg6 clientSideAdSources:(id)arg7 appColorScheme:(id)arg8;
+ (id)blogTagTimelineViewControllerForBlogNamed:(id)arg1 tag:(id)arg2 coreDataController:(id)arg3 analyticsBuffer:(id)arg4 linkRouter:(id)arg5 session:(id)arg6 clientSideAdSources:(id)arg7;
+ (id)genericTimelineViewControllerWithPath:(id)arg1 parameters:(id)arg2 title:(id)arg3 blogName:(id)arg4 coreDataController:(id)arg5 analyticsBuffer:(id)arg6 linkRouter:(id)arg7 session:(id)arg8 clientSideAdSources:(id)arg9 supplyLoggingManager:(id)arg10 timelineType:(id)arg11;
+ (id)flaggedPostTimelineViewControllerForBlogNamed:(id)arg1 blogUUID:(id)arg2 postID:(id)arg3 coreDataController:(id)arg4 analyticsBuffer:(id)arg5 linkRouter:(id)arg6 session:(id)arg7 clientSideAdSources:(id)arg8 supplyLoggingManager:(id)arg9 appColorScheme:(id)arg10;
+ (id)postPermalinkTimelineViewControllerForBlogNamed:(id)arg1 postID:(id)arg2 reblogViewModel:(id)arg3 revealPostFilteredByUserDefinedTag:(_Bool)arg4 coreDataController:(id)arg5 analyticsBuffer:(id)arg6 linkRouter:(id)arg7 session:(id)arg8 clientSideAdSources:(id)arg9 supplyLoggingManager:(id)arg10;
+ (id)messagePermalinkTimelineViewControllerForBlogNamed:(id)arg1 postID:(id)arg2 coreDataController:(id)arg3 analyticsBuffer:(id)arg4 linkRouter:(id)arg5 session:(id)arg6 clientSideAdSources:(id)arg7 supplyLoggingManager:(id)arg8 appColorScheme:(id)arg9;
+ (id)messagesTimelineViewControllerForBlogNamed:(id)arg1 coreDataController:(id)arg2 analyticsBuffer:(id)arg3 linkRouter:(id)arg4 session:(id)arg5 clientSideAdSources:(id)arg6 supplyLoggingManager:(id)arg7 appColorScheme:(id)arg8;
- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)stylingForNavigationBar;
- (void)updateFollowButtonVisibility:(_Bool)arg1;
- (id)avatarImageViewForFollowButton:(id)arg1;
- (id)carouselIndexForFollowButton:(id)arg1;
- (id)blogInfoForFollowButton:(id)arg1;
- (void)viewCurrentBlog:(id)arg1;
- (void)stopPreview;
- (void)startPreviewingWithEventualContainerNavigationController:(id)arg1;
- (void)updateColors:(id)arg1;
- (void)updateChangedUI:(id)arg1;
- (id)preferredTheme;
- (void)updateTheming:(id)arg1;
- (_Bool)shouldApplyTheme;
@property(nonatomic, readonly) UIViewController *childViewControllerForStatusBarStyle;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) _Bool hidesBottomBarWhenPushed;

@end

