//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;
@protocol _TtP14TelegraphSwift10Authorizer_, _TtP14TelegraphSwift26AuthRequestBuilderProtocol_;

@interface _TtC14TelegraphSwift12OCAuthMethod : NSObject
{
    MISSING_TYPE *type;
    MISSING_TYPE *secret;
    MISSING_TYPE *authEndpoint;
    MISSING_TYPE *authRequestBuilder;
    MISSING_TYPE *authorizer;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithAuthorizer:(id)arg1;
- (id)initWithSecret:(id)arg1;
- (id)initWithAuthRequestBuilder:(id)arg1;
- (id)initWithAuthEndpoint:(id)arg1;
- (id)initWithType:(long long)arg1;
@property(nonatomic, retain) id <_TtP14TelegraphSwift10Authorizer_> authorizer; // @synthesize authorizer;
@property(nonatomic, retain) id <_TtP14TelegraphSwift26AuthRequestBuilderProtocol_> authRequestBuilder; // @synthesize authRequestBuilder;
@property(nonatomic, copy) NSString *authEndpoint;
@property(nonatomic, copy) NSString *secret;
@property(nonatomic) long long type; // @synthesize type;

@end

