//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Tumblr16TabBarController.h"

@interface _TtC6Tumblr16TabBarController (Tumblr13)
- (void)didDoubleTap:(id)arg1;
- (void)didLongPress:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@end

