//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC12KanvasCamera18PhotoOutputHandler.h"

@interface _TtC12KanvasCamera18PhotoOutputHandler (KanvasCamera)
- (void)captureOutput:(id)arg1 didFinishProcessingPhoto:(id)arg2 error:(id)arg3;
@end

