//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr39SearchResultsTableViewSectionHeaderView : UITableViewHeaderFooterView
{
    MISSING_TYPE *$__lazy_storage_$_titleLabel;
    MISSING_TYPE *$__lazy_storage_$_actionButton;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *layoutConstraints;
    MISSING_TYPE *titleInsets;
    MISSING_TYPE *buttonTapHandler;
}

- (void).cxx_destruct;
- (void)updateColors:(id)arg1;
- (void)didTapButton;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;

@end

