//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr29DefaultSegmentedHeaderUpdater : _TtCs12_SwiftObject
{
    MISSING_TYPE *segmentedHeaderView;
    MISSING_TYPE *defaultOffset;
    MISSING_TYPE *segmentedHeaderTopConstraint;
}

@end

