//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC19DashboardPULTLogger19DashboardPULTLogger : NSObject
{
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *notificationCenter;
    MISSING_TYPE *event;
    MISSING_TYPE *sendEventsOnAppInitComplete;
    MISSING_TYPE *trackedExperiments;
    MISSING_TYPE *serverExperiments;
    MISSING_TYPE *downwardsPaginatorStartTime;
    MISSING_TYPE *downwardsPaginatorStopTime;
    MISSING_TYPE *sendEventsOnLoadingIndicatorStop;
    MISSING_TYPE *isLoaded;
}

+ (id)criticalPULTPathCompleteNotificationName;
+ (void)setMainTime:(id)arg1;
+ (id)mainTime;
- (void).cxx_destruct;
- (id)init;
- (void)appBackgrounded;
- (void)appInitComplete;
- (void)appInitWithMainTime:(id)arg1 startTime:(id)arg2;
- (id)initWithAnalyticsBuffer:(id)arg1 notificationCenter:(id)arg2 trackedExperiments:(id)arg3;

@end

