//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class MISSING_TYPE;

@interface _TtC9PostForms21PostFormToolbarButton : UIButton
{
    MISSING_TYPE *$__lazy_storage_$_iconView;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)bounceUp;
- (void)pressedUp;
- (void)pressedDown;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;

@end

