//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC9ComposeUI25PostFormExternalVideoView : UIView
{
    MISSING_TYPE *$__lazy_storage_$_imageView;
    MISSING_TYPE *$__lazy_storage_$_playButtonView;
    MISSING_TYPE *onPlayButtonTapped;
    MISSING_TYPE *canAutoPlay;
    MISSING_TYPE *videoURL;
    MISSING_TYPE *muteButton;
}

- (void).cxx_destruct;
- (void)playButtonTapped;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

