//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;
@protocol _TtP13OnboardingKit36OnboardingFlowViewControllerDelegate_;

@interface _TtC13OnboardingKit26InterstitialViewController : UIViewController
{
    MISSING_TYPE *viewModel;
    MISSING_TYPE *eventProvider;
    MISSING_TYPE *animationSequences;
    MISSING_TYPE *animationStartTime;
    MISSING_TYPE *hasShownSkipButton;
    MISSING_TYPE *skipButtonBottomConstraint;
    MISSING_TYPE *$__lazy_storage_$_contentView;
    MISSING_TYPE *$__lazy_storage_$_skipButton;
    MISSING_TYPE *$__lazy_storage_$_toggleSkipButton;
    MISSING_TYPE *$__lazy_storage_$_titleOverlay;
    MISSING_TYPE *$__lazy_storage_$_postView;
    MISSING_TYPE *$__lazy_storage_$_disappearingGradient;
    MISSING_TYPE *$__lazy_storage_$_navBar;
    MISSING_TYPE *$__lazy_storage_$_sparkles;
    MISSING_TYPE *$__lazy_storage_$_moreSparkles;
    MISSING_TYPE *$__lazy_storage_$_magnifyingGlass;
    MISSING_TYPE *$__lazy_storage_$_finalTitles;
    MISSING_TYPE *$__lazy_storage_$_progressBarBackground;
    MISSING_TYPE *$__lazy_storage_$_progressBar;
    MISSING_TYPE *onboardingFlowViewControllerDelegate;
    MISSING_TYPE *haltAnimations;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)viewController;
- (void)skipAnimations;
- (void)showOrHideSkip;
- (void)resumeAnimations;
- (void)pauseAnimations;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
@property(nonatomic, readonly) _Bool shouldAutorotate;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
@property(nonatomic) __weak id <_TtP13OnboardingKit36OnboardingFlowViewControllerDelegate_> onboardingFlowViewControllerDelegate; // @synthesize onboardingFlowViewControllerDelegate;

@end

