//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC9GroupChat27ConversationalItemViewModel : NSObject
{
    MISSING_TYPE *blogInfo;
    MISSING_TYPE *bottomPadding;
    MISSING_TYPE *npfLayout;
    MISSING_TYPE *cellWidth;
    MISSING_TYPE *conversationTitle;
    MISSING_TYPE *topPadding;
    MISSING_TYPE *alignRight;
    MISSING_TYPE *bubbleBorderWidth;
    MISSING_TYPE *bubbleBorderColor;
    MISSING_TYPE *contentConfigurations;
    MISSING_TYPE *bubbleBackgroundColor;
    MISSING_TYPE *textColor;
    MISSING_TYPE *singleTextBlockAttributedString;
    MISSING_TYPE *hasVerticalPadding;
    MISSING_TYPE *shouldOverrideBubbleTextColor;
    MISSING_TYPE *conversationalIdentifier;
    MISSING_TYPE *isCensored;
    MISSING_TYPE *conversationalItemType;
    MISSING_TYPE *theme;
    MISSING_TYPE *shouldDisableCopyInTextView;
    MISSING_TYPE *hasFailureInfoButton;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithConversationalItem:(id)arg1 alignRightAllOwnBlogs:(_Bool)arg2 cellWidth:(double)arg3 currentUser:(id)arg4 theme:(id)arg5 appColorScheme:(id)arg6;

@end

