//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Tumblr16TabBarController.h"

@class _TtC6Tumblr22ActivityViewController;
@protocol TMComposeFlowControllerDelegate;

@interface _TtC6Tumblr16TabBarController (Tumblr2)
- (void)showNotesWithBlogName:(id)arg1 postID:(id)arg2;
- (id)bannerPresentationViewController;
- (void)presentComposeFlowController:(id)arg1;
- (void)showAuthorizeViewControllerWithOAuthToken:(id)arg1;
- (void)showInboxFor:(id)arg1;
- (void)showExplore;
- (id)showActivityAnimated:(_Bool)arg1;
- (id)showActivityOnSegment:(long long)arg1 animated:(_Bool)arg2;
- (void)showCompose;
- (void)showExploreWithSearchBar:(_Bool)arg1;
- (void)showTagWithName:(id)arg1 searchFilter:(id)arg2;
- (void)showLaunchActionDestinationViewController:(id)arg1 presentationStyle:(long long)arg2;
- (void)refreshDashboardWithAdditionalParameters:(id)arg1;
- (void)showDashboard;
@property(nonatomic, readonly) id <TMComposeFlowControllerDelegate> composeFlowControllerDelegate;
@property(nonatomic, readonly) _TtC6Tumblr22ActivityViewController *activityViewController;
@end

