//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC12KanvasCamera17IgnoreTouchesView.h"

@class MISSING_TYPE;

@interface _TtC12KanvasCamera9TrashView : _TtC12KanvasCamera17IgnoreTouchesView
{
    MISSING_TYPE *borderCircle;
    MISSING_TYPE *backgroundCircle;
    MISSING_TYPE *openedTrash;
    MISSING_TYPE *closedTrash;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

