//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC12KanvasCamera17IgnoreTouchesView.h"

@class MISSING_TYPE;

@interface _TtC12KanvasCamera15ColorPickerView : _TtC12KanvasCamera17IgnoreTouchesView
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *selectorBackground;
    MISSING_TYPE *selectorPannableArea;
    MISSING_TYPE *gradient;
}

- (void).cxx_destruct;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)selectorLongPressedWithRecognizer:(id)arg1;
- (void)selectorPannedWithRecognizer:(id)arg1;
- (void)selectorTappedWithRecognizer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

