//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@class MISSING_TYPE;

@interface _TtC10GIFCreator8HUDLabel : UILabel
{
    MISSING_TYPE *lastShowMessageStartTime;
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

