//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "_TtP11TumblrTheme20AppUIChangedListener_-Protocol.h"

@class MISSING_TYPE, NSString;

@interface _TtC6Tumblr21AccountViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, _TtP11TumblrTheme20AppUIChangedListener_>
{
    MISSING_TYPE *blogUUID;
    MISSING_TYPE *tableView;
    MISSING_TYPE *viewModel;
    MISSING_TYPE *viewModelFactory;
    MISSING_TYPE *blogSettingsUpdater;
    MISSING_TYPE *bannerManager;
    MISSING_TYPE *userInfoDataService;
    MISSING_TYPE *headerLoader;
    MISSING_TYPE *previewingDelegate;
    MISSING_TYPE *requestingUserData;
    MISSING_TYPE *session;
    MISSING_TYPE *blogEventProvider;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *headerHeight;
    MISSING_TYPE *cellHorizontalInset;
    MISSING_TYPE *blogSettingsRequestParameters;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)updateChangedUI:(id)arg1;
- (void)headerDidTriggerRefresh;
- (void)updateColors:(id)arg1;
- (void)updateTheming:(id)arg1;
- (id)preferredTheme;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
@property(nonatomic, readonly) long long preferredStatusBarUpdateAnimation;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)stylingForNavigationBar;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, copy) NSString *blogUUID;

@end

