//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC9PostForms19ApoDrawerController : UIViewController
{
    MISSING_TYPE *state;
    MISSING_TYPE *delegate;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *postOptionsControllerModel;
    MISSING_TYPE *postOptionsModel;
    MISSING_TYPE *isAnswer;
    MISSING_TYPE *$__lazy_storage_$_advancedPostOptionsController;
    MISSING_TYPE *$__lazy_storage_$_apoDrawerView;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)keyboardWillHideWithNotification:(id)arg1;
- (void)keyboardWillShowWithNotification:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

