//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface _TtC11CoreExplore13MiniBlogCache : NSObject
{
    MISSING_TYPE *name;
    MISSING_TYPE *title;
    MISSING_TYPE *theme;
    MISSING_TYPE *following;
    MISSING_TYPE *UUID;
    MISSING_TYPE *attributedTitle;
    MISSING_TYPE *attributedBlogDescription;
    MISSING_TYPE *layoutAttributes;
    MISSING_TYPE *posts;
    MISSING_TYPE *configuration;
    MISSING_TYPE *placementIdentifier;
    MISSING_TYPE *sponsoredBadgeURL;
    MISSING_TYPE *advertisementType;
    MISSING_TYPE *isNSFWBlog;
    MISSING_TYPE *bio;
    MISSING_TYPE *followCoordinatorObserver;
    MISSING_TYPE *privacySetting;
    MISSING_TYPE *height;
    MISSING_TYPE *width;
    MISSING_TYPE *numberOfPostViews;
}

- (void).cxx_destruct;
- (id)init;
- (id)blogInfoRepresentation;
- (void)dealloc;
- (void)updateWithJSON:(id)arg1 attributesStore:(id)arg2 context:(id)arg3;
- (id)initWithBlog:(id)arg1 posts:(id)arg2 width:(double)arg3 height:(double)arg4 numberOfPostViews:(long long)arg5 showDescription:(_Bool)arg6 configuration:(id)arg7;
- (id)initWithBlogJSON:(id)arg1 attributesStore:(id)arg2 width:(double)arg3 height:(double)arg4 numberOfPostViews:(long long)arg5 configuration:(id)arg6 context:(id)arg7;
@property(nonatomic) int advertisementType; // @synthesize advertisementType;
@property(nonatomic, copy) NSString *sponsoredBadgeURL;
@property(nonatomic, readonly) NSString *impressionIdentifier;
@property(nonatomic, copy) NSString *placementIdentifier;
@property(nonatomic, copy) NSString *name;

@end

