//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, _TtC9Timelines20GroupChatPermissions;

@interface _TtC9Timelines21GroupChatModelDetails : NSObject
{
    MISSING_TYPE *publicURL;
    MISSING_TYPE *isOwner;
    MISSING_TYPE *isMember;
    MISSING_TYPE *permissions;
    MISSING_TYPE *readState;
    MISSING_TYPE *hasBlockedUser;
    MISSING_TYPE *canModifyRequestToJoin;
    MISSING_TYPE *allowsRequestsToJoin;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool allowsRequestsToJoin; // @synthesize allowsRequestsToJoin;
@property(nonatomic, readonly) _Bool canModifyRequestToJoin; // @synthesize canModifyRequestToJoin;
@property(nonatomic, readonly) _Bool hasBlockedUser; // @synthesize hasBlockedUser;
@property(nonatomic, readonly) long long readState; // @synthesize readState;
@property(nonatomic, readonly) _TtC9Timelines20GroupChatPermissions *permissions; // @synthesize permissions;
@property(nonatomic, readonly) _Bool isMember; // @synthesize isMember;
@property(nonatomic, readonly) _Bool isOwner; // @synthesize isOwner;
@property(nonatomic, readonly) NSString *publicURL;

@end

