//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC10CoreTumblr16PushNotification.h"

@class MISSING_TYPE, NSString, NSURL;

@interface _TtC9Messaging23MessagePushNotification : _TtC10CoreTumblr16PushNotification
{
    MISSING_TYPE *localizedTitle;
    MISSING_TYPE *localizedBody;
    MISSING_TYPE *iconURL;
    MISSING_TYPE *conversationID;
    MISSING_TYPE *conversationUnreadCount;
    MISSING_TYPE *recipientBlogName;
    MISSING_TYPE *recipientBlogUUID;
    MISSING_TYPE *senderIsAdult;
    MISSING_TYPE *senderUUID;
}

- (void).cxx_destruct;
- (id)initWithNotificationDictionary:(id)arg1;
@property(nonatomic, readonly) NSString *senderUUID;
@property(nonatomic, readonly) _Bool senderIsAdult; // @synthesize senderIsAdult;
@property(nonatomic, readonly) NSString *recipientBlogUUID;
@property(nonatomic, readonly) NSString *recipientBlogName;
@property(nonatomic, readonly) unsigned long long conversationUnreadCount; // @synthesize conversationUnreadCount;
@property(nonatomic, readonly) NSString *conversationID;
@property(nonatomic, readonly) NSURL *iconURL;
@property(nonatomic, readonly) NSString *localizedBody;
@property(nonatomic, readonly) NSString *localizedTitle;

@end

