//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC12KanvasCamera7Sharpie : _TtCs12_SwiftObject
{
    MISSING_TYPE *roundedTexture;
    MISSING_TYPE *minimumStroke;
    MISSING_TYPE *maximumStroke;
    MISSING_TYPE *textureType;
}

@end

