//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr31ClientSideAdLoaderEventProvider : NSObject
{
    MISSING_TYPE *screenID;
    MISSING_TYPE *preferences;
    MISSING_TYPE *clientSideAdTypeName;
    MISSING_TYPE *analyticsBuffer;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithPreferences:(id)arg1 analyticsBuffer:(id)arg2 clientSideAdType:(int)arg3;

@end

