//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC8TumblrUI25ExpandingToolbarTextField : UIView
{
    MISSING_TYPE *$__lazy_storage_$_textField;
    MISSING_TYPE *sendButton;
    MISSING_TYPE *leftAccessoryView;
    MISSING_TYPE *leftAccessoryConstraints;
    MISSING_TYPE *topSeparator;
    MISSING_TYPE *bottomSeparator;
    MISSING_TYPE *$__lazy_storage_$_stackView;
    MISSING_TYPE *$__lazy_storage_$_stackViewLeadingConstraint;
    MISSING_TYPE *backgroundView;
    MISSING_TYPE *includeStackViewPadding;
    MISSING_TYPE *delegate;
    MISSING_TYPE *maxTextFieldHeight;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)updateColors:(id)arg1;
- (void)updateTheming:(id)arg1;
- (void)sendMessage;
@property(nonatomic, readonly) _Bool isFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)resignFirstResponder;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (id)initWithCoder:(id)arg1;

@end

