//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP6Tumblr28BlogPageNotificationObserver_-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6Tumblr35DefaultBlogPageNotificationObserver : NSObject <_TtP6Tumblr28BlogPageNotificationObserver_>
{
    MISSING_TYPE *currentBlogDoesNeedUpdateHandler;
}

- (void).cxx_destruct;
- (id)init;
- (void)didReceiveCurrentBlogNeedsUpdateNotification:(id)arg1;
- (void)startObserving;
@property(nonatomic, copy) CDUnknownBlockType currentBlogDoesNeedUpdateHandler;

@end

