//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, UIColor;

@interface _TtC13PostAudioView22PostContentCornersView : UIView
{
    MISSING_TYPE *_cornersHidden;
    MISSING_TYPE *_cornerBackgroundColor;
    MISSING_TYPE *_cornerFillColor;
    MISSING_TYPE *topLeftCorner;
    MISSING_TYPE *topRightCorner;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) UIColor *cornerFillColor;
@property(nonatomic) _Bool cornersHidden;

@end

