//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9PostForms24PostFormViewCellProvider : _TtCs12_SwiftObject
{
    MISSING_TYPE *reblogTrailProvider;
    MISSING_TYPE *imageViewProvider;
    MISSING_TYPE *audioViewProvider;
    MISSING_TYPE *videoViewProvider;
    MISSING_TYPE *loadingIndicatorGenerator;
    MISSING_TYPE *tagsDelegate;
    MISSING_TYPE *postToolbar;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *altTextEnabled;
    MISSING_TYPE *mediaEditEnabled;
    MISSING_TYPE *gifEditEnabled;
}

@end

