//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr32BlocksPostUnsupportedContentView : UIView
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *$__lazy_storage_$_unsupportedContentView;
}

- (void).cxx_destruct;
- (void)actionButtonTapped;
- (void)updateConstraints;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

