//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr28BlogNameChangeViewController : UIViewController
{
    MISSING_TYPE *blogName;
    MISSING_TYPE *session;
    MISSING_TYPE *coreDataController;
    MISSING_TYPE *dismissHandler;
    MISSING_TYPE *preferences;
    MISSING_TYPE *blogNameChangeView;
    MISSING_TYPE *keyboardNotificationObserver;
    MISSING_TYPE *constraints;
    MISSING_TYPE *analyticsBuffer;
    MISSING_TYPE *userInfoDataService;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *blogNameChanger;
    MISSING_TYPE *blogNameChangerDelegate;
    MISSING_TYPE *rightBarButtonItem;
    MISSING_TYPE *eventProvider;
    MISSING_TYPE *blogNameChangeViewTopAnchor;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)stylingForNavigationBar;
- (void)updateColors:(id)arg1;
- (void)cancel;
- (void)saveAction;
- (id)initWithCoder:(id)arg1;

@end

