//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP11ImageLoader30ImageRequestAuthHeaderProvider_-Protocol.h"

@interface _TtC6Tumblr31ImageRequestOAuthHeaderProvider : NSObject <_TtP11ImageLoader30ImageRequestAuthHeaderProvider_>
{
}

- (id)init;
- (id)makeOAuthHeaderFor:(id)arg1;

@end

