//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC10GIFCreator21GIFEditViewController : UIViewController
{
    MISSING_TYPE *bannerQueueInfo;
    MISSING_TYPE *currentBannerTimer;
    MISSING_TYPE *bannerQueueLimit;
    MISSING_TYPE *gifMedia;
    MISSING_TYPE *gifSizeEstimator;
    MISSING_TYPE *delegate;
    MISSING_TYPE *networkSession;
    MISSING_TYPE *operationQueue;
    MISSING_TYPE *loadingController;
    MISSING_TYPE *$__lazy_storage_$_cropViewController;
    MISSING_TYPE *placeholderImage;
    MISSING_TYPE *editToolsView;
    MISSING_TYPE *loadingOverlay;
    MISSING_TYPE *hudLabel;
    MISSING_TYPE *loadingControl;
    MISSING_TYPE *audioPlayer;
    MISSING_TYPE *libraryCachePaths;
    MISSING_TYPE *lastTrimHandleImageIndex;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)cancelAction:(id)arg1;
- (void)nextAction:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

