//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC9PostForms13ApoDrawerView : UIView
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *appColorScheme;
    MISSING_TYPE *contentHeight;
    MISSING_TYPE *$__lazy_storage_$_contentViewHeight;
    MISSING_TYPE *$__lazy_storage_$_headerViewTop;
    MISSING_TYPE *$__lazy_storage_$_headerViewBottom;
    MISSING_TYPE *$__lazy_storage_$_extraBottomSpaceBottom;
    MISSING_TYPE *$__lazy_storage_$_extraBottomSpaceTop;
    MISSING_TYPE *$__lazy_storage_$_scrollViewTop;
    MISSING_TYPE *$__lazy_storage_$_scrollViewBottom;
    MISSING_TYPE *$__lazy_storage_$_scrollViewHeight;
    MISSING_TYPE *$__lazy_storage_$_overlay;
    MISSING_TYPE *$__lazy_storage_$_header;
    MISSING_TYPE *$__lazy_storage_$_scrollView;
    MISSING_TYPE *$__lazy_storage_$_contentView;
    MISSING_TYPE *$__lazy_storage_$_extraBottomSpace;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didTapOverlay;
- (void)didPanWithRecognizer:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

