//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr33TagFilteringSectionHeaderProvider : _TtCs12_SwiftObject
{
    MISSING_TYPE *filterContainer;
    MISSING_TYPE *headerViewDelegate;
    MISSING_TYPE *appColorScheme;
}

- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;

@end

