//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr23TimelineObjectTitleView : UIView
{
    MISSING_TYPE *$__lazy_storage_$_titleTextLabel;
    MISSING_TYPE *$__lazy_storage_$_auxButton;
    MISSING_TYPE *$__lazy_storage_$_auxButtonWidthConstraint;
    MISSING_TYPE *$__lazy_storage_$_titleAuxButtonSpacingConstraint;
    MISSING_TYPE *delegate;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateColors:(id)arg1;
- (void)updateTheming:(id)arg1;
- (void)auxButtonTapped;
- (id)initWithCoder:(id)arg1;

@end

