//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE;

@interface _TtC6Tumblr29PostNotesTypeaheadMentionCell : UICollectionViewCell
{
    MISSING_TYPE *avatarView;
    MISSING_TYPE *nameLabel;
    MISSING_TYPE *previousBlogName;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)updateColors:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

