//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP11TumblrTheme14AppColorSource_;

@protocol _TtP11TumblrTheme20ColorSourceRequiring_
- (void)updateWithAppColorSource:(id <_TtP11TumblrTheme14AppColorSource_>)arg1;
@end

