//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, _TtC6Tumblr21AdBeaconEventProvider;

@protocol _TtP6Tumblr19RuleTrackerDelegate_
- (float)percentVisible;
- (void)fireBeacon:(NSArray *)arg1 eventProvider:(_TtC6Tumblr21AdBeaconEventProvider *)arg2;
@end

