//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSString, TMPost;
@protocol TMRequest;

@protocol _TtP6Tumblr25TMTimelineAndBlogsOptions_
- (id <TMRequest>)requestWithQueryParameters:(NSDictionary *)arg1;
- (NSDictionary *)dictionaryOfParametersWithLatest:(_Bool)arg1 offset:(unsigned long long)arg2 lastPost:(TMPost *)arg3 resultLimit:(unsigned long long)arg4;
@property(nonatomic, readonly) unsigned long long resultsType;
@property(nonatomic, readonly) NSString *query;
@end

