//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtP19NetworkAbstractions8Nextable_-Protocol.h"

@protocol _TtP19NetworkAbstractions11DataService_ <_TtP19NetworkAbstractions8Nextable_>
- (void)cancel;
- (void)updateWithNext:(void (^)(NSError *, id <TMAPIError>))arg1;
- (void)updateWithLatestWithIsUserGenerated:(_Bool)arg1 serviceCompletionHandler:(void (^)(NSError *, id <TMAPIError>))arg2;
@end

