//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class TMTimelineObject, _TtC6Tumblr16YahooVideoPlayer;

@protocol _TtP6Tumblr26TMYahooVideoPlayerDelegate_
- (void)dismissedFullScreenYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
- (void)presentedFullScreenYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
- (void)didLoopYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
- (void)playedOrPausedYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2 played:(_Bool)arg3;
- (void)didEndScrubbingYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
- (void)willBeginScrubbingYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
- (void)mutedOrUnmutedYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2 muted:(_Bool)arg3;
- (void)didAutoStopYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
- (void)didAutoPlayYahooVideo:(_TtC6Tumblr16YahooVideoPlayer *)arg1 timelineObject:(TMTimelineObject *)arg2;
@end

