//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtP11TumblrTheme9TMTheming_-Protocol.h"
#import "_TtP6Tumblr26ReselectableViewController_-Protocol.h"

@class UIView, UIViewController, _TtC11TumblrTheme7TMTheme;
@protocol TMTableViewProviding;

@protocol _TtP6Tumblr8BlogPage_ <_TtP6Tumblr26ReselectableViewController_, _TtP11TumblrTheme9TMTheming_>
- (void)reloadIfNeeded;
- (void)updateToReflectCurrentCustomizationState;
- (void)headerDidTriggerRefresh;
- (void)updateTableHeaderFrame:(struct CGRect)arg1;
- (void)updateTableHeaderView:(UIView *)arg1 theme:(_TtC11TumblrTheme7TMTheme *)arg2;
- (void)pauseVideos;
@property(nonatomic, readonly) _Bool headerHasBeenSet;
@property(nonatomic) _Bool isShared;
@property(nonatomic, readonly) long long type;
@property(nonatomic, readonly) id <TMTableViewProviding> tableViewProvider;
@property(nonatomic, readonly) UIViewController *viewController;
@end

