//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtP9Timelines14TimelineObject_-Protocol.h"

@class NSString;

@protocol _TtP9Timelines21BlogRowTimelineObject_ <_TtP9Timelines14TimelineObject_>
@property(nonatomic, readonly) NSString *blogUUID;
@end

