//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, NSURL, _TtC6Tumblr16YahooVideoPlayer, _TtC6Tumblr28PostVideoPlayerEventProvider;
@protocol TMYahooVideoAttributesModel;

@protocol _TtP6Tumblr25YahooVideoPlayerProviding_
- (_TtC6Tumblr16YahooVideoPlayer *)createNewPlayerWithUrl:(NSURL *)arg1 thumbnailURLString:(NSString *)arg2;
- (_TtC6Tumblr16YahooVideoPlayer *)createNewPlayerWithYahooVideoAttributes:(id <TMYahooVideoAttributesModel>)arg1 thumbnailURLString:(NSString *)arg2;
@property(nonatomic, readonly) _TtC6Tumblr28PostVideoPlayerEventProvider *eventProvider;
@end

