//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtP14DataDisplayKit23DataDisplayViewDelegate_-Protocol.h"

@protocol UICollectionViewDelegate;

@protocol _TtP14DataDisplayKit33DataDisplayCollectionViewDelegate_ <_TtP14DataDisplayKit23DataDisplayViewDelegate_>
- (id <UICollectionViewDelegate>)delegate;
@end

