//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP6Tumblr19VideoBeaconTracking_
@property(nonatomic, readonly) double duration;
@property(nonatomic, readonly) _Bool playing;
@property(nonatomic, readonly) _Bool muted;
@property(nonatomic, readonly) double secondsElapsed;
@property(nonatomic, readonly) double progress;
@property(nonatomic, readonly) _Bool loading;
@property(nonatomic, readonly) _Bool fullscreen;
@property(nonatomic, readonly) struct CGSize size;
@end

