//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSLayoutConstraint, UIView;

@protocol _TtP8TumblrUI30DropdownAnimationViewProviding_
@property(nonatomic, readonly) UIView *headerView;
@property(nonatomic, readonly) UIView *footerView;
@property(nonatomic, readonly) NSLayoutConstraint *dropdownTopConstraint;
@property(nonatomic, readonly) UIView *dropdownContainerView;
@property(nonatomic, readonly) UIView *dropdownView;
@end

