//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;
@protocol _TtP8TumblrUI20FollowButtonDelegate_;

@protocol _TtP8TumblrUI20FollowButtonProtocol_
@property(nonatomic, copy) NSString *screenIdentifier;
@property(nonatomic) _Bool hidesWhenFollowing;
@property(nonatomic) __weak id <_TtP8TumblrUI20FollowButtonDelegate_> delegate;
- (void)setFollowing:(_Bool)arg1;
@property(nonatomic) _Bool isFollowing;
@property(nonatomic, readonly) long long style;
@end

