//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, TMPostCell;

@protocol _TtP6Tumblr39PostCellNSFWOwnPostAppealBannerDelegate_
- (void)eyeButtonTappedForPostCell:(TMPostCell *)arg1;
- (void)showAppropriateAppealPromptForPostCell:(TMPostCell *)arg1;
- (void)dismissBannerForPostCell:(TMPostCell *)arg1;
- (void)requestReviewForPostCell:(TMPostCell *)arg1;
- (void)showNsfwAppealHelpFromSource:(NSString *)arg1;
@end

