//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP5Utils21ReachabilityObserving_;

@protocol _TtP5Utils22ReachabilityDeterminer_
- (void)removeReachability:(id <_TtP5Utils21ReachabilityObserving_>)arg1;
- (void)addReachability:(id <_TtP5Utils21ReachabilityObserving_>)arg1;
@property(nonatomic, readonly) _Bool reachable;
@property(nonatomic, readonly) _Bool wifiReachable;
@end

