//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP9Timelines8Timeline_;

@protocol _TtP9Timelines27TimelineBatchUpdateListener_
- (void)batchUpdatesDidCompleteOn:(id <_TtP9Timelines8Timeline_>)arg1;
@end

