//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, _TtC8TumblrUI11TMSearchBar;

@protocol _TtP8TumblrUI19TMSearchBarDelegate_
- (void)searchBarTextDidEndEditing:(_TtC8TumblrUI11TMSearchBar *)arg1;
- (void)searchBarWillClear:(_TtC8TumblrUI11TMSearchBar *)arg1;
- (void)searchBarCancelButtonClicked:(_TtC8TumblrUI11TMSearchBar *)arg1;
- (void)searchBarSearchButtonClicked:(_TtC8TumblrUI11TMSearchBar *)arg1;
- (void)searchBar:(_TtC8TumblrUI11TMSearchBar *)arg1 textDidChange:(NSString *)arg2;
- (void)searchBarTextDidBeginEditing:(_TtC8TumblrUI11TMSearchBar *)arg1;
@end

