//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, TMRating;

@protocol _TtP10CoreTumblr23AppInstallationModeling_
@property(nonatomic, readonly) TMRating *rating;
@property(nonatomic, readonly) NSString *appID;
@property(nonatomic, readonly) NSString *openText;
@property(nonatomic, readonly) NSString *installText;
@property(nonatomic, readonly) NSString *iconURL;
@property(nonatomic, readonly) NSString *appName;
@end

