//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC8TumblrUI22BlogSelectorHeaderView;

@protocol _TtP8TumblrUI32BlogSelectionHeaderViewProviding_
@property(nonatomic, readonly) _TtC8TumblrUI22BlogSelectorHeaderView *blogSelectorHeaderView;
@end

