//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtP10GIFCreator13MediaItemType_-Protocol.h"

@class NSArray, NSString, NSURL;

@protocol _TtP10GIFCreator21LoadableMediaItemType_ <_TtP10GIFCreator13MediaItemType_>
@property(nonatomic, readonly) NSString *mediaSource;
@property(nonatomic, readonly) NSString *identifier;
@property(nonatomic, readonly) NSArray *urls;
@property(nonatomic, readonly) NSURL *url;
@property(nonatomic, readonly) long long height;
@property(nonatomic, readonly) long long width;
@property(nonatomic, readonly) double aspectRatio;
- (void)cancelLoad;
@property(nonatomic, readonly) long long state;
- (void)addCompletionHandler:(void (^)(_Bool, NSError *))arg1;
@end

