//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP14DataDisplayKit16EmptyViewManager_
- (void)reloadEmptyView;
- (void)showOrHideIfNeeded:(_Bool)arg1 errorCode:(long long)arg2;
- (void)hideEmptyView:(_Bool)arg1;
- (void)showEmptyView:(_Bool)arg1 errorCode:(long long)arg2;
- (void)layoutEmptyView;
@end

