//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSDictionary;

@protocol _TtP9Timelines30TimelineObjectsJSONTransformer_
- (NSArray *)createTimelineObjectsWith:(NSDictionary *)arg1 extraValues:(NSDictionary *)arg2;
@end

