//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface ActionRule : NSObject
{
    NSArray *_actionValues;
    NSString *_placement;
    NSString *_type;
    long long _start;
    long long _interval;
    long long _minimumDuration;
    long long _probability;
    long long _ratio;
    long long _length;
    long long _duration;
    long long _overlayStart;
    long long _padding;
    long long _repeat;
    long long _timeUpdate;
    long long _clipDuration;
    long long _currentDuration;
    long long _lastShown;
    NSMutableArray *_blockFunctions;
}

- (void).cxx_destruct;
@property(retain) NSMutableArray *blockFunctions; // @synthesize blockFunctions=_blockFunctions;
@property long long lastShown; // @synthesize lastShown=_lastShown;
@property long long currentDuration; // @synthesize currentDuration=_currentDuration;
@property long long clipDuration; // @synthesize clipDuration=_clipDuration;
@property long long timeUpdate; // @synthesize timeUpdate=_timeUpdate;
@property long long repeat; // @synthesize repeat=_repeat;
@property long long padding; // @synthesize padding=_padding;
@property long long overlayStart; // @synthesize overlayStart=_overlayStart;
@property long long duration; // @synthesize duration=_duration;
@property long long length; // @synthesize length=_length;
@property long long ratio; // @synthesize ratio=_ratio;
@property long long probability; // @synthesize probability=_probability;
@property long long minimumDuration; // @synthesize minimumDuration=_minimumDuration;
@property long long interval; // @synthesize interval=_interval;
@property long long start; // @synthesize start=_start;
@property(retain) NSString *type; // @synthesize type=_type;
@property(retain) NSString *placement; // @synthesize placement=_placement;
@property(retain) NSArray *actionValues; // @synthesize actionValues=_actionValues;
- (_Bool)evaluateFrequency;
- (_Bool)evaluateLength;
- (_Bool)evaluateMinimumDuration;
- (_Bool)evaluateOverlay;
- (_Bool)evaluateStart;
- (_Bool)evaluateDefault;
- (_Bool)evaluate:(id)arg1 timeUpdate:(id)arg2;
- (void)addRuleBlock:(CDUnknownBlockType)arg1;

@end

