//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface Allocation : NSObject
{
    _Bool _disableFallback;
    NSDictionary *_settingsMap;
    NSString *_algoId;
    NSString *_propertyId;
    NSDictionary *_communicatorIdNameMap;
    NSArray *_priorityList;
    NSDictionary *_communicatorAllocation;
}

- (void).cxx_destruct;
@property(retain) NSDictionary *communicatorAllocation; // @synthesize communicatorAllocation=_communicatorAllocation;
@property(retain) NSArray *priorityList; // @synthesize priorityList=_priorityList;
@property(retain) NSDictionary *communicatorIdNameMap; // @synthesize communicatorIdNameMap=_communicatorIdNameMap;
@property(retain) NSString *propertyId; // @synthesize propertyId=_propertyId;
@property _Bool disableFallback; // @synthesize disableFallback=_disableFallback;
@property(retain) NSString *algoId; // @synthesize algoId=_algoId;
@property(retain) NSDictionary *settingsMap; // @synthesize settingsMap=_settingsMap;
- (id)pickPossibleCommunicators:(id)arg1;
- (_Bool)canService:(id)arg1 desired:(id)arg2;
- (id)pickFallbackCommunicator:(id)arg1;
- (id)pickCommunicator:(id)arg1;

@end

