//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, TMBlog;

@protocol AvatarImageViewUpdate
- (void)setAvatarShape:(long long)arg1 defaultCorner:(double)arg2;
- (void)setBlogName:(NSString *)arg1 privateBlog:(_Bool)arg2 force:(_Bool)arg3 isNSFW:(_Bool)arg4;
- (void)setBlogName:(NSString *)arg1 privateBlog:(_Bool)arg2;
- (void)setBlog:(TMBlog *)arg1;
@end

