//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVAsynchronousVideoCompositionRequest, AVVideoCompositionRenderContext, AVVideoCompositionRenderHint, NSDictionary;

@protocol AVVideoCompositing <NSObject>
- (void)startVideoCompositionRequest:(AVAsynchronousVideoCompositionRequest *)arg1;
- (void)renderContextChanged:(AVVideoCompositionRenderContext *)arg1;
@property(nonatomic, readonly) NSDictionary *requiredPixelBufferAttributesForRenderContext;
@property(nonatomic, readonly) NSDictionary *sourcePixelBufferAttributes;

@optional
- (void)prerollForRenderingUsingHint:(AVVideoCompositionRenderHint *)arg1;
- (void)anticipateRenderingUsingHint:(AVVideoCompositionRenderHint *)arg1;
@property(nonatomic, readonly) _Bool supportsWideColorSourceFrames;
- (void)cancelAllPendingVideoCompositionRequests;
@end

