//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AdResponse, Communicator, NSString;

@protocol CommunicatorDelegate <NSObject>
- (void)adFailure:(AdResponse *)arg1 key:(NSString *)arg2 communicator:(Communicator *)arg3 error:(NSString *)arg4;
- (void)adReady:(AdResponse *)arg1 key:(NSString *)arg2 communicator:(Communicator *)arg3;
@end

