//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DFPCustomRenderedAd, DFPInterstitial;

@protocol DFPCustomRenderedInterstitialDelegate <NSObject>
- (void)interstitial:(DFPInterstitial *)arg1 didReceiveCustomRenderedAd:(DFPCustomRenderedAd *)arg2;
@end

