//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface EmbeddedLandingUrls : NSObject
{
    NSArray *_urls;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *urls; // @synthesize urls=_urls;
- (id)init;

@end

