//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBMediaView.h"

@interface FBAdIconView : FBMediaView
{
}

@property(readonly, nonatomic) unsigned long long nativeAdViewTag;
- (void)setNativeAdViewTag:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

