//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAdReportingCoordinator, NSString;

@protocol FBAdReportingCoordinatorDelegate <NSObject>

@optional
- (void)adReportingCoordinatorDidCloseWhyAmISeeingThis:(FBAdReportingCoordinator *)arg1;
- (void)adReportingCoordinatorDidCancelFlow:(FBAdReportingCoordinator *)arg1;
- (void)adReportingCoordinatorDidCompleteFlow:(FBAdReportingCoordinator *)arg1 reason:(NSString *)arg2 flowType:(long long)arg3;
@end

