//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FBAdProviderResponseParser : NSObject
{
}

- (void)parseResponseFromJSONDict:(id)arg1 successHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;
- (void)parseResponseFromData:(id)arg1 successHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;
- (id)parsePlacementObjectFromJsonData:(id)arg1;
- (id)parsePlacementDefinitionFromData:(id)arg1;

@end

