//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface FBAdToolbarConfiguration : NSObject
{
    _Bool _hidesHintLabel;
    UIColor *_tintColor;
    UIColor *_backgroundColor;
    unsigned long long _size;
}

@property(nonatomic) _Bool hidesHintLabel; // @synthesize hidesHintLabel=_hidesHintLabel;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

