//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAdCommandProcessor, NSDictionary, UIViewController;

@protocol FBAdCommandProcessorDelegate <NSObject>
@property(readonly, nonatomic) UIViewController *viewControllerForPresentingModalView;
- (NSDictionary *)commandProcessorTouchInformation:(FBAdCommandProcessor *)arg1;
- (void)viewControllerDismissed:(FBAdCommandProcessor *)arg1;
- (void)willPresentViewController:(FBAdCommandProcessor *)arg1;
@end

