//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, NSDate, NSString, NSURL;

@protocol FBAdPersistentCache
- (NSURL *)storageURLForCache;
- (void)wipeCache;
- (NSURL *)storageURLForAssetWithKey:(NSString *)arg1 ofType:(long long)arg2;
- (_Bool)storeAssetWithData:(NSData *)arg1 forKey:(NSString *)arg2 ofType:(long long)arg3;
- (void)assetForKey:(NSString *)arg1 remoteURL:(NSURL *)arg2 ofType:(long long)arg3 context:(NSString *)arg4 resultHandler:(void (^)(id, NSURL *))arg5;
- (void)assetForKey:(NSString *)arg1 ofType:(long long)arg2 resultHandler:(void (^)(id, NSURL *))arg3;
- (_Bool)storeAssetInMemory:(id)arg1 forKey:(NSString *)arg2 expiration:(NSDate *)arg3;
- (id)assetInMemoryForKey:(NSString *)arg1;
@end

