//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class FBAdColorInfo, FBAdImage, UIImageView, UIView;

@interface FBAdCTAButton : UIButton
{
    UIView *_backgroundView;
    UIImageView *_iconImageView;
    FBAdImage *_icon;
    FBAdColorInfo *_colorInfo;
}

@property(retain, nonatomic) FBAdColorInfo *colorInfo; // @synthesize colorInfo=_colorInfo;
@property(retain, nonatomic) FBAdImage *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setupBackgroundLayerWithColor:(id)arg1 cornerRadius:(double)arg2 shadowEnabled:(_Bool)arg3 animationDuration:(double)arg4;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setCtaButtonStyle:(unsigned long long)arg1 animationDuration:(double)arg2;
- (void)setCtaButtonStyle:(unsigned long long)arg1;
- (void)setupWithStyle:(unsigned long long)arg1;
- (id)initWithStyle:(unsigned long long)arg1 icon:(id)arg2 colorInfo:(id)arg3;

@end

