//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface FBAdEventConfiguration : NSObject
{
    _Bool _shouldPurgeOn413Response;
    _Bool _shouldCollectLocalCountersSignal;
    double _unifiedLoggingImmediateDelay;
    double _eventsDispatchInterval;
    long long _unifiedLoggingEventLimit;
    NSURL *_baseEventURL;
}

@property(nonatomic) _Bool shouldCollectLocalCountersSignal; // @synthesize shouldCollectLocalCountersSignal=_shouldCollectLocalCountersSignal;
@property(nonatomic) _Bool shouldPurgeOn413Response; // @synthesize shouldPurgeOn413Response=_shouldPurgeOn413Response;
@property(retain, nonatomic) NSURL *baseEventURL; // @synthesize baseEventURL=_baseEventURL;
@property(nonatomic) long long unifiedLoggingEventLimit; // @synthesize unifiedLoggingEventLimit=_unifiedLoggingEventLimit;
@property(nonatomic) double eventsDispatchInterval; // @synthesize eventsDispatchInterval=_eventsDispatchInterval;
@property(nonatomic) double unifiedLoggingImmediateDelay; // @synthesize unifiedLoggingImmediateDelay=_unifiedLoggingImmediateDelay;
- (void).cxx_destruct;
- (id)initWithBaseEventURL:(id)arg1;

@end

