//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBAdSafariViewControllerDelegate-Protocol.h"

@class NSString, SKStoreProductViewController;
@protocol FBAdCommandProcessorDelegate;

@interface FBAdCommandProcessor : NSObject <FBAdSafariViewControllerDelegate>
{
    id <FBAdCommandProcessorDelegate> _delegate;
    NSString *_inlineClientToken;
    CDUnknownBlockType _completionHandler;
    SKStoreProductViewController *_inAppAppStoreViewController;
}

+ (id)getLinkFromCommandURL:(id)arg1;
+ (_Bool)isValidBrowseCommand:(id)arg1;
+ (_Bool)isValidOpenAppStoreCommand:(id)arg1;
+ (void)initialize;
@property(retain, nonatomic) SKStoreProductViewController *inAppAppStoreViewController; // @synthesize inAppAppStoreViewController=_inAppAppStoreViewController;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(copy, nonatomic) NSString *inlineClientToken; // @synthesize inlineClientToken=_inlineClientToken;
@property(nonatomic) __weak id <FBAdCommandProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewControllerDismissed:(id)arg1;
- (void)viewControllerCompleted:(id)arg1;
- (id)logger;
- (_Bool)isValidViewController:(id)arg1;
- (void)doneCommandProcessing;
- (void)callCompletionHandlerForCommand:(long long)arg1 withAdAction:(long long)arg2;
- (_Bool)launchURLOutOfApp:(id)arg1 withAdAction:(long long)arg2;
- (_Bool)openLinkInApp:(id)arg1 withAdAction:(long long)arg2;
- (id)openInAppAppStore:(id)arg1;
- (_Bool)shouldShowInAppAppStoreSheet;
- (id)openAppStore:(id)arg1;
- (_Bool)launchAppForEngagement:(id)arg1;
- (_Bool)openURL:(id)arg1 nameValuePairs:(id)arg2 mutableExtraData:(id)arg3 skipAppStore:(_Bool)arg4;
- (_Bool)processCommand:(id)arg1 withExtraData:(id)arg2 inlineClientToken:(id)arg3 skipAppStore:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (_Bool)processCommand:(id)arg1 inlineClientToken:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 skipAppStore:(_Bool)arg4;
- (_Bool)processCommand:(id)arg1 inlineClientToken:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)processCommand:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

