//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBAdBackgroundStateManaging-Protocol.h"

@class NSString;

@interface FBAdBackgroundStateManager : NSObject <FBAdBackgroundStateManaging>
{
    unsigned long long _extensionState;
}

@property unsigned long long extensionState; // @synthesize extensionState=_extensionState;
- (long long)applicationState;
- (_Bool)isApplicationBecomingActive;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

