//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FBAdExperienceConfig : NSObject
{
    NSString *_adExperienceType;
}

@property(retain, nonatomic) NSString *adExperienceType; // @synthesize adExperienceType=_adExperienceType;
- (void).cxx_destruct;
- (id)stringRepresentation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAdExperienceType:(id)arg1;

@end

