//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAdSyncBundlePayload, NSString;
@protocol FBAdSyncBundleDelegate;

@protocol FBAdSyncBundle <NSObject>
@property(readonly, copy) FBAdSyncBundlePayload *payload;
@property(readonly, getter=isReady) _Bool ready;
@property(readonly, copy, nonatomic) NSString *bundleId;
@property(readonly, nonatomic) long long bundleType;
- (void)removeDelegate:(id <FBAdSyncBundleDelegate>)arg1;
- (void)addDelegate:(id <FBAdSyncBundleDelegate>)arg1;
@end

