//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIViewController;

@protocol FBAdSafariViewControllerDelegate <NSObject>

@optional
- (void)viewControllerDismissed:(UIViewController *)arg1;
- (void)viewControllerCompleted:(UIViewController *)arg1;
- (void)willPresentViewController:(UIViewController *)arg1;
@end

