//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FBAdAssetListLoader, NSArray;

@interface FBAdAssetSetData : NSObject
{
    NSArray *_mandatoryAssets;
    NSArray *_optionalAssets;
    FBAdAssetListLoader *_mandatoryAssetsLoader;
    FBAdAssetListLoader *_optionalAssetsLoader;
}

+ (id)fileAssetsFromData:(id)arg1;
+ (id)assetsFromData:(id)arg1 assetType:(long long)arg2;
@property(retain, nonatomic) FBAdAssetListLoader *optionalAssetsLoader; // @synthesize optionalAssetsLoader=_optionalAssetsLoader;
@property(retain, nonatomic) FBAdAssetListLoader *mandatoryAssetsLoader; // @synthesize mandatoryAssetsLoader=_mandatoryAssetsLoader;
@property(copy, nonatomic) NSArray *optionalAssets; // @synthesize optionalAssets=_optionalAssets;
@property(copy, nonatomic) NSArray *mandatoryAssets; // @synthesize mandatoryAssets=_mandatoryAssets;
- (void).cxx_destruct;
- (void)callHandler:(CDUnknownBlockType)arg1;
- (_Bool)loadOptionalAssetsWithSuccessHandler:(CDUnknownBlockType)arg1 failHandler:(CDUnknownBlockType)arg2;
- (_Bool)loadMandatoryAssetsWithSuccessHandler:(CDUnknownBlockType)arg1 failHandler:(CDUnknownBlockType)arg2;
- (id)initWithData:(id)arg1;
- (id)initWithMandatoryAssets:(id)arg1 optionalAssets:(id)arg2;
- (id)init;

@end

