//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBNativeAdBase, NSError;

@protocol FBNativeAdBaseDelegate <NSObject>
- (void)nativeAdBaseDidFinishHandling:(FBNativeAdBase *)arg1;
- (void)nativeAdBaseDidClick:(FBNativeAdBase *)arg1;
- (void)nativeAdBase:(FBNativeAdBase *)arg1 didFailWithError:(NSError *)arg2;
- (void)nativeAdBaseWillLogImpression:(FBNativeAdBase *)arg1;
- (void)nativeAdBaseDidLoad:(FBNativeAdBase *)arg1;
- (void)nativeAdBaseDidDownloadMedia:(FBNativeAdBase *)arg1;
@end

