//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSNumber, NSNumberFormatter, NSString;
@protocol FBSDKVideoUploaderDelegate;

@interface FBSDKVideoUploader : NSObject
{
    NSNumber *_videoID;
    NSNumber *_uploadSessionID;
    NSNumberFormatter *_numberFormatter;
    NSString *_graphPath;
    NSString *_videoName;
    unsigned long long _videoSize;
    NSDictionary *_parameters;
    NSString *_graphNode;
    id <FBSDKVideoUploaderDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <FBSDKVideoUploaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *graphNode; // @synthesize graphNode=_graphNode;
@property(copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
- (id)_graphPathWithSuffix:(id)arg1;
- (id)numberFormatter;
- (id)_extractOffsetsFromResultDictionary:(id)arg1;
- (void)_postFinishRequest;
- (void)_startTransferRequestWithOffsetDictionary:(id)arg1;
- (void)_postStartRequest;
- (void)start;
- (id)initWithVideoName:(id)arg1 videoSize:(unsigned long long)arg2 parameters:(id)arg3 delegate:(id)arg4;

@end

