//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;

@interface FBSDKIcon : NSObject
{
    UIColor *_color;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIColor *color; // @synthesize color=_color;
- (struct CGPath *)pathWithSize:(struct CGSize)arg1;
- (id)imageWithSize:(struct CGSize)arg1;
- (id)init;
- (id)initWithColor:(id)arg1;

@end

