//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBSDKMonitorEntry-Protocol.h"

@class NSDate, NSString;

@interface FBSDKPerformanceMonitorEntry : NSObject <FBSDKMonitorEntry>
{
    NSString *_name;
    NSDate *_startTime;
    NSDate *_endTime;
}

+ (id)entryWithName:(id)arg1 startTime:(id)arg2 endTime:(id)arg3;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)name;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

