//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSDKLikeDialog, NSDictionary, NSError;

@protocol FBSDKLikeDialogDelegate <NSObject>
- (void)likeDialog:(FBSDKLikeDialog *)arg1 didFailWithError:(NSError *)arg2;
- (void)likeDialog:(FBSDKLikeDialog *)arg1 didCompleteWithResults:(NSDictionary *)arg2;
@end

