//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FlurryStreamEntityBase.h"

@class NSDate;

@interface FlurrySessionInitInfo : FlurryStreamEntityBase
{
    int _frameType;
    NSDate *_startTime;
}

+ (id)streamEntityFromJSONData:(id)arg1;
+ (id)sessionInitInfo;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
- (void)setFrameType:(int)arg1;
- (int)frameType;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)init;

@end

