//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface FlurryCacheRetrievalPolicy : NSObject
{
    _Bool _removeFromCache;
    CDUnknownBlockType _adUnitFilter;
    long long _timeout;
}

+ (id)defaultPolicy;
@property(nonatomic) _Bool removeFromCache; // @synthesize removeFromCache=_removeFromCache;
@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;
@property(copy, nonatomic) CDUnknownBlockType adUnitFilter; // @synthesize adUnitFilter=_adUnitFilter;
- (void).cxx_destruct;

@end

