//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface FlurryLoadOperationResult : NSObject
{
    double queuedTime;
    double loadTime;
    NSData *data;
    NSString *assetName;
    NSString *assetPath;
}

@property(retain, nonatomic) NSString *assetPath; // @synthesize assetPath;
@property(retain, nonatomic) NSString *assetName; // @synthesize assetName;
@property(retain, nonatomic) NSData *data; // @synthesize data;
@property(nonatomic) double loadTime; // @synthesize loadTime;
@property(nonatomic) double queuedTime; // @synthesize queuedTime;
- (void).cxx_destruct;
- (id)init;

@end

