//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IFlurryManagedUIAdLogger;

@interface FlurryAdLogger : NSObject
{
    id <IFlurryManagedUIAdLogger> _snoopyLogger;
    id <IFlurryManagedUIAdLogger> _flurryLogger;
    NSString *_apiKey;
    NSString *_sdkVersion;
}

+ (void)createWithApiKey:(id)arg1 andSdkVersion:(id)arg2 andSnoopyLogger:(id)arg3 andFlurryLogger:(id)arg4;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(retain, nonatomic) NSString *apiKey; // @synthesize apiKey=_apiKey;
@property(retain, nonatomic) id <IFlurryManagedUIAdLogger> flurryLogger; // @synthesize flurryLogger=_flurryLogger;
@property(retain, nonatomic) id <IFlurryManagedUIAdLogger> snoopyLogger; // @synthesize snoopyLogger=_snoopyLogger;
- (void).cxx_destruct;
- (id)constructParameters:(int)arg1 value:(id)arg2 ad:(id)arg3 params:(id)arg4;
- (_Bool)isFlurryEvent:(int)arg1;
- (_Bool)isFromUserInteraction:(int)arg1;
- (void)logErrorEvent:(int)arg1 value:(id)arg2 ad:(id)arg3 params:(id)arg4;
- (void)logAdActionEvent:(int)arg1 value:(id)arg2 ad:(id)arg3 params:(id)arg4;

@end

