//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FlurryCachedAsset;

@protocol FlurryPreCachingDelegate <NSObject>
- (void)assetPreCachingCancelled:(FlurryCachedAsset *)arg1;
- (void)assetPreCachingFailed:(FlurryCachedAsset *)arg1;
- (void)assetPreCachingDone:(FlurryCachedAsset *)arg1;
@end

