//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class FlurryStoreProductViewController, NSNumber, NSString, NSTimer;

@interface FlurrySKAppstoreController : UIViewController <SKStoreProductViewControllerDelegate>
{
    FlurryStoreProductViewController *_skController;
    NSTimer *_loadingTimer;
    NSNumber *_preLoadedAppID;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSNumber *preLoadedAppID; // @synthesize preLoadedAppID=_preLoadedAppID;
@property(retain, nonatomic) NSTimer *loadingTimer; // @synthesize loadingTimer=_loadingTimer;
@property(retain, nonatomic) FlurryStoreProductViewController *skController; // @synthesize skController=_skController;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)loadingProductTimedout;
- (void)preloadSKAppStoreWithAppID:(id)arg1;
- (void)presentInAppAppStoreOnController:(id)arg1;
- (void)openSKAppstore:(id)arg1 onViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)openSKAppstore:(id)arg1 onViewController:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

