//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface FlurryPreCachingDelegatesMapManager : NSObject
{
    NSMutableDictionary *_preCachingDelegatesMap;
}

+ (id)sharedQueue;
@property(retain, nonatomic) NSMutableDictionary *preCachingDelegatesMap; // @synthesize preCachingDelegatesMap=_preCachingDelegatesMap;
- (void).cxx_destruct;
- (void)processWriteBlockWithBlock:(CDUnknownBlockType)arg1;
- (void)processReadBlockWithBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

