//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSDictionary, NSError, NSString, NSURL;
@protocol FlurryContentLoadOperationDelegate;

@interface FlurryLoadOperation : NSOperation
{
    _Bool _isFinished;
    _Bool _isExecuting;
    _Bool isFromCache_;
    _Bool executing;
    _Bool finished;
    id <FlurryContentLoadOperationDelegate> delegate;
    NSString *_assetName;
    NSURL *assetUrl_;
    double inceptionTime_;
    double startTime_;
    NSError *operationError_;
    NSDictionary *tags_;
    NSString *savePath_;
    NSString *relativeSavePath_;
    double expiryTime;
    double _endTime;
}

@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double expiryTime; // @synthesize expiryTime;
@property(retain, nonatomic) NSString *relativeSavePath; // @synthesize relativeSavePath=relativeSavePath_;
@property(retain, nonatomic) NSString *savePath; // @synthesize savePath=savePath_;
@property(nonatomic) _Bool isFromCache; // @synthesize isFromCache=isFromCache_;
@property(retain, nonatomic) NSDictionary *tags; // @synthesize tags=tags_;
@property(retain, nonatomic) NSError *operationError; // @synthesize operationError=operationError_;
@property(nonatomic) double startTime; // @synthesize startTime=startTime_;
@property(nonatomic) double inceptionTime; // @synthesize inceptionTime=inceptionTime_;
@property(retain, nonatomic) NSURL *assetUrl; // @synthesize assetUrl=assetUrl_;
@property(retain, nonatomic) NSString *resourceId; // @synthesize resourceId=_assetName;
@property(nonatomic) __weak id <FlurryContentLoadOperationDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)finishOperation;
@property(nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing;
- (void)cancel;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished;
- (_Bool)isConcurrent;
- (void)start;
- (void)dealloc;
- (id)initWithAssetName:(id)arg1 withUrlString:(id)arg2 withExpiryTime:(double)arg3 withTags:(id)arg4 delegate:(id)arg5 withSavePath:(id)arg6 withRelativePath:(id)arg7;

@end

