//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FlurryAdJSONManifest.h"

@class NSString;

@interface FlurryAdViewabilityDefManifest : FlurryAdJSONManifest
{
}

@property(readonly, copy, nonatomic) NSString *adFormat;
@property(readonly, copy, nonatomic) NSString *audioFlag;
@property(readonly, copy, nonatomic) NSString *consecutiveFlag;
@property(readonly, copy, nonatomic) NSString *viewabilityPercentVisible;
@property(readonly, copy, nonatomic) NSString *viewabilityDurationInSecs;
@property(readonly, copy, nonatomic) NSString *viewType;

@end

