//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol IFlurryAdRequestBuilder;

@interface FlurryAdNativeInteractorRequestParams : NSObject
{
    id <IFlurryAdRequestBuilder> _adRequestBuilder;
    NSString *_adSpace;
}

@property(copy, nonatomic) NSString *adSpace; // @synthesize adSpace=_adSpace;
@property(retain, nonatomic) id <IFlurryAdRequestBuilder> adRequestBuilder; // @synthesize adRequestBuilder=_adRequestBuilder;
- (void).cxx_destruct;

@end

