//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDate, NSString;

@interface FlurryAdDataSenderBlockInfo : NSObject <NSCoding>
{
    NSString *_groupIdentifier;
    NSString *_identifier;
    unsigned long long _dataSize;
    NSDate *_creationDate;
}

@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(nonatomic) unsigned long long dataSize; // @synthesize dataSize=_dataSize;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) NSString *groupIdentifier; // @synthesize groupIdentifier=_groupIdentifier;
- (void).cxx_destruct;
- (_Bool)setData:(id)arg1;
- (id)data;
- (_Bool)deletePersistentData;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (id)initWithData:(id)arg1;

@end

