//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FlurryNativeAsset, NSString;

@interface FlurryAdNativeAsset : NSObject
{
    FlurryNativeAsset *_nativeAsset;
    int type;
    int width;
    int height;
    NSString *name;
    NSString *value;
}

+ (id)nativeAssetTypeEnumToString:(int)arg1;
+ (int)nativeAssetTypeStringToEnum:(id)arg1;
+ (id)nativeAssetTypeArrayInstance;
@property(nonatomic) int height; // @synthesize height;
@property(nonatomic) int width; // @synthesize width;
@property(retain, nonatomic) NSString *value; // @synthesize value;
@property(nonatomic) int type; // @synthesize type;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;
- (id)description;

@end

