//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FlurryVideoViewabilityState;
@protocol OS_dispatch_queue;

@interface FlurryViewabilityRule : NSObject
{
    _Bool _consecutiveFlag;
    _Bool _audioFlag;
    int _viewType;
    float _viewabilityDurationInSecs;
    float _viewabilityPercentVisible;
    int _adFormat;
    FlurryVideoViewabilityState *_currentState;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)defaultVideoViewRuleWithDuration:(float)arg1 andPercentage:(float)arg2;
+ (id)defaultImpressionRuleWithDuration:(float)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) int adFormat; // @synthesize adFormat=_adFormat;
@property(retain, nonatomic) FlurryVideoViewabilityState *currentState; // @synthesize currentState=_currentState;
@property(nonatomic) _Bool audioFlag; // @synthesize audioFlag=_audioFlag;
@property(nonatomic) _Bool consecutiveFlag; // @synthesize consecutiveFlag=_consecutiveFlag;
@property(nonatomic) float viewabilityPercentVisible; // @synthesize viewabilityPercentVisible=_viewabilityPercentVisible;
@property(nonatomic) float viewabilityDurationInSecs; // @synthesize viewabilityDurationInSecs=_viewabilityDurationInSecs;
@property(nonatomic) int viewType; // @synthesize viewType=_viewType;
- (void).cxx_destruct;
- (_Bool)shouldFire:(id)arg1 currentTime:(float)arg2;
- (id)description;
- (void)resetCurrentViewabilityDuration;
- (void)resetViewabilityState;
- (id)init;

@end

