//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FlurryAdActor.h"

#import "FlurryAdConsentCacheDelegate-Protocol.h"
#import "FlurryPreCachingDelegate-Protocol.h"
#import "IFlurryAdRequestDelegate-Protocol.h"

@class FlurryAdActorDeferredQueue, NSHashTable, NSMutableDictionary, NSString;

@interface FlurryAdCache : FlurryAdActor <FlurryPreCachingDelegate, IFlurryAdRequestDelegate, FlurryAdConsentCacheDelegate>
{
    NSMutableDictionary *_adSpaceToAdUnitsMap;
    NSMutableDictionary *_freqCapIdToPreparedAds;
    NSMutableDictionary *_cacheKeyDict;
    Class _cacheKeyFactory;
    NSHashTable *_delegates;
    FlurryAdActorDeferredQueue *_deferredQueue;
}

+ (id)adCacheForAdViewType:(int)arg1 adTargeting:(id)arg2;
+ (id)adCaches;
@property(retain, nonatomic) FlurryAdActorDeferredQueue *deferredQueue; // @synthesize deferredQueue=_deferredQueue;
@property(retain, nonatomic) NSHashTable *delegates; // @synthesize delegates=_delegates;
@property(nonatomic) __weak Class cacheKeyFactory; // @synthesize cacheKeyFactory=_cacheKeyFactory;
@property(retain, nonatomic) NSMutableDictionary *cacheKeyDict; // @synthesize cacheKeyDict=_cacheKeyDict;
@property(retain, nonatomic) NSMutableDictionary *freqCapIdToPreparedAds; // @synthesize freqCapIdToPreparedAds=_freqCapIdToPreparedAds;
@property(retain, nonatomic) NSMutableDictionary *adSpaceToAdUnitsMap; // @synthesize adSpaceToAdUnitsMap=_adSpaceToAdUnitsMap;
- (void).cxx_destruct;
- (void)adRequest:(id)arg1 failedWithError:(id)arg2;
- (void)adRequest:(id)arg1 successfulWithData:(id)arg2;
- (void)unzipAssetPreCachingFile:(id)arg1;
- (void)assetPreCachingCancelled:(id)arg1;
- (void)assetPreCachingFailed:(id)arg1;
- (void)assetPreCachingDone:(id)arg1;
- (void)consentInformationUpdated;
- (id)block_fetchFromAdUnits:(id)arg1 usingFilter:(CDUnknownBlockType)arg2;
- (id)firstElementFromArray:(id)arg1;
- (_Bool)isTakeover:(id)arg1;
- (void)removeAndReportAdUnit:(id)arg1;
- (void)requestSuccessful:(id)arg1 withParams:(id)arg2;
- (void)requestDidCancel;
- (void)requestDidFail:(id)arg1 error:(id)arg2;
- (void)block_notifyCSRTBAdDidFailLoadToManager:(id)arg1;
- (void)block_notifyAdManager:(id)arg1;
- (void)block_notifyAdManagerRequestFailed:(id)arg1;
- (void)block_notifyRequestFailed:(id)arg1 error:(id)arg2;
- (void)notifyRequestFailed:(id)arg1 error:(id)arg2;
- (void)block_notifyAdDidLoad:(id)arg1;
- (void)block_notifyCSRTBAdDidFailLoad:(id)arg1;
- (void)block_deRegisterAdManagerDelegate:(id)arg1;
- (void)block_regsiterAdCacheDelegate:(id)arg1;
- (void)block_safeForEachAdCacheDelegate:(CDUnknownBlockType)arg1;
- (void)fetchRealTimeAdForCacheKey:(id)arg1 additionalParams:(id)arg2;
- (void)block_fetchAdUnitsFromServer:(id)arg1;
- (void)clearCache;
- (_Bool)updateFreqCapToAdUnitMap:(id)arg1;
- (void)block_resetCounterForId:(id)arg1 newCount:(int)arg2;
- (void)resetCounterForId:(id)arg1 newCount:(int)arg2;
- (unsigned long long)validatedCacheCountForKey:(id)arg1;
- (id)block_validatedCachedAdUnitsForKey:(id)arg1;
- (void)block_removeAdUnit:(id)arg1 withGroupId:(id)arg2 space:(id)arg3 withCapId:(id)arg4 andCondition:(int)arg5;
- (void)removeAdUnit:(id)arg1;
- (void)removeAdUnitForFreqCapId:(id)arg1 adSpace:(id)arg2;
- (void)removeAdUnitsForSpace:(id)arg1;
- (void)removeAdUnitsForGroupID:(id)arg1 withSpace:(id)arg2;
- (void)block_findAndReplace:(id)arg1 withNewAdUnit:(id)arg2;
- (void)block_addUnit:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)block_addAdUnits:(id)arg1;
- (void)addAdUnit:(id)arg1 forKey:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)addAdUnit:(id)arg1 forKey:(id)arg2;
- (void)addAdUnits:(id)arg1;
- (void)allCachedAdUnitsForKey:(id)arg1 forQueue:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (id)block_cachedAdUnitFromUnits:(id)arg1 cacheRetrievalPolicy:(id)arg2;
- (void)adUnitForKey:(id)arg1 adViewType:(id)arg2 retrievalPolicy:(id)arg3 additionalParams:(id)arg4 onQueue:(id)arg5 withCompletionHandler:(CDUnknownBlockType)arg6;
- (void)resumeOperationQueue;
- (void)deRegisterAdManagerDelegate:(id)arg1;
- (void)registerAdManagerDelegate:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

