//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface FlurryVASTManagerCollection : NSObject
{
    NSMutableDictionary *_adGuidToFlurryVASTManagerMap;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *adGuidToFlurryVASTManagerMap; // @synthesize adGuidToFlurryVASTManagerMap=_adGuidToFlurryVASTManagerMap;
- (void).cxx_destruct;
- (void)setVastManager:(id)arg1 forAdGuid:(id)arg2;
- (id)vastManagerForAdGuid:(id)arg1;
- (id)init;

@end

