//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FlurryStreamEntityBase.h"

@class NSData, NSDate;

@interface FlurryStreamEpoch : FlurryStreamEntityBase
{
    int _frameType;
    NSData *_payload;
    double _timeStamp;
    NSDate *_epochDate;
}

+ (id)streamEntityFromJSONData:(id)arg1;
+ (id)streamEpochWithDate:(id)arg1;
@property(retain, nonatomic) NSDate *epochDate; // @synthesize epochDate=_epochDate;
- (void)setTimeStamp:(double)arg1;
- (double)timeStamp;
- (void)setPayload:(id)arg1;
- (id)payload;
- (void)setFrameType:(int)arg1;
- (int)frameType;
- (void).cxx_destruct;
- (id)jsonRepresentation;
- (id)dictionaryRepresentation;
- (id)initEpochWithDate:(id)arg1;

@end

