//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "IFlurryAdViewController-Protocol.h"

@class FlurryAdFrame, NSString, UIButton, UIView;
@protocol IFlurryAd, IFlurryNativeAd;

@interface FlurryModalBannerViewController : UIViewController <IFlurryAdViewController>
{
    _Bool _statusBarHidden;
    id <IFlurryAd> _ad;
    UIView *_adView;
    FlurryAdFrame *_adFrame;
    UIButton *_closeButton;
    id <IFlurryNativeAd> _nativeAd;
}

@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
@property(retain, nonatomic) id <IFlurryNativeAd> nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) FlurryAdFrame *adFrame; // @synthesize adFrame=_adFrame;
@property(retain, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) id <IFlurryAd> ad; // @synthesize ad=_ad;
- (void).cxx_destruct;
- (void)adjustToOrientation:(long long)arg1;
- (void)adjustViewForCurrentUserInterface;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)centerAdView;
- (void)removeWindow;
- (id)clientViewController;
- (void)loadAd:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)closeAd:(id)arg1;
- (void)viewDidLoad;
- (id)initWithAd:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

