//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FlurryAdBeaconParameters.h"

@interface FlurryAdVideoBeaconParameters : FlurryAdBeaconParameters
{
    _Bool _autoPlayed;
    _Bool _muted;
    _Bool _skipAvailable;
    _Bool _expanded;
    _Bool _isInView100HalfTime;
    int _viewInfo;
    int _audioInfo;
    int _audioInView100;
    int _timeInView50;
    int _timeInView50MaxContinuous;
    struct CGSize _playerSize;
}

+ (id)beaconParametersWithPlayerSize:(struct CGSize)arg1 autoPlayed:(_Bool)arg2 muted:(_Bool)arg3 skipAvailable:(_Bool)arg4 expanded:(_Bool)arg5 viewInfo:(int)arg6 audioInfo:(int)arg7 audioInView100:(int)arg8 timeInView50:(int)arg9 timeInView50MaxContinuous:(int)arg10 isInView100HalfTime:(_Bool)arg11;
@property(nonatomic) _Bool isInView100HalfTime; // @synthesize isInView100HalfTime=_isInView100HalfTime;
@property(nonatomic) int timeInView50MaxContinuous; // @synthesize timeInView50MaxContinuous=_timeInView50MaxContinuous;
@property(nonatomic) int timeInView50; // @synthesize timeInView50=_timeInView50;
@property(nonatomic) int audioInView100; // @synthesize audioInView100=_audioInView100;
@property(nonatomic) int audioInfo; // @synthesize audioInfo=_audioInfo;
@property(nonatomic) int viewInfo; // @synthesize viewInfo=_viewInfo;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
@property(nonatomic) _Bool skipAvailable; // @synthesize skipAvailable=_skipAvailable;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
@property(nonatomic) _Bool autoPlayed; // @synthesize autoPlayed=_autoPlayed;
@property(nonatomic) struct CGSize playerSize; // @synthesize playerSize=_playerSize;
- (id)beaconKeyValues;

@end

