//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FlurryAdJSONParser.h"

@class FlurryAdSpaceLayoutParser;

@interface FlurryAdFrameParser : FlurryAdJSONParser
{
    FlurryAdSpaceLayoutParser *_adSpaceLayoutParser;
}

+ (Class)manifestClass;
@property(retain, nonatomic) FlurryAdSpaceLayoutParser *adSpaceLayoutParser; // @synthesize adSpaceLayoutParser=_adSpaceLayoutParser;
- (void).cxx_destruct;
- (id)build;
- (void)validateFieldsStoringErrorsTo:(id)arg1;
- (id)initWithPath:(id)arg1 payload:(id)arg2 options:(unsigned long long)arg3 validationFailureCallback:(CDUnknownBlockType)arg4;

@end

