//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface FlurryAdCallback : NSObject
{
    NSString *_event;
    NSArray *_commands;
}

@property(readonly, nonatomic) NSArray *commands; // @synthesize commands=_commands;
@property(readonly, nonatomic) NSString *event; // @synthesize event=_event;
- (void).cxx_destruct;
- (id)description;
- (id)initWithEvent:(id)arg1 andCommands:(id)arg2;

@end

