//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol GADCustomEventNativeAd, GADMediatedNativeAd;

@protocol GADCustomEventNativeAdDelegate <NSObject>
- (void)customEventNativeAd:(id <GADCustomEventNativeAd>)arg1 didFailToLoadWithError:(NSError *)arg2;
- (void)customEventNativeAd:(id <GADCustomEventNativeAd>)arg1 didReceiveMediatedNativeAd:(id <GADMediatedNativeAd>)arg2;
@end

