//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GADAdLoaderOptions.h"

@class GADCorrelator;

@interface GADCorrelatorAdLoaderOptions : GADAdLoaderOptions
{
    GADCorrelator *_correlator;
}

@property(retain, nonatomic) GADCorrelator *correlator; // @synthesize correlator=_correlator;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

