//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GADGMSGHandler.h"

@interface GADDelayPageCloseGMSGHandler : GADGMSGHandler
{
}

+ (id)actionBlockDictionary;
- (_Bool)shouldBufferNotification:(id)arg1 adView:(id)arg2;
- (void)adView:(id)arg1 didReceiveDelayPageCloseAction:(id)arg2;

@end

