//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface GADGCacheURLLoader : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
- (void)requestGCacheURLLoad:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)prefetchGCacheURL:(id)arg1;
- (void)loadGCacheURL:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

