//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADInterstitialPoolRefilling-Protocol.h"

@class NSHashTable, NSString;
@protocol OS_dispatch_queue;

@interface GADInterstitialPoolGroupRefillPolicy : NSObject <GADInterstitialPoolRefilling>
{
    NSHashTable *_pools;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
- (void)addPool:(id)arg1;
- (void)fillPools;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

