//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GADAd, GADAudioVideoManager, GADRequest, GADSlot, NSArray, NSString, UIView, UIViewController;

@protocol GADSlotDelegate <NSObject>

@optional
- (_Bool)slot:(GADSlot *)arg1 shouldDisableVideoEventReportToAudioVideoManager:(GADAudioVideoManager *)arg2;
- (_Bool)slot:(GADSlot *)arg1 shouldChangeAudioSessionCategoryTo:(NSString *)arg2;
- (void)slotDidReceiveAdClick:(GADSlot *)arg1;
- (void)slot:(GADSlot *)arg1 willLoadAdWithRequest:(GADRequest *)arg2;
- (_Bool)slot:(GADSlot *)arg1 notifyPublisherToRenderCustomRenderingAd:(GADAd *)arg2 error:(id *)arg3;
- (void)slot:(GADSlot *)arg1 didReceiveAppEvent:(NSString *)arg2 withInfo:(NSString *)arg3;
- (void)slot:(GADSlot *)arg1 willResizeToAdSize:(struct GADAdSize)arg2;
- (void)slotDidLoadMRAIDAd:(GADSlot *)arg1;
- (NSArray *)validAdSizes;
- (struct GADAdSize)adSize;
- (void)layoutSubviewsIfNeeded;
- (void)setAdSize:(struct GADAdSize)arg1 andReload:(_Bool)arg2;
- (void)slot:(GADSlot *)arg1 contentSizeDidChange:(struct CGSize)arg2;
- (void)slot:(GADSlot *)arg1 didReceiveAdView:(UIView *)arg2;
- (UIViewController *)rootViewController;
- (struct CGRect)bounds;
- (struct CGRect)frameInInterface;
- (struct CGRect)frame;
- (_Bool)slotShouldPreemptInProgressRequest:(GADSlot *)arg1;
- (_Bool)slotShouldReloadCurrentRequest:(GADSlot *)arg1;
- (_Bool)slot:(GADSlot *)arg1 shouldLoadRequest:(GADRequest *)arg2 error:(id *)arg3;
@end

