//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface GADStatisticsCore : NSObject
{
    NSMutableDictionary *_statistics;
    NSString *_userDefaultsKey;
    NSObject<OS_dispatch_queue> *_lockQueue;
}

- (void).cxx_destruct;
- (void)removeObjectForKey:(id)arg1;
- (void)appendDictionary:(id)arg1 toArrayForKey:(id)arg2;
- (void)appendString:(id)arg1 toArrayForKey:(id)arg2;
- (id)arrayForKey:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)savePersistentStatistics;
- (void)applicationWillTerminate:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *statistics;
- (void)dealloc;
- (id)init;

@end

