//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GADResourceCache, GADVideoConfiguration, NSURL;

@interface GADVideoAssetLoader : NSObject
{
    NSURL *_sourceURL;
    GADResourceCache *_mainResourceCache;
    GADVideoConfiguration *_videoConfiguration;
    GADResourceCache *_resourceCache;
    long long _resourceCacheStartingByteOffset;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)finishedUsingResourceCache:(id)arg1;
- (_Bool)getResourceCache:(id *)arg1 startingByteOffset:(long long *)arg2 loadingByteOffset:(long long)arg3 error:(id *)arg4;
- (id)initWithVideoURL:(id)arg1 resourceCache:(id)arg2 videoConfiguration:(id)arg3;

@end

