//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GADVideoController;

@protocol GADVideoControllerDelegate <NSObject>

@optional
- (void)videoControllerDidUnmuteVideo:(GADVideoController *)arg1;
- (void)videoControllerDidMuteVideo:(GADVideoController *)arg1;
- (void)videoControllerDidEndVideoPlayback:(GADVideoController *)arg1;
- (void)videoControllerDidPauseVideo:(GADVideoController *)arg1;
- (void)videoControllerDidPlayVideo:(GADVideoController *)arg1;
@end

