//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@protocol IFlurryAdStoreKey;

@protocol IFlurryAdStoreKey <NSObject, NSCopying>
- (unsigned long long)hash;
- (_Bool)isEqual:(id <IFlurryAdStoreKey>)arg1;
@end

