//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IMError, IMInterstitial, NSDictionary;

@protocol IMInterstitialDelegate <NSObject>

@optional
- (void)interstitial:(IMInterstitial *)arg1 didFailToPresentScreenWithError:(IMError *)arg2;
- (void)interstitialDidInteract:(IMInterstitial *)arg1 withParams:(NSDictionary *)arg2;
- (void)interstitialWillLeaveApplication:(IMInterstitial *)arg1;
- (void)interstitialDidDismissScreen:(IMInterstitial *)arg1;
- (void)interstitialWillDismissScreen:(IMInterstitial *)arg1;
- (void)interstitialWillPresentScreen:(IMInterstitial *)arg1;
- (void)interstitial:(IMInterstitial *)arg1 didFailToReceiveAdWithError:(IMError *)arg2;
- (void)interstitialDidReceiveAd:(IMInterstitial *)arg1;
@end

