//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol MTLDrawable <NSObject>
@property(nonatomic, readonly) long long drawableID;
@property(nonatomic, readonly) double presentedTime;
- (void)addPresentedHandler:(void (^)(id <MTLDrawable>))arg1;
- (void)presentAfterMinimumDuration:(double)arg1;
- (void)presentAtTime:(double)arg1;
- (void)present;
@end

