//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (YVideoMP4Parser)
- (id)subarray:(unsigned long long)arg1 end:(unsigned long long)arg2;
- (unsigned int)getUint8:(unsigned long long)arg1;
- (unsigned int)getUint16:(unsigned long long)arg1;
- (unsigned int)getUint32:(unsigned long long)arg1;
@end

