//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class O2ItemID;

@interface O2BatsBeaconAdCallDetectorResult : NSObject
{
    _Bool _isSuccessful;
    O2ItemID *_itemId;
}

+ (id)failureResultWithItemId:(id)arg1;
+ (id)successResultWithItemId:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isSuccessful; // @synthesize isSuccessful=_isSuccessful;
@property(readonly, copy, nonatomic) O2ItemID *itemId; // @synthesize itemId=_itemId;
- (id)initWithItemId:(id)arg1 isSuccessful:(_Bool)arg2;

@end

