//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface O2Clickthrough : NSObject
{
    _Bool _isPresentationRequested;
}

+ (id)reduce:(id)arg1 andAction:(id)arg2;
+ (id)stateWithClickthroughToggled:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isPresentationRequested; // @synthesize isPresentationRequested=_isPresentationRequested;
- (id)initStateWithClickthroughToggled:(_Bool)arg1;

@end

