//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface O2CurrentTimeActionCreator : NSObject
{
}

+ (id)updateCurrentTime:(CDStruct_1b6d18a9)arg1;

@end

