//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface O2ItemParserWorker : NSObject
{
    CDUnknownBlockType _parseItem;
    CDUnknownBlockType _dispatch;
    NSMutableSet *_processedIDs;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSMutableSet *processedIDs; // @synthesize processedIDs=_processedIDs;
@property(readonly, copy, nonatomic) CDUnknownBlockType dispatch; // @synthesize dispatch=_dispatch;
@property(readonly, copy, nonatomic) CDUnknownBlockType parseItem; // @synthesize parseItem=_parseItem;
- (void)processState:(id)arg1;
- (void)processParserQueueScheduledItems:(id)arg1;
- (id)initWithDispatch:(CDUnknownBlockType)arg1 parseItem:(CDUnknownBlockType)arg2;

@end

