//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, O2FetchItemID, O2ItemID;

@interface O2ItemFetchInfo : NSObject
{
    O2FetchItemID *_fetchID;
    O2ItemID *_itemID;
    NSURL *_url;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, copy, nonatomic) O2ItemID *itemID; // @synthesize itemID=_itemID;
@property(readonly, nonatomic) O2FetchItemID *fetchID; // @synthesize fetchID=_fetchID;
- (id)initWithItemID:(id)arg1 url:(id)arg2;

@end

