//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, O2Clickthrough, O2CurrentTime, O2Duration, O2IconClickthrough, O2IconViewDisplay, O2Mute, O2Play, O2PlaybackStatus, O2SkipAd, O2Viewport;

@interface O2PlayerState : NSObject
{
    NSDate *_creationDate;
    O2Mute *_mute;
    O2Play *_play;
    O2CurrentTime *_currentTime;
    O2Viewport *_viewport;
    O2Duration *_duration;
    O2Clickthrough *_clickthrough;
    O2PlaybackStatus *_playback;
    O2SkipAd *_skipAd;
    O2IconViewDisplay *_iconView;
    O2IconClickthrough *_iconClickthrough;
}

+ (id)reduce:(id)arg1 andAction:(id)arg2;
+ (id)stateWithMute:(id)arg1 play:(id)arg2 currentTime:(id)arg3 viewport:(id)arg4 duration:(id)arg5 clickthrough:(id)arg6 playback:(id)arg7 currentDate:(id)arg8 skip:(id)arg9 iconView:(id)arg10 iconClickthrough:(id)arg11;
+ (id)defaultStateWithCurrentDate:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) O2IconClickthrough *iconClickthrough; // @synthesize iconClickthrough=_iconClickthrough;
@property(readonly, nonatomic) O2IconViewDisplay *iconView; // @synthesize iconView=_iconView;
@property(readonly, nonatomic) O2SkipAd *skipAd; // @synthesize skipAd=_skipAd;
@property(readonly, nonatomic) O2PlaybackStatus *playback; // @synthesize playback=_playback;
@property(readonly, nonatomic) O2Clickthrough *clickthrough; // @synthesize clickthrough=_clickthrough;
@property(readonly, nonatomic) O2Duration *duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) O2Viewport *viewport; // @synthesize viewport=_viewport;
@property(readonly, nonatomic) O2CurrentTime *currentTime; // @synthesize currentTime=_currentTime;
@property(readonly, nonatomic) O2Play *play; // @synthesize play=_play;
@property(readonly, nonatomic) O2Mute *mute; // @synthesize mute=_mute;
@property(readonly, copy, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
- (id)initStateWithMute:(id)arg1 play:(id)arg2 currentTime:(id)arg3 viewport:(id)arg4 duration:(id)arg5 clickthrough:(id)arg6 playback:(id)arg7 currentDate:(id)arg8 skip:(id)arg9 iconView:(id)arg10 iconClickthrough:(id)arg11;

@end

