//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface O2SkipAd : NSObject
{
    _Bool _isSkipped;
}

+ (id)reduceWithState:(id)arg1 action:(id)arg2;
@property(nonatomic) _Bool isSkipped; // @synthesize isSkipped=_isSkipped;
- (id)initWithSkip:(_Bool)arg1;

@end

