//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface O2Timer : NSObject
{
    NSTimer *_timer;
    CDUnknownBlockType _fire;
}

+ (id)timerWithInterval:(double)arg1 fire:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType fire; // @synthesize fire=_fire;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void)cancel;
- (void)onFire;
- (id)initWithTimeInterval:(double)arg1 fire:(CDUnknownBlockType)arg2;

@end

