//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "O2VASTModel-Protocol.h"

@class NSArray, NSNumber, NSString, NSURL, O2VASTModelPixels;

@interface O2VASTWrapperModel : NSObject <O2VASTModel>
{
    NSNumber *_sequence;
    NSURL *_tagURL;
    O2VASTModelPixels *_pixels;
    NSArray *_icons;
    NSArray *_adVerification;
    NSString *_adId;
    NSString *_adSystem;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *adSystem; // @synthesize adSystem=_adSystem;
@property(readonly, copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(copy, nonatomic) NSArray *adVerification; // @synthesize adVerification=_adVerification;
@property(copy, nonatomic) NSArray *icons; // @synthesize icons=_icons;
@property(readonly, nonatomic) O2VASTModelPixels *pixels; // @synthesize pixels=_pixels;
@property(readonly, copy, nonatomic) NSURL *tagURL; // @synthesize tagURL=_tagURL;
@property(readonly, nonatomic) NSNumber *sequence; // @synthesize sequence=_sequence;
- (id)initWithTagURL:(id)arg1 pixels:(id)arg2 sequence:(id)arg3 icons:(id)arg4 adVerification:(id)arg5 adId:(id)arg6 adSystem:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

