//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, O2AdOpptyBeaconStatus, O2AdPrefetchStartTime, O2CurrentGroup, O2CurrentSlot, O2ErroredItems, O2FinalResult, O2GroupQueue, O2History, O2ItemFetcherQueue, O2ItemParserQueue, O2ItemsResponseSequence, O2ItemsResponseTime, O2PlacementIds, O2RetriableItems, O2ScheduledItems, O2SlotQueue, O2Timeout, O2TimeoutItems, O2TopPriorityItem, O2WrapperItemResults, O2WrapperItems;

@interface O2VRMState : NSObject
{
    NSDictionary *_allSlots;
    NSDictionary *_groupsPerSlot;
    NSDictionary *_allGroups;
    NSDictionary *_allItems;
    NSDictionary *_itemsPerGroup;
    unsigned long long _allPodsCount;
    unsigned long long _backendVersion;
    NSString *_generalSlot;
    double _softTimeout;
    double _hardTimeout;
    O2Timeout *_timeout;
    unsigned long long _maxWrapperRedirectCount;
    O2RetriableItems *_retriableItems;
    O2SlotQueue *_slotQueue;
    O2CurrentSlot *_currentSlot;
    O2GroupQueue *_groupQueue;
    O2CurrentGroup *_currentGroup;
    O2ScheduledItems *_scheduledItems;
    O2WrapperItemResults *_itemResults;
    O2TimeoutItems *_timeoutItems;
    O2ErroredItems *_erroredItems;
    O2WrapperItems *_wrapperItemsCount;
    O2ItemParserQueue *_itemParserQueue;
    O2ItemFetcherQueue *_itemFetcherQueue;
    O2TopPriorityItem *_topPriorityItem;
    O2FinalResult *_finalResult;
    O2History *_history;
    O2ItemsResponseTime *_itemsResponseTime;
    O2ItemsResponseSequence *_itemsResponseSequence;
    O2AdOpptyBeaconStatus *_adOpptyBeaconStatus;
    O2AdPrefetchStartTime *_adPrefetchStartTime;
    O2PlacementIds *_placementIds;
}

+ (id)reduceWithState:(id)arg1 action:(id)arg2 actionId:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) O2PlacementIds *placementIds; // @synthesize placementIds=_placementIds;
@property(readonly, nonatomic) O2AdPrefetchStartTime *adPrefetchStartTime; // @synthesize adPrefetchStartTime=_adPrefetchStartTime;
@property(readonly, nonatomic) O2AdOpptyBeaconStatus *adOpptyBeaconStatus; // @synthesize adOpptyBeaconStatus=_adOpptyBeaconStatus;
@property(readonly, nonatomic) O2ItemsResponseSequence *itemsResponseSequence; // @synthesize itemsResponseSequence=_itemsResponseSequence;
@property(readonly, nonatomic) O2ItemsResponseTime *itemsResponseTime; // @synthesize itemsResponseTime=_itemsResponseTime;
@property(readonly, nonatomic) O2History *history; // @synthesize history=_history;
@property(readonly, nonatomic) O2FinalResult *finalResult; // @synthesize finalResult=_finalResult;
@property(readonly, nonatomic) O2TopPriorityItem *topPriorityItem; // @synthesize topPriorityItem=_topPriorityItem;
@property(readonly, nonatomic) O2ItemFetcherQueue *itemFetcherQueue; // @synthesize itemFetcherQueue=_itemFetcherQueue;
@property(readonly, nonatomic) O2ItemParserQueue *itemParserQueue; // @synthesize itemParserQueue=_itemParserQueue;
@property(readonly, nonatomic) O2WrapperItems *wrapperItemsCount; // @synthesize wrapperItemsCount=_wrapperItemsCount;
@property(readonly, nonatomic) O2ErroredItems *erroredItems; // @synthesize erroredItems=_erroredItems;
@property(readonly, nonatomic) O2TimeoutItems *timeoutItems; // @synthesize timeoutItems=_timeoutItems;
@property(readonly, nonatomic) O2WrapperItemResults *itemResults; // @synthesize itemResults=_itemResults;
@property(readonly, nonatomic) O2ScheduledItems *scheduledItems; // @synthesize scheduledItems=_scheduledItems;
@property(readonly, nonatomic) O2CurrentGroup *currentGroup; // @synthesize currentGroup=_currentGroup;
@property(readonly, nonatomic) O2GroupQueue *groupQueue; // @synthesize groupQueue=_groupQueue;
@property(readonly, nonatomic) O2CurrentSlot *currentSlot; // @synthesize currentSlot=_currentSlot;
@property(readonly, nonatomic) O2SlotQueue *slotQueue; // @synthesize slotQueue=_slotQueue;
@property(readonly, nonatomic) O2RetriableItems *retriableItems; // @synthesize retriableItems=_retriableItems;
@property(readonly, nonatomic) unsigned long long maxWrapperRedirectCount; // @synthesize maxWrapperRedirectCount=_maxWrapperRedirectCount;
@property(readonly, nonatomic) O2Timeout *timeout; // @synthesize timeout=_timeout;
@property(readonly, nonatomic) double hardTimeout; // @synthesize hardTimeout=_hardTimeout;
@property(readonly, nonatomic) double softTimeout; // @synthesize softTimeout=_softTimeout;
@property(readonly, copy, nonatomic) NSString *generalSlot; // @synthesize generalSlot=_generalSlot;
@property(readonly, nonatomic) unsigned long long backendVersion; // @synthesize backendVersion=_backendVersion;
@property(readonly, nonatomic) unsigned long long allPodsCount; // @synthesize allPodsCount=_allPodsCount;
@property(readonly, copy, nonatomic) NSDictionary *itemsPerGroup; // @synthesize itemsPerGroup=_itemsPerGroup;
@property(readonly, copy, nonatomic) NSDictionary *allItems; // @synthesize allItems=_allItems;
@property(readonly, copy, nonatomic) NSDictionary *allGroups; // @synthesize allGroups=_allGroups;
@property(readonly, copy, nonatomic) NSDictionary *groupsPerSlot; // @synthesize groupsPerSlot=_groupsPerSlot;
@property(readonly, copy, nonatomic) NSDictionary *allSlots; // @synthesize allSlots=_allSlots;
- (id)initWithSlots:(id)arg1 allPodsCount:(unsigned long long)arg2 backendVersion:(unsigned long long)arg3 generalSlot:(id)arg4 maxWrapperRedirectCount:(unsigned long long)arg5 softTimeout:(double)arg6 hardTimeout:(double)arg7;
- (id)initWithAllSlots:(id)arg1 groupIDsPerSlotID:(id)arg2 allGroups:(id)arg3 allItems:(id)arg4 itemIDsPerGroupID:(id)arg5 allPodsCount:(unsigned long long)arg6 backendVersion:(unsigned long long)arg7 generalSlot:(id)arg8 maxWrapperRedirectCount:(unsigned long long)arg9 softTimeout:(double)arg10 hardTimeout:(double)arg11 retriableItems:(id)arg12 slotQueue:(id)arg13 currentSlot:(id)arg14 groupQueue:(id)arg15 currentGroup:(id)arg16 scheduledItems:(id)arg17 itemResults:(id)arg18 timeoutItems:(id)arg19 erroredItems:(id)arg20 wrapperItemsCount:(id)arg21 itemParserQueue:(id)arg22 itemFetcherQueue:(id)arg23 itemResultPriority:(id)arg24 finalResult:(id)arg25 timeout:(id)arg26 history:(id)arg27 itemsResponseTime:(id)arg28 itemsResponseSequence:(id)arg29 adOpptyBeaconStatus:(id)arg30 adPrefetchStartTime:(id)arg31 placementIds:(id)arg32;

@end

