//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface O2WrapperItemResults : NSObject
{
    NSDictionary *_items;
}

+ (id)reduceWithState:(id)arg1 action:(id)arg2;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *items; // @synthesize items=_items;
- (id)initWithIDs:(id)arg1;

@end

