//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "OAConsentProvider.h"

@interface OAPrivacyConsentProvider : OAConsentProvider
{
}

- (id)consentRecord;
- (_Bool)isGDPRJurisdiction;
- (id)init;

@end

