//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PSPhotosetDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, PSPhotoset, UILongPressGestureRecognizer;
@protocol PSLightTableViewDelegate;

@interface PSLightTableView : UIView <PSPhotosetDelegate>
{
    _Bool _isDragging;
    _Bool _shouldAnimateDashedLine;
    PSPhotoset *_photoset;
    id <PSLightTableViewDelegate> _delegate;
    NSMutableDictionary *_photoViews;
    UILongPressGestureRecognizer *_currentLongPressGestureRecognizer;
    struct CGPoint _initialPressLocation;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILongPressGestureRecognizer *currentLongPressGestureRecognizer; // @synthesize currentLongPressGestureRecognizer=_currentLongPressGestureRecognizer;
@property(nonatomic) struct CGPoint initialPressLocation; // @synthesize initialPressLocation=_initialPressLocation;
@property(retain, nonatomic) NSMutableDictionary *photoViews; // @synthesize photoViews=_photoViews;
@property(nonatomic) _Bool shouldAnimateDashedLine; // @synthesize shouldAnimateDashedLine=_shouldAnimateDashedLine;
@property(nonatomic) __weak id <PSLightTableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isDragging; // @synthesize isDragging=_isDragging;
@property(retain, nonatomic) PSPhotoset *photoset; // @synthesize photoset=_photoset;
@property(readonly, nonatomic) NSArray *photosetItemViews;
- (void)animateDashedLines;
- (void)animateLayoutForDragPoint:(struct CGPoint)arg1 excludingView:(id)arg2;
- (void)didReceiveLongPressGesture:(id)arg1;
- (void)didReceiveTapGesture:(id)arg1;
- (void)removePhotoFromLightTable:(id)arg1 animated:(_Bool)arg2;
- (void)addPhotoToLightTable:(id)arg1 animated:(_Bool)arg2;
- (void)applyLayoutRectangles;
- (void)applyLayoutRectanglesAnimated;
- (void)photoset:(id)arg1 didAddPhoto:(id)arg2;
- (void)photoset:(id)arg1 didRemovePhoto:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

