//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class PSPhotoset, UIView;
@protocol PSPhotoDescriptor;

@protocol PSPhotosetDelegate
- (void)photoset:(PSPhotoset *)arg1 didAddPhoto:(UIView<PSPhotoDescriptor> *)arg2;
- (void)photoset:(PSPhotoset *)arg1 didRemovePhoto:(UIView<PSPhotoDescriptor> *)arg2;
@end

