//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RTStep.h"

@interface RTFirstrunStep : RTStep
{
}

- (void)runSuspendedStep;
- (void)runUnfocusedStep;
- (void)runPostStartupStepWithInfo:(id)arg1;
- (void)runPostStartupStep;
- (void)runStartupStepWithInfo:(id)arg1;
- (void)runStartupStep;

@end

