//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "RTHandleProxyMethods-Protocol.h"

@class NSString, RTIDGenerator, RTKernel;

@interface RTHandleProxy : NSObject <NSCopying, RTHandleProxyMethods>
{
    NSString *mHandleID;
    RTIDGenerator *mInvokeIDGenerator;
    NSString *mContextID;
    RTKernel *mKernel;
}

- (void).cxx_destruct;
@property(nonatomic) RTKernel *kernel; // @synthesize kernel=mKernel;
@property(retain, nonatomic) NSString *contextID; // @synthesize contextID=mContextID;
@property(retain, nonatomic) RTIDGenerator *invokeIDGenerator; // @synthesize invokeIDGenerator=mInvokeIDGenerator;
@property(retain, nonatomic) NSString *handleID; // @synthesize handleID=mHandleID;
- (void)cancelMethod:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithHandleID:(id)arg1 kernel:(id)arg2 invocationIDGenerator:(id)arg3 contextID:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

