//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperationQueue.h>

@class RTObject;

@interface RTOperationQueue : NSOperationQueue
{
    RTObject *mObject;
}

- (void).cxx_destruct;
@property(nonatomic) __weak RTObject *owner; // @synthesize owner=mObject;
- (_Bool)isSuspended;
- (void)setSuspended:(_Bool)arg1;
- (void)setMaxConcurrentOperationCount:(long long)arg1;
- (long long)maxConcurrentOperationCount;
- (void)waitUntilAllOperationsAreFinished;
- (void)cancelAllOperations;
- (unsigned long long)operationCount;
- (id)operations;
- (void)addOperationWithBlock:(CDUnknownBlockType)arg1;
- (void)addOperations:(id)arg1 waitUntilFinished:(_Bool)arg2;
- (void)addOperation:(id)arg1;
- (void)dealloc;
- (id)initWithOwner:(id)arg1;
- (id)init;

@end

