//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, RTKernel;
@protocol RTURLProtocolHandler;

@protocol RTURLProtocolRegistrar <NSObject>
+ (void)registerHandler:(id <RTURLProtocolHandler>)arg1 forToken:(NSString *)arg2 success:(void (^)(void))arg3 error:(void (^)(RTError *))arg4;
+ (void)unregisterURLProtocol;
+ (void)registerURLProtocolForKernel:(RTKernel *)arg1;
@end

