//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TMAPIErrorFactory : NSObject
{
    _Bool _legacy;
    NSArray *_errors;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool legacy; // @synthesize legacy=_legacy;
@property(readonly, nonatomic) NSArray *errors; // @synthesize errors=_errors;
- (id)APIErrors;
- (id)initWithErrors:(id)arg1 legacy:(_Bool)arg2;

@end

