//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol TMAppUserAuthenticationControllerDelegate <NSObject>
- (void)userAuthenticationControllerNoticeWasReceived:(NSString *)arg1 noticeWasApproved:(void (^)(void))arg2 noticeWasDenied:(void (^)(void))arg3;
- (void)userAuthenticationControllerDidLogout;
- (void)userAuthenticationControllerDidLoginWithInterfaceUpdatedBlock:(void (^)(void))arg1;
@end

