//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL, TMBlogHeaderView, TMCustomizeTextView;

@protocol TMBlogHeaderViewDelegate <NSObject>
- (void)blogHeaderViewDidChangeDescriptionText:(TMBlogHeaderView *)arg1;
- (void)blogHeaderViewDidChangeTitleText:(TMBlogHeaderView *)arg1;
- (void)blogHeaderViewHeightChanged:(TMBlogHeaderView *)arg1;
- (void)blogHeaderView:(TMBlogHeaderView *)arg1 longPressedLinkWithURL:(NSURL *)arg2 inRect:(struct CGRect)arg3;
- (void)blogHeaderView:(TMBlogHeaderView *)arg1 tappedLinkWithURL:(NSURL *)arg2;
- (void)blogHeaderView:(TMBlogHeaderView *)arg1 textViewDidChangeTextSelection:(TMCustomizeTextView *)arg2;
- (void)blogHeaderView:(TMBlogHeaderView *)arg1 didBeginEditingTextView:(TMCustomizeTextView *)arg2;
- (_Bool)blogHeaderView:(TMBlogHeaderView *)arg1 shouldBeginEditingTextView:(TMCustomizeTextView *)arg2;
@end

