//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UILabel;

@interface TMBlogResultsSectionView : UITableViewHeaderFooterView
{
    _Bool _verticallyCentered;
    _Bool _fullWidthOnTablet;
    UILabel *_titleLabel;
    double _verticalInset;
    double _iPadContentWidth;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool fullWidthOnTablet; // @synthesize fullWidthOnTablet=_fullWidthOnTablet;
@property(nonatomic) double iPadContentWidth; // @synthesize iPadContentWidth=_iPadContentWidth;
@property(nonatomic) _Bool verticallyCentered; // @synthesize verticallyCentered=_verticallyCentered;
@property(nonatomic) double verticalInset; // @synthesize verticalInset=_verticalInset;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setUpLabel;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

