//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP8TumblrUI5Toast_-Protocol.h"

@class MISSING_TYPE, NSAttributedString, UIColor;

@interface TMBlogDeletionToast : NSObject <_TtP8TumblrUI5Toast_>
{
    MISSING_TYPE *toastPresentationStyle;
    MISSING_TYPE *message;
    MISSING_TYPE *deleted;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) long long toastPresentationStyle; // @synthesize toastPresentationStyle;
@property(nonatomic, readonly) UIColor *tintColor;
@property(nonatomic, readonly) NSAttributedString *attributedText;

@end

