//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSDictionary, NSString;

@interface TMBlogAvatar : NSObject <NSSecureCoding>
{
    NSDictionary *_avatarURLs;
    NSString *_blogName;
}

+ (id)avatarURLStringForBlogUUID:(id)arg1 size:(unsigned long long)arg2;
+ (id)avatarURLStringForBlogName:(id)arg1 size:(unsigned long long)arg2;
+ (unsigned long long)avatarSizeNoScalingForWidth:(double)arg1;
+ (unsigned long long)avatarSizeForWidth:(double)arg1;
+ (_Bool)supportsSecureCoding;
+ (unsigned long long)widthForAvatarSize:(unsigned long long)arg1;
+ (id)allAvatarURLsforBlogName:(id)arg1;
+ (id)allAvatarSizes;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *blogName; // @synthesize blogName=_blogName;
@property(retain, nonatomic) NSDictionary *avatarURLs; // @synthesize avatarURLs=_avatarURLs;
- (id)avatarURLStringForWidth:(double)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)updateAvatar:(id)arg1;
- (id)initWithBlogName:(id)arg1 avatarArray:(id)arg2;

@end

