//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TMCarouselHiddenButton;

@protocol TMCarouselHiddenButtonDelegate <NSObject>
- (void)carouselHiddenButtonWasSelected:(TMCarouselHiddenButton *)arg1;
- (void)carouselHiddenButton:(TMCarouselHiddenButton *)arg1 didBecomeHighlighted:(_Bool)arg2;
@end

