//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@protocol TMCarouselHiddenButtonDelegate;

@interface TMCarouselHiddenButton : UIButton
{
    id <TMCarouselHiddenButtonDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <TMCarouselHiddenButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void)selected:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

