//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMPostParameters.h"

@class NSString;

@interface TMChatPostParameters : TMPostParameters
{
    NSString *_title;
    NSString *_conversation;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *conversation; // @synthesize conversation=_conversation;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)init;
- (id)stringFromDialogue:(id)arg1;
- (id)dictionaryRepresentation;
- (void)fillWithPostValues:(id)arg1;

@end

