//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface TMClippingView : UIView
{
    UIView *_clippingView;
    UIView *_containerView;
    struct UIEdgeInsets _clippingInsets;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *clippingView; // @synthesize clippingView=_clippingView;
@property(nonatomic) struct UIEdgeInsets clippingInsets; // @synthesize clippingInsets=_clippingInsets;
- (void)addContentView:(id)arg1;
- (_Bool)isClipped;
- (id)initWithFrame:(struct CGRect)arg1;

@end

