//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TMRedesignedReblogViewModelFactory-Protocol.h"

@class NSString;

@interface TMComposeReblogViewModelFactory : NSObject <TMRedesignedReblogViewModelFactory>
{
}

- (id)reblogTrailViewModelsWithPost:(id)arg1 viewConfiguration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

