//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "TMHeightRequiring-Protocol.h"

@class AVPlayer, AVPlayerLayer, NSString, NSURL, UIButton, UIView, _TtC8TumblrUI11TMImageView;

@interface TMComposeVideoCell : UITableViewCell <TMHeightRequiring>
{
    AVPlayerLayer *_playerLayer;
    UIView *_playerContainer;
    UIButton *_playButton;
    UIButton *_pauseButton;
    _TtC8TumblrUI11TMImageView *_mediaImageView;
    struct CGSize _mediaSize;
    _Bool _playing;
    double _heightRequired;
    AVPlayer *_player;
    NSURL *_mediaURL;
    NSString *_thumbnailURLString;
    struct CGSize _thumbnailSize;
}

- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isPlaying) _Bool playing; // @synthesize playing=_playing;
@property(nonatomic) struct CGSize thumbnailSize; // @synthesize thumbnailSize=_thumbnailSize;
@property(copy, nonatomic) NSString *thumbnailURLString; // @synthesize thumbnailURLString=_thumbnailURLString;
@property(retain, nonatomic) NSURL *mediaURL; // @synthesize mediaURL=_mediaURL;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(readonly, nonatomic) double heightRequired; // @synthesize heightRequired=_heightRequired;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)playbackDidFinish;
- (id)mediaImageView;
- (id)pauseButton;
- (id)playButton;
- (void)updateUIForUnplayableVideo;
- (void)pauseVideo:(id)arg1;
- (void)playVideo:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

