//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TMComposeOptionsProviding-Protocol.h"

@class NSArray, NSString, TMPostParameters, _TtC6Tumblr26BlocksPostContentViewModel;
@protocol TMComposePostDataSource, TMPostDeliverer;

@interface TMComposeDefaultOptions : NSObject <TMComposeOptionsProviding>
{
    _Bool _editing;
    _Bool _GIFFilter;
    int _initialPostState;
    TMPostParameters *_postParameters;
    id <TMPostDeliverer> _postDeliverer;
    NSString *_currentlyViewingBlogUUID;
    id <TMComposePostDataSource> _composePostDataSource;
    NSArray *_suggestedTags;
    _TtC6Tumblr26BlocksPostContentViewModel *_blocksPostContentViewModel;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) int initialPostState; // @synthesize initialPostState=_initialPostState;
@property(readonly, nonatomic) _TtC6Tumblr26BlocksPostContentViewModel *blocksPostContentViewModel; // @synthesize blocksPostContentViewModel=_blocksPostContentViewModel;
@property(readonly, nonatomic) NSArray *suggestedTags; // @synthesize suggestedTags=_suggestedTags;
@property(retain, nonatomic) id <TMComposePostDataSource> composePostDataSource; // @synthesize composePostDataSource=_composePostDataSource;
@property(readonly, nonatomic) NSString *currentlyViewingBlogUUID; // @synthesize currentlyViewingBlogUUID=_currentlyViewingBlogUUID;
@property(nonatomic) _Bool GIFFilter; // @synthesize GIFFilter=_GIFFilter;
@property(readonly, nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
@property(readonly, nonatomic) id <TMPostDeliverer> postDeliverer; // @synthesize postDeliverer=_postDeliverer;
@property(retain, nonatomic) TMPostParameters *postParameters; // @synthesize postParameters=_postParameters;
- (_Bool)canShowNewPostFormsCanvasForPostType:(int)arg1;
@property(readonly, nonatomic) _Bool useMultipleStepPosting;
@property(readonly, nonatomic) _Bool useAdvancedOptionsRedesign;
- (_Bool)canUseAdvancedPostOptionsForPostType:(int)arg1;
- (id)URLHandlingViewControllerWithURL:(id)arg1;
- (Class)composeNavigationBarClass;
- (_Bool)canShowPopoverMediaPicker;
- (_Bool)cancellingVideoEditingShouldCancelComposing;
- (id)customTitleView;
- (id)reblogViewFactory;
- (id)reblogCellFactory;
- (unsigned long long)composeActionsDisplayStyle;
- (_Bool)createdAsLegacy;
- (_Bool)shouldDismissAfterPostAutomatically;
- (_Bool)shouldShowMiniMediaPicker;
- (_Bool)canAddAudios;
- (_Bool)shouldShowGallery;
- (_Bool)canAddVideos;
- (_Bool)canAddImages;
- (_Bool)canAddGIFs;
- (_Bool)canShowCameraInput;
- (id)submissionTerms;
- (_Bool)isInterAppCommunication;
- (id)askTargetBlog;
- (_Bool)isAsk;
- (_Bool)isSubmission;
- (_Bool)isShare;
- (_Bool)shouldUseCurrentlyViewingBlogByDefault;
- (_Bool)shouldUsePreviouslyPostedBlogByDefault;
- (_Bool)shouldAllowDrafts;
- (id)suggestedTagNames;
- (id)permittedTagNames;
- (_Bool)shouldShowButtonForSocialNetwork:(long long)arg1;
- (_Bool)shouldAllowUserGeneratedTags;
- (_Bool)shouldShowContentSource;
- (_Bool)shouldShowPostSettings;
- (id)permittedComposeTypes;
- (id)initWithPostParameters:(id)arg1 isEditing:(_Bool)arg2 currentlyViewingBlogUUID:(id)arg3 suggestedTags:(id)arg4 blocksPostContentViewModel:(id)arg5;
- (id)initWithPostParameters:(id)arg1 isEditing:(_Bool)arg2 currentlyViewingBlogUUID:(id)arg3 suggestedTags:(id)arg4;
- (id)initWithPostParameters:(id)arg1 isEditing:(_Bool)arg2 currentlyViewingBlogUUID:(id)arg3;
- (id)initWithPostParameters:(id)arg1 isEditing:(_Bool)arg2;
- (id)initWithPostParameters:(id)arg1;
- (id)init;

@end

