//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class TMComposeEmbeddedMediaCell;
@protocol _TtP10CoreTumblr17ComposeEmbeddable_;

@protocol TMComposeEmbeddedMediaCellDelegate
- (void)composeEmbeddedMediaCell:(TMComposeEmbeddedMediaCell *)arg1 didRemoveEmbed:(id <_TtP10CoreTumblr17ComposeEmbeddable_>)arg2;
@end

