//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMComposeDefaultOptions.h"

@class TMSubmissionTerms;

@interface TMComposeSubmissionOptions : TMComposeDefaultOptions
{
    TMSubmissionTerms *_submissionTerms;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TMSubmissionTerms *submissionTerms; // @synthesize submissionTerms=_submissionTerms;
- (id)URLHandlingViewControllerWithURL:(id)arg1;
- (_Bool)canShowPopoverMediaPicker;
- (unsigned long long)composeActionsDisplayStyle;
- (_Bool)isSubmission;
- (_Bool)shouldUseCurrentlyViewingBlogByDefault;
- (_Bool)shouldUsePreviouslyPostedBlogByDefault;
- (_Bool)shouldAllowDrafts;
- (_Bool)composeFlowController:(id)arg1 shouldShowButtonForSocialNetwork:(long long)arg2;
- (id)postParameters;
- (_Bool)composeFlowControllerShouldShowContentSource:(id)arg1;
- (_Bool)composeFlowControllerShouldShowPostSettings:(id)arg1;
- (id)permittedTagNames;
- (id)permittedComposeTypes;
- (id)initWithSubmissionTerms:(id)arg1;

@end

