//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMComposeFieldTableCell.h"

@interface TMComposeVideoURLTableCell : TMComposeFieldTableCell
{
    _Bool _shouldSelectText;
}

+ (id)errorBackgroundColor;
@property(nonatomic) _Bool shouldSelectText; // @synthesize shouldSelectText=_shouldSelectText;
- (_Bool)becomeFirstResponder;
- (double)heightNeeded;
- (void)setContentStatus:(unsigned long long)arg1;

@end

