//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TMContentOffsetCalculator, UIView;

@protocol TMContentCellOffsetCalculatorDelegate <NSObject>

@optional
- (void)contentOffsetCalculator:(TMContentOffsetCalculator *)arg1 visibilityChanged:(float)arg2;
- (void)contentOffsetCalculator:(TMContentOffsetCalculator *)arg1 offsetChanged:(struct CGPoint)arg2 inView:(UIView *)arg3;
- (void)contentOffsetCalculator:(TMContentOffsetCalculator *)arg1 didEndIntersectingCellRect:(struct CGRect)arg2;
- (void)contentOffsetCalculator:(TMContentOffsetCalculator *)arg1 didBeginIntersectingCellRect:(struct CGRect)arg2;
@end

