//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TMCredentials : NSObject
{
    NSString *_email;
    NSString *_password;
}

+ (id)allCredentials;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
- (id)description;
- (id)data;
- (_Bool)save;
- (void)setupFromDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

