//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIWindow;
@protocol TMCurrentWindowSupplierDataSource;

@interface TMCurrentWindowSupplier : NSObject
{
    id <TMCurrentWindowSupplierDataSource> _dataSource;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) __weak id <TMCurrentWindowSupplierDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) UIWindow *currentWindow;

@end

