//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMCustomizeTextView.h"

@interface TMCustomizeDescriptionTextView : TMCustomizeTextView
{
    double _fontLineHeight;
}

@property(nonatomic) double fontLineHeight; // @synthesize fontLineHeight=_fontLineHeight;
- (struct CGRect)caretRectForPosition:(id)arg1;
- (void)setFont:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)titleForCustomizing;

@end

