//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMVideoPlaybackView.h"

#import "_TtP8TumblrUI11TMMediaItem_-Protocol.h"

@class AVPlayerLayer, MISSING_TYPE, _TtC8TumblrUI11TMImageView;

@interface TMDashboardVideoPlaybackView : TMVideoPlaybackView <_TtP8TumblrUI11TMMediaItem_>
{
    MISSING_TYPE *isVideo;
    MISSING_TYPE *shouldStylePlaceholder;
    MISSING_TYPE *wasPlayingBeforeBackgrounded;
    MISSING_TYPE *pausedVideoProgress;
    MISSING_TYPE *videoEventQueue;
    MISSING_TYPE *playerLayer;
    MISSING_TYPE *$__lazy_storage_$_placeholder;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 application:(id)arg2 restartWhenUnmuting:(_Bool)arg3;
- (void)audioPlayerStateDidChange:(id)arg1;
- (void)willResignActive:(id)arg1;
- (void)didBecomeActive:(id)arg1;
- (void)didMoveToSuperview;
- (void)layoutSubviews;
- (void)dealloc;
@property(nonatomic, retain) AVPlayerLayer *playerLayer; // @synthesize playerLayer;
@property(nonatomic) _Bool transitioningFromFullscreen;
- (_Bool)isTransitioningFromFullscreen;
@property(nonatomic) _Bool transitioningToFullscreen;
- (_Bool)isTransitioningToFullscreen;
@property(nonatomic) _Bool fullScreen;
- (_Bool)isFullScreen;
@property(nonatomic, readonly) _TtC8TumblrUI11TMImageView *placeholderImageView;
@property(nonatomic, readonly) _Bool isVideo; // @synthesize isVideo;
@property(nonatomic) _Bool isPanorama;

@end

