//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TMNativeAutoPlayDeterminer-Protocol.h"

@class _TtC10CoreTumblr13TMPreferences;
@protocol _TtP10CoreTumblr24TMLowPowerModeDeterminer_, _TtP10CoreTumblr25DataSavingModeDetermining_, _TtP5Utils22ReachabilityDeterminer_;

@interface TMDefaultNativeAutoPlayDeterminer : NSObject <TMNativeAutoPlayDeterminer>
{
    id <_TtP5Utils22ReachabilityDeterminer_> _reachabilityDeterminer;
    id <_TtP10CoreTumblr24TMLowPowerModeDeterminer_> _lowPowerModeDeterminer;
    id <_TtP10CoreTumblr25DataSavingModeDetermining_> _dataSavingModeDeterminer;
    _TtC10CoreTumblr13TMPreferences *_preferences;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _TtC10CoreTumblr13TMPreferences *preferences; // @synthesize preferences=_preferences;
@property(readonly, nonatomic) id <_TtP10CoreTumblr25DataSavingModeDetermining_> dataSavingModeDeterminer; // @synthesize dataSavingModeDeterminer=_dataSavingModeDeterminer;
@property(readonly, nonatomic) id <_TtP10CoreTumblr24TMLowPowerModeDeterminer_> lowPowerModeDeterminer; // @synthesize lowPowerModeDeterminer=_lowPowerModeDeterminer;
@property(readonly, nonatomic) id <_TtP5Utils22ReachabilityDeterminer_> reachabilityDeterminer; // @synthesize reachabilityDeterminer=_reachabilityDeterminer;
- (void)removeReachabilityObserver:(id)arg1;
- (void)addReachabilityObserver:(id)arg1;
- (_Bool)meetsAutoPlayHardwareAndNetworkRequirementsForVideoAutoPlayAttributes:(id)arg1;
- (_Bool)shouldAutoPlayWithVideoAutoPlayAttributes:(id)arg1;
- (id)initWithReachabilityDeterminer:(id)arg1 lowPowerModeDeterminer:(id)arg2 preferences:(id)arg3;

@end

