//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class TMBurstView, UIImageView, UILabel;

@interface TMEmptyDashboardView : UIView
{
    _Bool _hasAppeared;
    double _navigationBarHeight;
    UIImageView *_icon;
    TMBurstView *_burst;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
}

+ (double)labelLeftRightPadding;
+ (double)detailFontSize;
+ (double)headlineFontSize;
- (void).cxx_destruct;
@property(nonatomic) _Bool hasAppeared; // @synthesize hasAppeared=_hasAppeared;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) TMBurstView *burst; // @synthesize burst=_burst;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(nonatomic) double navigationBarHeight; // @synthesize navigationBarHeight=_navigationBarHeight;
- (void)configureWithTitleText:(id)arg1 detailText:(id)arg2 hideIcon:(_Bool)arg3;
- (void)willMoveToWindow:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)outroAnimation;
- (void)introAnimation;

@end

