//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TMKeyboardHeightObserver : NSObject
{
    double _cachedKeyboardHeight;
}

@property(nonatomic) double cachedKeyboardHeight; // @synthesize cachedKeyboardHeight=_cachedKeyboardHeight;
- (void)keyboardAppearanceChanged:(id)arg1;
- (id)init;

@end

