//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TMLineSeparatorBorderApplier : NSObject
{
}

+ (void)addHorizontalSeparatorSubviewToView:(id)arg1 xOrigin:(double)arg2 autoresizingMask:(unsigned long long)arg3 color:(id)arg4;
+ (void)addVerticalSeparatorSubviewToView:(id)arg1 yOrigin:(double)arg2 autoresizingMask:(unsigned long long)arg3 color:(id)arg4;
+ (void)applyBorderToView:(id)arg1 atEdges:(unsigned long long)arg2 borderColor:(id)arg3;
+ (void)applyBorderToView:(id)arg1 atEdges:(unsigned long long)arg2;

@end

