//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TMScreenIdentifying-Protocol.h"

@class NSNumber, NSString;

@interface TMLikeParameters : NSObject <TMScreenIdentifying>
{
    _Bool _like;
    int _advertisementType;
    NSString *_screenIdentifier;
    NSString *_postID;
    NSString *_reblogKey;
    NSString *_placementIdentifier;
    NSNumber *_carouselIndex;
    NSString *_targetPostBlogName;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *targetPostBlogName; // @synthesize targetPostBlogName=_targetPostBlogName;
@property(readonly, copy, nonatomic) NSNumber *carouselIndex; // @synthesize carouselIndex=_carouselIndex;
@property(copy, nonatomic) NSString *placementIdentifier; // @synthesize placementIdentifier=_placementIdentifier;
@property(nonatomic) int advertisementType; // @synthesize advertisementType=_advertisementType;
@property(nonatomic) _Bool like; // @synthesize like=_like;
@property(copy, nonatomic) NSString *reblogKey; // @synthesize reblogKey=_reblogKey;
@property(copy, nonatomic) NSString *postID; // @synthesize postID=_postID;
@property(copy, nonatomic) NSString *screenIdentifier; // @synthesize screenIdentifier=_screenIdentifier;
- (id)initWithPostID:(id)arg1 reblogKey:(id)arg2 like:(_Bool)arg3 advertisementType:(int)arg4 placementIdentifier:(id)arg5 screenIdentifier:(id)arg6 carouselIndex:(id)arg7 targetPostBlogName:(id)arg8;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

