//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMBannerView.h"

@class UIButton, UIImageView, UILabel;

@interface TMMessageBannerView : TMBannerView
{
    _Bool _overridesTheming;
    unsigned long long _layout;
    UILabel *_label;
    UIImageView *_disclosureImageView;
    UIButton *_accessoryButton;
    CDUnknownBlockType _accessoryTappedBlock;
}

+ (id)yellowBannerViewWithMessage:(id)arg1;
+ (id)errorBannerViewWithMessage:(id)arg1;
+ (id)successBannerViewWithMessage:(id)arg1 duration:(double)arg2;
+ (id)successBannerViewWithMessage:(id)arg1;
+ (double)labelFontSize;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType accessoryTappedBlock; // @synthesize accessoryTappedBlock=_accessoryTappedBlock;
@property(nonatomic) _Bool overridesTheming; // @synthesize overridesTheming=_overridesTheming;
@property(retain, nonatomic) UIButton *accessoryButton; // @synthesize accessoryButton=_accessoryButton;
@property(retain, nonatomic) UIImageView *disclosureImageView; // @synthesize disclosureImageView=_disclosureImageView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) unsigned long long layout; // @synthesize layout=_layout;
- (void)tappedAccessoryButton;
- (void)updateTheming:(id)arg1;
- (void)setBarTintColor:(id)arg1 tintColor:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 bannerVisibleDuration:(double)arg2;
- (id)initWithMessage:(id)arg1 overridesTheming:(_Bool)arg2 layout:(unsigned long long)arg3 accessoryTappedBlock:(CDUnknownBlockType)arg4 bannerVisibleDuration:(double)arg5;

@end

