//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURLSessionTask, TMAPIClient;

@interface TMMentionsDataSource : NSObject
{
    _Bool _reloading;
    NSArray *_blogs;
    TMAPIClient *_APIClient;
    NSURLSessionTask *_task;
    NSString *_searchString;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
@property(readonly, nonatomic) TMAPIClient *APIClient; // @synthesize APIClient=_APIClient;
@property(readonly, nonatomic, getter=isReloading) _Bool reloading; // @synthesize reloading=_reloading;
@property(readonly, nonatomic) NSArray *blogs; // @synthesize blogs=_blogs;
- (void)cancel;
- (void)reloadDataWithString:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithAPIClient:(id)arg1;

@end

