//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIPercentDrivenInteractiveTransition.h>

#import "MediaGestureRecognizerCoordinatingDelegate-Protocol.h"
#import "TMScreenIdentifying-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIViewControllerAnimatedTransitioning-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSArray, NSString, TMClippingView, UIView, UIViewController, _TtC6Tumblr21LightBoxEventProvider, _TtC6Tumblr23MediaGestureCoordinator, _TtC6Tumblr28LightBoxPostControlViewModel;
@protocol TMMediaTransitionControllerDelegate, TMMediaTransitioning, UIViewControllerContextTransitioning, _TtP6Tumblr16LightBoxDelegate_;

@interface TMMediaTransitionController : UIPercentDrivenInteractiveTransition <UIViewControllerTransitioningDelegate, UIGestureRecognizerDelegate, TMScreenIdentifying, UIViewControllerAnimatedTransitioning, MediaGestureRecognizerCoordinatingDelegate>
{
    _Bool _transitionGesturesEnabled;
    _Bool _presenting;
    _Bool _videoMedia;
    _Bool _interactive;
    _Bool _respondsToDeviceMotion;
    _Bool _postControlsEnabled;
    NSString *_screenIdentifier;
    UIViewController<TMMediaTransitioning> *_mediaController;
    id <TMMediaTransitionControllerDelegate> _delegate;
    NSArray *_mediaViews;
    NSArray *_visibleMediaViews;
    UIView *_gestureView;
    UIView *_mediaTransitionView;
    UIView *_mediaSuperView;
    TMClippingView *_clippingView;
    double _previousCornerRadius;
    double _pinchGestureScale;
    id <UIViewControllerContextTransitioning> _transitionContext;
    _TtC6Tumblr23MediaGestureCoordinator *_gestureCoordinator;
    _TtC6Tumblr23MediaGestureCoordinator *_fullScreenGestureCoordinator;
    _TtC6Tumblr28LightBoxPostControlViewModel *_lightBoxPostControlViewModel;
    id <_TtP6Tumblr16LightBoxDelegate_> _lightBoxDelegate;
    _TtC6Tumblr21LightBoxEventProvider *_lightBoxEventProvider;
    struct CGPoint _previousPinchLocation;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _TtC6Tumblr21LightBoxEventProvider *lightBoxEventProvider; // @synthesize lightBoxEventProvider=_lightBoxEventProvider;
@property(nonatomic) __weak id <_TtP6Tumblr16LightBoxDelegate_> lightBoxDelegate; // @synthesize lightBoxDelegate=_lightBoxDelegate;
@property(nonatomic) _Bool postControlsEnabled; // @synthesize postControlsEnabled=_postControlsEnabled;
@property(retain, nonatomic) _TtC6Tumblr28LightBoxPostControlViewModel *lightBoxPostControlViewModel; // @synthesize lightBoxPostControlViewModel=_lightBoxPostControlViewModel;
@property(nonatomic) _Bool respondsToDeviceMotion; // @synthesize respondsToDeviceMotion=_respondsToDeviceMotion;
@property(retain, nonatomic) _TtC6Tumblr23MediaGestureCoordinator *fullScreenGestureCoordinator; // @synthesize fullScreenGestureCoordinator=_fullScreenGestureCoordinator;
@property(retain, nonatomic) _TtC6Tumblr23MediaGestureCoordinator *gestureCoordinator; // @synthesize gestureCoordinator=_gestureCoordinator;
@property(nonatomic) __weak id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(nonatomic) double pinchGestureScale; // @synthesize pinchGestureScale=_pinchGestureScale;
@property(nonatomic) double previousCornerRadius; // @synthesize previousCornerRadius=_previousCornerRadius;
@property(nonatomic) struct CGPoint previousPinchLocation; // @synthesize previousPinchLocation=_previousPinchLocation;
@property(retain, nonatomic) TMClippingView *clippingView; // @synthesize clippingView=_clippingView;
@property(retain, nonatomic) UIView *mediaSuperView; // @synthesize mediaSuperView=_mediaSuperView;
@property(retain, nonatomic) UIView *mediaTransitionView; // @synthesize mediaTransitionView=_mediaTransitionView;
@property(nonatomic, getter=isInteractive) _Bool interactive; // @synthesize interactive=_interactive;
@property(nonatomic) __weak UIView *gestureView; // @synthesize gestureView=_gestureView;
@property(nonatomic, getter=isVideoMedia) _Bool videoMedia; // @synthesize videoMedia=_videoMedia;
@property(copy, nonatomic) NSArray *visibleMediaViews; // @synthesize visibleMediaViews=_visibleMediaViews;
@property(retain, nonatomic) NSArray *mediaViews; // @synthesize mediaViews=_mediaViews;
@property(nonatomic) __weak id <TMMediaTransitionControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isPresenting) _Bool presenting; // @synthesize presenting=_presenting;
@property(nonatomic) _Bool transitionGesturesEnabled; // @synthesize transitionGesturesEnabled=_transitionGesturesEnabled;
@property(readonly, nonatomic) __weak UIViewController<TMMediaTransitioning> *mediaController; // @synthesize mediaController=_mediaController;
@property(copy, nonatomic) NSString *screenIdentifier;
- (id)currentlyVisibleMediaViews;
- (void)didDismissWithGestureType:(unsigned long long)arg1;
- (void)presentPostControlLightBoxWithRootViewController:(id)arg1 mediaViewController:(id)arg2;
- (_Bool)gestureDismissalAllowed;
- (void)didLongPress;
- (void)panEnded:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2 completion:(CDUnknownBlockType)arg3;
- (void)panChanged:(struct CGPoint)arg1;
- (void)panBegan;
- (void)pinchEnded;
- (void)pinchChanged:(struct CGPoint)arg1 scale:(double)arg2;
- (void)pinchBegan;
- (void)didTap:(id)arg1 location:(struct CGPoint)arg2;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)interactionControllerForPresentation:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)animationEnded:(_Bool)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (void)tappedMediaView:(id)arg1 location:(struct CGPoint)arg2;
- (void)tappedFullscreenMediaView;
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
- (_Bool)isSafeToDismiss;
- (_Bool)isSafeToPresent;
- (_Bool)isPresented;
- (void)setMediaController:(id)arg1;
- (void)applyClippingInsets;
- (void)cancelTransition;
- (void)finishTransitionWithGesture:(id)arg1;
- (void)endGestureWithGesture:(id)arg1 transition:(_Bool)arg2;
- (void)beginDismissal;
- (void)beginPresentation:(id)arg1;
- (void)applyFullscreenGestureRecognizer;
- (void)setupWithPostControlsEnabled:(_Bool)arg1 lightBoxDelegate:(id)arg2 lightBoxPostControlViewModel:(id)arg3;
- (id)initWithMediaController:(id)arg1;
- (id)initWithVideoPlaybackLightboxableView:(id)arg1 gestureView:(id)arg2 respondsToDeviceMotion:(_Bool)arg3;
- (id)initWithVideoView:(id)arg1 gestureView:(id)arg2 respondsToDeviceMotion:(_Bool)arg3;
- (id)initWithMediaViews:(id)arg1 gestureView:(id)arg2 respondsToDeviceMotion:(_Bool)arg3;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

