//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIColor;

@protocol TMNavigationBarStyleDefining
@property(nonatomic, readonly) UIColor *navigationBarBadgeBackgroundColor;
@property(nonatomic, readonly) UIColor *navigationBarBackgroundTintColor;
@property(nonatomic, readonly) UIColor *navigationBarTintColor;
@property(nonatomic, readonly) UIColor *navigationBarSubtitleColor;
@property(nonatomic, readonly) UIColor *navigationBarTitleColor;
@property(nonatomic, readonly) long long navigationBarStyle;
@property(nonatomic, readonly) long long navigationBarAppearance;
@end

