//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSAttributedString, NSString, _TtC11TumblrTheme14AppColorScheme, _TtC8TumblrUI13PostNoteStyle;

@interface TMNoteViewModel : NSObject
{
    struct __CTFrame *_labelFrameRef;
    struct CGSize _labelFrameSize;
    struct __CTFrame *_blockquoteFrameRef;
    struct CGSize _blockquoteFrameSize;
    _Bool _following;
    _Bool _containsBlockquote;
    _Bool _isFromNSFWBlog;
    int _noteType;
    struct __CTFrame *_frameRef;
    NSAttributedString *_labelAttributedString;
    NSAttributedString *_blockquoteAttributedString;
    NSString *_reblogParentBlogName;
    _TtC8TumblrUI13PostNoteStyle *_postNoteStyle;
    _TtC11TumblrTheme14AppColorScheme *_appColorScheme;
    double _maximumWidth;
    unsigned long long _noteStyle;
    NSArray *_boldTextRanges;
    NSArray *_lightTextRanges;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *lightTextRanges; // @synthesize lightTextRanges=_lightTextRanges;
@property(retain, nonatomic) NSArray *boldTextRanges; // @synthesize boldTextRanges=_boldTextRanges;
@property(nonatomic) int noteType; // @synthesize noteType=_noteType;
@property(nonatomic) unsigned long long noteStyle; // @synthesize noteStyle=_noteStyle;
@property(nonatomic) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(retain, nonatomic) _TtC11TumblrTheme14AppColorScheme *appColorScheme; // @synthesize appColorScheme=_appColorScheme;
@property(readonly, nonatomic) _TtC8TumblrUI13PostNoteStyle *postNoteStyle; // @synthesize postNoteStyle=_postNoteStyle;
@property(nonatomic) _Bool isFromNSFWBlog; // @synthesize isFromNSFWBlog=_isFromNSFWBlog;
@property(nonatomic) _Bool containsBlockquote; // @synthesize containsBlockquote=_containsBlockquote;
@property(readonly, copy, nonatomic) NSString *reblogParentBlogName; // @synthesize reblogParentBlogName=_reblogParentBlogName;
@property(nonatomic) _Bool following; // @synthesize following=_following;
@property(retain, nonatomic) NSAttributedString *blockquoteAttributedString; // @synthesize blockquoteAttributedString=_blockquoteAttributedString;
@property(retain, nonatomic) NSAttributedString *labelAttributedString; // @synthesize labelAttributedString=_labelAttributedString;
@property(readonly, nonatomic) struct __CTFrame *frameRef; // @synthesize frameRef=_frameRef;
- (void)_buildAttributedStringWithNote:(id)arg1;
- (id)noteDescription;
- (void)_buildNoteFrame;
- (void)_applyTextAttributes;
- (double)_textAreaWidth;
@property(readonly, nonatomic) struct CGSize frameSize;
- (void)dealloc;
- (id)initWithNote:(id)arg1 style:(id)arg2 maximumWidth:(double)arg3 appColorScheme:(id)arg4;

@end

