//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMDictionaryUpdatableManagedObject.h"

@class NSDate, NSString, TMPost, TMUser;

@interface TMNote : TMDictionaryUpdatableManagedObject
{
}

- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;
- (id)initWithContext:(id)arg1 dictionary:(id)arg2;
- (void)updateWithDictionary:(id)arg1;
@property(nonatomic, readonly) _Bool isBlogCensored;

// Remaining properties
@property(nonatomic) _Bool blogIsNSFW; // @dynamic blogIsNSFW;
@property(nonatomic, copy) NSString *blogName; // @dynamic blogName;
@property(nonatomic, copy) NSString *blogUUID; // @dynamic blogUUID;
@property(nonatomic, copy) NSDate *date; // @dynamic date;
@property(nonatomic) _Bool following; // @dynamic following;
@property(nonatomic, copy) NSString *noteID; // @dynamic noteID;
@property(nonatomic) int noteType; // @dynamic noteType;
@property(nonatomic, retain) TMPost *post; // @dynamic post;
@property(nonatomic, copy) NSString *postID; // @dynamic postID;
@property(nonatomic, copy) NSString *reblogParentBlogName; // @dynamic reblogParentBlogName;
@property(nonatomic, retain) TMUser *user; // @dynamic user;

@end

