//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMNotificationIconView.h"

@interface TMNotificationPostTypeIconView : TMNotificationIconView
{
}

- (void)updateImageViewWithURL:(id)arg1;
- (void)updateImageViewWithImage:(id)arg1;
- (void)updateWithActivityItemType:(long long)arg1 targetBlogName:(id)arg2 targetBlogIsPrivate:(_Bool)arg3 targetPostType:(int)arg4 mediaURL:(id)arg5;
- (void)updateWithActivityItemType:(long long)arg1 targetBlog:(id)arg2 targetPostType:(int)arg3 mediaURL:(id)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

