//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface TMOnboardingNavigationWrapperViewController : UIViewController
{
    UIViewController *_controller;
}

+ (id)wrapperViewControllerWithController:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIViewController *controller; // @synthesize controller=_controller;
- (_Bool)wantsOpaqueNavigationBar;
- (void)onboardingNavigationController:(id)arg1 willMoveViewControllerOnScreen:(_Bool)arg2;
- (void)onboardingNavigationControllerWillPop:(id)arg1;
- (void)onboardingNavigationControllerWillPush:(id)arg1;
- (_Bool)extendedLayoutIncludesOpaqueBars;
- (id)toolbarItems;
- (id)navigationItem;
- (void)setupChildViewController;
- (void)viewDidLoad;
- (id)initWithController:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

