//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TMPostActionValue : NSObject
{
    _Bool _animate;
    NSString *_title;
    NSString *_state;
    NSString *_backgroundColor;
    NSString *_borderColor;
    NSString *_titleColor;
    NSString *_iOSURL;
    NSString *_URL;
    NSString *_price;
    NSString *_type;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool animate; // @synthesize animate=_animate;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *price; // @synthesize price=_price;
@property(readonly, copy, nonatomic) NSString *URL; // @synthesize URL=_URL;
@property(readonly, copy, nonatomic) NSString *iOSURL; // @synthesize iOSURL=_iOSURL;
@property(readonly, copy, nonatomic) NSString *titleColor; // @synthesize titleColor=_titleColor;
@property(readonly, copy, nonatomic) NSString *borderColor; // @synthesize borderColor=_borderColor;
@property(readonly, copy, nonatomic) NSString *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, copy, nonatomic) NSString *state; // @synthesize state=_state;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (unsigned long long)hash;
- (id)initWithPostAction:(id)arg1;
- (id)init;

@end

