//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TMPostActionButtonsContainerView, UIButton, _TtC6Tumblr20NativeAppURLLauncher;

@protocol TMPostActionButtonsContainerViewDelegate <NSObject>
- (void)actionButtonsContainerView:(TMPostActionButtonsContainerView *)arg1 didSelectButton:(UIButton *)arg2 withURL:(_TtC6Tumblr20NativeAppURLLauncher *)arg3;
@end

