//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMPostCellResponder.h"

@interface TMPostCellResponder (Tumblr7)
- (void)likePost:(id)arg1 carouselIndex:(id)arg2;
- (void)fastReblogPost:(id)arg1 fromPoint:(struct CGPoint)arg2 fromKeyCommand:(_Bool)arg3 fromControl:(id)arg4;
- (void)dismissPopovers;
@end

