//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIViewController, _TtC10LinkRouter10LinkRouter, _TtC6Tumblr19ClientSideAdSources;
@protocol TMSession, TMTumblrCoreDataController, _TtP9Analytics14EventBuffering_;

@interface TMPostViewControllerProvider : NSObject
{
    NSString *_blogName;
    NSString *_blogUUID;
    id <TMSession> _session;
    id <TMTumblrCoreDataController> _coreDataController;
    id <_TtP9Analytics14EventBuffering_> _analyticsBuffer;
    _TtC10LinkRouter10LinkRouter *_linkRouter;
    _TtC6Tumblr19ClientSideAdSources *_clientSideAdSources;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _TtC6Tumblr19ClientSideAdSources *clientSideAdSources; // @synthesize clientSideAdSources=_clientSideAdSources;
@property(readonly, nonatomic) _TtC10LinkRouter10LinkRouter *linkRouter; // @synthesize linkRouter=_linkRouter;
@property(readonly, nonatomic) id <_TtP9Analytics14EventBuffering_> analyticsBuffer; // @synthesize analyticsBuffer=_analyticsBuffer;
@property(readonly, nonatomic) id <TMTumblrCoreDataController> coreDataController; // @synthesize coreDataController=_coreDataController;
@property(readonly, nonatomic) id <TMSession> session; // @synthesize session=_session;
@property(readonly, copy, nonatomic) NSString *blogUUID; // @synthesize blogUUID=_blogUUID;
@property(readonly, copy, nonatomic) NSString *blogName; // @synthesize blogName=_blogName;
@property(readonly, nonatomic) UIViewController *appealViewController;
@property(readonly, nonatomic) UIViewController *draftsViewController;
@property(readonly, nonatomic) UIViewController *queueViewController;
- (id)initWithBlogName:(id)arg1 blogUUID:(id)arg2 coreDataController:(id)arg3 analyticsBuffer:(id)arg4 linkRouter:(id)arg5 session:(id)arg6 clientSideAdSources:(id)arg7;

@end

