//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMVerticalStackView.h"

#import "_TtP11TumblrTheme9TMTheming_-Protocol.h"

@class NSDictionary, TMPostActionButton, _TtC11TumblrTheme7TMTheme, _TtC6Tumblr20NativeAppURLLauncher;
@protocol TMPostActionButtonsContainerViewDelegate;

@interface TMPostActionButtonsContainerView : TMVerticalStackView <_TtP11TumblrTheme9TMTheming_>
{
    _Bool _animateActionButton;
    id <TMPostActionButtonsContainerViewDelegate> _delegate;
    NSDictionary *_buttonValuesToAppURLs;
    _TtC11TumblrTheme7TMTheme *_currentTheme;
    unsigned long long _postActionsViewModelHash;
    TMPostActionButton *_actionButton;
    _TtC6Tumblr20NativeAppURLLauncher *_nativeURLLauncher;
}

+ (double)heightForNumberOfActions:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(nonatomic) _Bool animateActionButton; // @synthesize animateActionButton=_animateActionButton;
@property(retain, nonatomic) _TtC6Tumblr20NativeAppURLLauncher *nativeURLLauncher; // @synthesize nativeURLLauncher=_nativeURLLauncher;
@property(retain, nonatomic) TMPostActionButton *actionButton; // @synthesize actionButton=_actionButton;
@property(nonatomic) unsigned long long postActionsViewModelHash; // @synthesize postActionsViewModelHash=_postActionsViewModelHash;
@property(retain, nonatomic) _TtC11TumblrTheme7TMTheme *currentTheme; // @synthesize currentTheme=_currentTheme;
@property(retain, nonatomic) NSDictionary *buttonValuesToAppURLs; // @synthesize buttonValuesToAppURLs=_buttonValuesToAppURLs;
@property(nonatomic) __weak id <TMPostActionButtonsContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)updateTheming:(id)arg1;
- (void)actionButtonTapped:(id)arg1;
- (void)updateForOffset:(double)arg1 viewHeight:(double)arg2;
- (void)contentOffsetChangedInView:(id)arg1;
- (void)setupWithPostActionsViewModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

