//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol TMPushNotification <NSObject>
- (id)initWithNotificationDictionary:(NSDictionary *)arg1;
@property(nonatomic, readonly) NSDictionary *loggingData;
@property(nonatomic, readonly) NSString *source;
@property(nonatomic, readonly) NSString *type;
@property(nonatomic, readonly) _Bool isSilentPush;
@property(nonatomic, readonly) NSDictionary *notificationDictionary;
@property(nonatomic, readonly) NSString *localizedMessage;
@end

