//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@interface TMRange : NSObject <NSCopying, NSSecureCoding>
{
    long long _start;
    long long _length;
}

+ (_Bool)supportsSecureCoding;
+ (id)rangeWithStart:(long long)arg1 length:(long long)arg2;
+ (id)rangeWithRange:(struct _NSRange)arg1;
@property(nonatomic) long long length; // @synthesize length=_length;
@property(nonatomic) long long start; // @synthesize start=_start;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (struct _NSRange)toNSRange;
- (id)init;
- (id)initWithStart:(long long)arg1 length:(long long)arg2;
- (id)initWithRange:(struct _NSRange)arg1;

@end

