//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol TMRequest;

@protocol TMRequestTransformer
- (id <TMRequest>)transformRequest:(id <TMRequest>)arg1;
@end

