//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMTimelineObject.h"

@class MISSING_TYPE, NSString;

@interface TMTakeoverBanner : TMTimelineObject
{
    MISSING_TYPE *dictionary;
}

- (void).cxx_destruct;
- (void).cxx_construct;
- (id)initWithEntity:(id)arg1 insertIntoManagedObjectContext:(id)arg2;
- (id)initWithContext:(id)arg1 dictionary:(id)arg2;
- (void)updateWithDictionary:(id)arg1;
@property(nonatomic, readonly) NSString *sponsoredBadgeURL;
@property(nonatomic, readonly) NSString *impressionIdentifier;
@property(nonatomic, readonly) int advertisementType;
@property(nonatomic) int type;
@property(nonatomic, readonly) _Bool showsDecoration;

// Remaining properties
@property(nonatomic, copy) NSString *iconURL; // @dynamic iconURL;
@property(nonatomic) _Bool live; // @dynamic live;
@property(nonatomic, copy) NSString *placementIdentifier; // @dynamic placementIdentifier;
@property(nonatomic, copy) NSString *takeoverTerm; // @dynamic takeoverTerm;
@property(nonatomic) long long takeoverType; // @dynamic takeoverType;
@property(nonatomic, copy) NSString *text; // @dynamic text;
@property(nonatomic, copy) NSString *title; // @dynamic title;

@end

