//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/NSLayoutManager.h>

@class TMAttributedTextView;

@interface TMTextLayoutManager : NSLayoutManager
{
    TMAttributedTextView *_textView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak TMAttributedTextView *textView; // @synthesize textView=_textView;
- (void)drawCiteAtPoint:(struct CGPoint)arg1 withFont:(id)arg2 inContext:(struct CGContext *)arg3;
- (void)drawUnorderedListAtPoint:(struct CGPoint)arg1 withFont:(id)arg2 inContext:(struct CGContext *)arg3;
- (void)drawOrderedListInAttributes:(id)arg1 atPoint:(struct CGPoint)arg2 withFont:(id)arg3 inContext:(struct CGContext *)arg4;
- (void)drawBlockquotesInAttributes:(id)arg1 atPoint:(struct CGPoint)arg2 withFont:(id)arg3 inContext:(struct CGContext *)arg4;
- (void)drawHorizontalRuleAtPoint:(struct CGPoint)arg1 withAttributes:(id)arg2 inContext:(struct CGContext *)arg3;
- (void)showCGGlyphs:(const unsigned short *)arg1 positions:(const struct CGPoint *)arg2 count:(unsigned long long)arg3 font:(id)arg4 matrix:(struct CGAffineTransform)arg5 attributes:(id)arg6 inContext:(struct CGContext *)arg7;

@end

