//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UITraitCollection, _TtC22TimelineViewManagement21PostViewConfiguration;
@protocol _TtP9Timelines14TimelineObject_;

@protocol TMTimelineObjectHeightCalculating
- (double)heightForTimelineObject:(id <_TtP9Timelines14TimelineObject_>)arg1 previousTimelineObject:(id <_TtP9Timelines14TimelineObject_>)arg2 width:(double)arg3 traitCollection:(UITraitCollection *)arg4 postViewConfiguration:(_TtC22TimelineViewManagement21PostViewConfiguration *)arg5;
@end

