//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMTransitionAnimator.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, TMToastViewController;

@interface TMToastTransitionController : TMTransitionAnimator <UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate>
{
    double _keyboardHeight;
    TMToastViewController *_toastViewController;
}

- (void).cxx_destruct;
@property(nonatomic) __weak TMToastViewController *toastViewController; // @synthesize toastViewController=_toastViewController;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)animateTransition:(id)arg1;
- (double)toastYOriginForPresentationStyle:(long long)arg1 transitionContext:(id)arg2;
- (struct CGAffineTransform)transformForToastPresentationStyle:(long long)arg1;
- (double)dismissalDuration;
- (double)presentationDuration;
- (id)initWithToastViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

