//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMPostDeliverer-Protocol.h"

@protocol TMTrackingPostDeliverer <TMPostDeliverer>
@property(copy, nonatomic) CDUnknownBlockType requestEstimatedProgressDidUpdateBlock;
@property(copy, nonatomic) CDUnknownBlockType requestDidFinishBlock;
@property(copy, nonatomic) CDUnknownBlockType requestWillBeSentBlock;
- (void)cancelAllRequests;
@end

