//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class TMUnknownFigureButton, UIButton;

@interface TMUnknownEmbedFigureView : UIView
{
    _Bool _flushWithSuperViewX;
    TMUnknownFigureButton *_unknownFigureButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TMUnknownFigureButton *unknownFigureButton; // @synthesize unknownFigureButton=_unknownFigureButton;
@property(nonatomic, getter=isFlushWithSuperViewX) _Bool flushWithSuperViewX; // @synthesize flushWithSuperViewX=_flushWithSuperViewX;
@property(readonly, nonatomic) UIButton *button;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithUnknownCache:(id)arg1;

@end

