//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TMURLEncoding : NSObject
{
}

+ (void)encodeObject:(id)arg1 withKey:(id)arg2 andSubKey:(id)arg3 intoArray:(id)arg4;
+ (id)formEncodedDictionary:(id)arg1;
+ (id)encodedDictionary:(id)arg1;
+ (id)formEncodedString:(id)arg1;
+ (id)encodedString:(id)arg1;

@end

