//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMFigureAsset.h"

@class NSNumber, NSString;

@interface TMVideoFigureAsset : TMFigureAsset
{
}

- (void)updateWithDictionary:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSNumber *thumbnailHeight; // @dynamic thumbnailHeight;
@property(copy, nonatomic) NSString *thumbnailURL; // @dynamic thumbnailURL;
@property(retain, nonatomic) NSNumber *thumbnailWidth; // @dynamic thumbnailWidth;
@property(retain, nonatomic) NSString *videoURL; // @dynamic videoURL;

@end

