//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class TMVideoMuteButton, TMVideoPlayPauseButton, UIActivityIndicatorView, UIButton;

@interface TMVideoControlView : UIView
{
    _Bool _showsLoadingIndicator;
    long long _style;
    UIActivityIndicatorView *_activityIndicator;
    TMVideoMuteButton *_muteButton;
    TMVideoPlayPauseButton *_playPauseButton;
    UIButton *_currentButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *currentButton; // @synthesize currentButton=_currentButton;
@property(retain, nonatomic) TMVideoPlayPauseButton *playPauseButton; // @synthesize playPauseButton=_playPauseButton;
@property(retain, nonatomic) TMVideoMuteButton *muteButton; // @synthesize muteButton=_muteButton;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) _Bool showsLoadingIndicator; // @synthesize showsLoadingIndicator=_showsLoadingIndicator;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void)showCurrentButton;
- (void)showActivityIndicator;
- (void)setShowsLoadingIndicator:(_Bool)arg1 animated:(_Bool)arg2;
- (struct CGSize)playPauseButtonSize;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

