//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TMPostParameters.h"

@class NSString;

@interface TMVideoPostParameters : TMPostParameters
{
    NSString *_contentType;
    NSString *_filePath;
    NSString *_fileName;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
- (id)init;
- (void)fillWithPostValues:(id)arg1;
- (id)dictionaryRepresentation;
- (id)requestWithRequestFactory:(id)arg1;

@end

