//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface UIImageView (IconView)
- (_Bool)fbad_containsImage:(id)arg1;
- (void)fbad_setIcon:(id)arg1 completion:(CDUnknownBlockType)arg2;
@end

