//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface UIImageView (HighlightedWebCache)
- (void)sd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2 context:(id)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5;
- (void)sd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2 progress:(CDUnknownBlockType)arg3 completed:(CDUnknownBlockType)arg4;
- (void)sd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2 completed:(CDUnknownBlockType)arg3;
- (void)sd_setHighlightedImageWithURL:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (void)sd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2 context:(id)arg3;
- (void)sd_setHighlightedImageWithURL:(id)arg1 options:(unsigned long long)arg2;
- (void)sd_setHighlightedImageWithURL:(id)arg1;
@end

