//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (ExploreUI)
- (double)heightRequired:(double)arg1;
- (void)resizeAttributedStringToFitLabelInBounds:(struct CGRect)arg1 minimumFontSize:(double)arg2 fontPointSizeStep:(unsigned long long)arg3;
@end

