//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (TMSlideTransitions)
- (void)setText:(id)arg1 animated:(_Bool)arg2 duration:(double)arg3 delay:(double)arg4 withSlideTransitionDirection:(long long)arg5 completion:(CDUnknownBlockType)arg6;
- (void)setText:(id)arg1 animated:(_Bool)arg2 duration:(double)arg3 withSlideTransitionDirection:(long long)arg4;
@end

