//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UINavigationBar.h>

@class UIView;

@interface UINavigationBar (Orangina)
+ (double)defaultHeight;
@property(readonly, nonatomic) UIView *barBackgroundView;
@property(readonly, nonatomic) UIView *lineSeparator;
@end

