//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (Animations)
- (void)fadeAndFlyOutWithDuration:(double)arg1 delay:(double)arg2;
- (void)fadeAndFlyInWithDuration:(double)arg1 delay:(double)arg2;
@end

