//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface VASTCreatives : NSObject
{
    NSMutableArray *_creative;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *creative; // @synthesize creative=_creative;
- (id)description;
- (id)init;

@end

