//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VDMSAnalyticsEvent.h"

@class NSString;

@interface VDMSAnalyticsEventUserChangedCaptionsLanguage : VDMSAnalyticsEvent
{
    NSString *_languageTag;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *languageTag; // @synthesize languageTag=_languageTag;

@end

