//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL, VDMSVideoStreamMetadata;

@interface VDMSStream : NSObject
{
    NSURL *_url;
    NSString *_contentType;
    VDMSVideoStreamMetadata *_videoMetadata;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) VDMSVideoStreamMetadata *videoMetadata; // @synthesize videoMetadata=_videoMetadata;
@property(readonly, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
- (id)initWithBuilder:(id)arg1;

@end

