//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface VDMSMetadata : NSObject
{
    NSURL *_posterUrl;
    NSString *_title;
    NSString *_videoDescription;
    double _duration;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) NSString *videoDescription; // @synthesize videoDescription=_videoDescription;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSURL *posterUrl; // @synthesize posterUrl=_posterUrl;
- (id)initWithBuilder:(id)arg1;

@end

