//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface VDMSBreakBuilder : NSObject
{
    long long _type;
    double _startPosition;
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) double startPosition; // @synthesize startPosition=_startPosition;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

