//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class VDMSInteractionConfig, VDMSSource;

@interface VDMSAdBreakItemBuilder : NSObject
{
    _Bool _inStream;
    VDMSSource *_source;
    double _duration;
    VDMSInteractionConfig *_interactionConfig;
}

- (void).cxx_destruct;
@property(retain, nonatomic) VDMSInteractionConfig *interactionConfig; // @synthesize interactionConfig=_interactionConfig;
@property(nonatomic) _Bool inStream; // @synthesize inStream=_inStream;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) VDMSSource *source; // @synthesize source=_source;

@end

