//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YAActor.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSDictionary, NSMutableArray, NSString, YI13NLocationData;

@interface YI13NLocationDataProvider : YAActor <CLLocationManagerDelegate>
{
    NSMutableArray *_observerArray;
    YI13NLocationData *_locationData;
    CLLocationManager *_locationManager;
    NSDictionary *_configuration;
    Class _CLLocationManagerClass;
}

+ (void)wipe;
+ (id)sharedInstance;
+ (void)setSharedInstance:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) Class CLLocationManagerClass; // @synthesize CLLocationManagerClass=_CLLocationManagerClass;
@property(retain, nonatomic) NSDictionary *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) YI13NLocationData *locationData; // @synthesize locationData=_locationData;
@property(retain, nonatomic) NSMutableArray *observerArray; // @synthesize observerArray=_observerArray;
- (void)dealloc;
- (id)setLocationData:(id)arg1 withParam:(id)arg2;
- (void)updateData;
- (void)notifyObserver;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (_Bool)hasLocationPermission;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)forceRefresh:(CDUnknownBlockType)arg1;
- (void)createLocationManager;
- (id)initWithConfiguration:(id)arg1 WithLocationManager:(id)arg2 withCLLocationManagerClass:(Class)arg3;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

