//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YAActor.h"

@class NSDictionary, NSMutableArray, NSObject, NSString, YI13NVNodeData;
@protocol OS_dispatch_source;

@interface YI13NVNodeDataProvider : YAActor
{
    NSObject<OS_dispatch_source> *source;
    int fileDescriptor;
    _Bool keepMonitoringFile;
    NSString *_filePath;
    NSMutableArray *_observerArray;
    NSDictionary *_configuration;
    YI13NVNodeData *_nodeData;
}

+ (void)wipe;
+ (id)sharedInstance;
+ (void)setSharedInstance:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) YI13NVNodeData *nodeData; // @synthesize nodeData=_nodeData;
@property(retain, nonatomic) NSDictionary *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) NSMutableArray *observerArray; // @synthesize observerArray=_observerArray;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (void)dealloc;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)notifyObserver;
- (void)alertDelegateOfEvents:(unsigned long long)arg1;
- (void)recreateDispatchSource;
- (void)beginMonitoringFile;
- (void)forceRefresh:(CDUnknownBlockType)arg1;
- (id)initWithConfiguration:(id)arg1 withFilePath:(id)arg2;
- (id)init;

@end

