//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YMAdMiddleTierAdImageManifest.h"

@class NSNumber, NSString;

@interface YMAdMiddleTierFlurryAdImageManifest : YMAdMiddleTierAdImageManifest
{
    NSString *_URL;
    NSNumber *_width;
    NSNumber *_height;
}

+ (id)createWithURL:(id)arg1 width:(int)arg2 height:(int)arg3;
- (void).cxx_destruct;
@property(copy, nonatomic) NSNumber *height; // @synthesize height=_height;
@property(copy, nonatomic) NSNumber *width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *URL; // @synthesize URL=_URL;
- (id)initWithURL:(id)arg1 width:(int)arg2 height:(int)arg3;

@end

