//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface YMAdTextStyleAttribute : NSObject
{
    int _style;
    struct _NSRange _indexRange;
}

+ (id)createWithRange:(struct _NSRange)arg1 style:(int)arg2;
@property(nonatomic) struct _NSRange indexRange; // @synthesize indexRange=_indexRange;
@property(nonatomic) int style; // @synthesize style=_style;
- (id)initWithRange:(struct _NSRange)arg1 style:(int)arg2;

@end

