//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSURL, YMAdImage;

@interface YMAdVideo : NSObject
{
    _Bool _autoLoopEnabled;
    NSURL *_sourceURL;
    NSURL *_potraitURL;
    NSURL *_trailerURL;
    NSURL *_webViewEndCardURL;
    NSArray *_webViewEndCardBlackList;
    YMAdImage *_thumbnailImage;
    NSString *_callToActionText;
    double _chargeDuration;
    NSString *_videoStartURLFormat;
    NSString *_videoChargeURLFormat;
    NSString *_videoProgress25pctURLFormat;
    NSString *_videoProgress50pctURLFormat;
    NSString *_videoProgress75pctURLFormat;
    NSString *_videoProgress100pctURLFormat;
    NSString *_videoProgress3secURLFormat;
}

+ (id)createWithSourceURL:(id)arg1 potraitURL:(id)arg2 webViewEndCardURL:(id)arg3 webViewEndCardBlackList:(id)arg4 thumbnailImage:(id)arg5 chargeDuration:(double)arg6 callToActionText:(id)arg7 videoStartURLFormat:(id)arg8 videoChargeURLFormat:(id)arg9 videoProgress25pctURLFormat:(id)arg10 videoProgress50pctURLFormat:(id)arg11 videoProgress75pctURLFormat:(id)arg12 videoProgress100pctURLFormat:(id)arg13 autoLoopEnabled:(_Bool)arg14 trailerURL:(id)arg15;
+ (id)createWithSourceURL:(id)arg1 thumbnailImage:(id)arg2 chargeDuration:(double)arg3 callToActionText:(id)arg4 videoStartURLFormat:(id)arg5 videoChargeURLFormat:(id)arg6 videoProgress25pctURLFormat:(id)arg7 videoProgress50pctURLFormat:(id)arg8 videoProgress75pctURLFormat:(id)arg9 videoProgress100pctURLFormat:(id)arg10;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *videoProgress3secURLFormat; // @synthesize videoProgress3secURLFormat=_videoProgress3secURLFormat;
@property(copy, nonatomic) NSString *videoProgress100pctURLFormat; // @synthesize videoProgress100pctURLFormat=_videoProgress100pctURLFormat;
@property(copy, nonatomic) NSString *videoProgress75pctURLFormat; // @synthesize videoProgress75pctURLFormat=_videoProgress75pctURLFormat;
@property(copy, nonatomic) NSString *videoProgress50pctURLFormat; // @synthesize videoProgress50pctURLFormat=_videoProgress50pctURLFormat;
@property(copy, nonatomic) NSString *videoProgress25pctURLFormat; // @synthesize videoProgress25pctURLFormat=_videoProgress25pctURLFormat;
@property(copy, nonatomic) NSString *videoChargeURLFormat; // @synthesize videoChargeURLFormat=_videoChargeURLFormat;
@property(copy, nonatomic) NSString *videoStartURLFormat; // @synthesize videoStartURLFormat=_videoStartURLFormat;
@property(nonatomic) _Bool autoLoopEnabled; // @synthesize autoLoopEnabled=_autoLoopEnabled;
@property(nonatomic) double chargeDuration; // @synthesize chargeDuration=_chargeDuration;
@property(copy, nonatomic) NSString *callToActionText; // @synthesize callToActionText=_callToActionText;
@property(retain, nonatomic) YMAdImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(copy, nonatomic) NSArray *webViewEndCardBlackList; // @synthesize webViewEndCardBlackList=_webViewEndCardBlackList;
@property(copy, nonatomic) NSURL *webViewEndCardURL; // @synthesize webViewEndCardURL=_webViewEndCardURL;
@property(copy, nonatomic) NSURL *trailerURL; // @synthesize trailerURL=_trailerURL;
@property(copy, nonatomic) NSURL *potraitURL; // @synthesize potraitURL=_potraitURL;
@property(copy, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
- (id)initWithSourceURL:(id)arg1 potraitURL:(id)arg2 thumbnailImage:(id)arg3 webViewEndCardURL:(id)arg4 webViewEndCardBlackList:(id)arg5 chargeDuration:(double)arg6 callToActionText:(id)arg7 videoStartURLFormat:(id)arg8 videoChargeURLFormat:(id)arg9 videoProgress25pctURLFormat:(id)arg10 videoProgress50pctURLFormat:(id)arg11 videoProgress75pctURLFormat:(id)arg12 videoProgress100pctURLFormat:(id)arg13 autoLoopEnabled:(_Bool)arg14 trailerURL:(id)arg15;

@end

