//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "YMAdPolicyDataSource-Protocol.h"

@class NSDictionary, NSString;

@interface YMAdStaticPolicyDataSource : NSObject <YMAdPolicyDataSource>
{
    NSDictionary *_policyPayload;
}

+ (id)loadedFromResource;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *policyPayload; // @synthesize policyPayload=_policyPayload;
- (id)payloadForSection:(id)arg1;
- (id)initWithPayload:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

