//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol YMAdLogListener;

@protocol YMAdLogConfig <NSObject>
@property _Bool logToNSLog;
@property int severityLevel;
@property(copy) NSString *tagFilter;
- (void)removeAllLogListeners;
- (void)removeLogListener:(id <YMAdLogListener>)arg1;
- (void)registerLogListener:(id <YMAdLogListener>)arg1;
@end

