//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class YMAdView;
@protocol YMAdViewDelegate;

@interface YMAdViewStateAnimationTracker : NSObject
{
    YMAdView *_owningAdView;
    unsigned long long __currentAnimatingIdentifier;
    unsigned long long _nextAvailableAnimatingIdentifier;
}

+ (id)createWithOwningAdView:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long nextAvailableAnimatingIdentifier; // @synthesize nextAvailableAnimatingIdentifier=_nextAvailableAnimatingIdentifier;
@property(nonatomic) unsigned long long _currentAnimatingIdentifier; // @synthesize _currentAnimatingIdentifier=__currentAnimatingIdentifier;
@property(nonatomic) __weak YMAdView *owningAdView; // @synthesize owningAdView=_owningAdView;
- (void)reset;
- (void)layoutCompletedForTrackerIdentifier:(unsigned long long)arg1;
- (unsigned long long)layoutStartedForViewStateChange:(int)arg1 animated:(_Bool)arg2;
@property(nonatomic) unsigned long long currentAnimatingIdentifier;
@property(readonly, getter=isViewStateChangeAnimationInProgress) _Bool viewStateChangeAnimationInProgress;
@property(readonly, nonatomic) __weak id <YMAdViewDelegate> adViewDelegate;
- (id)initWithOwningAdView:(id)arg1;

@end

