//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface YMAdRequestedUnits : NSObject
{
    NSMutableArray *_units;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *units; // @synthesize units=_units;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)requestedUnits;
- (void)addUnit:(id)arg1;
- (void)addUnit:(id)arg1 unitOptions:(id)arg2;
- (id)init;

@end

