//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, YMAdUI;

@interface YMAdViewReuseManager : NSObject
{
    long long _dispatch_token;
    NSArray *__reuseIdentifiers;
    NSMutableDictionary *_placeholderAdUnits;
    NSMutableDictionary *_sizingViews;
    NSMutableDictionary *_fixedHeights;
    YMAdUI *_adUI;
}

- (void).cxx_destruct;
@property(nonatomic) __weak YMAdUI *adUI; // @synthesize adUI=_adUI;
@property(retain, nonatomic) NSMutableDictionary *fixedHeights; // @synthesize fixedHeights=_fixedHeights;
@property(retain, nonatomic) NSMutableDictionary *sizingViews; // @synthesize sizingViews=_sizingViews;
@property(retain, nonatomic) NSMutableDictionary *placeholderAdUnits; // @synthesize placeholderAdUnits=_placeholderAdUnits;
@property(copy, nonatomic) NSArray *_reuseIdentifiers; // @synthesize _reuseIdentifiers=__reuseIdentifiers;
- (id)createAdUnitForTemplateKey:(id)arg1;
- (id)adUnitForReuseIdentifier:(id)arg1;
- (id)sizingViewForReuseID:(id)arg1;
- (id)fixedHeightForReuseID:(id)arg1 viewState:(int)arg2;
- (id)unitControllerFromReuseID:(id)arg1;
- (id)createPlaceholderViewForReuseIdentifier:(id)arg1;
- (id)placeholderViewForReuseIdentifer:(id)arg1;
@property(readonly, nonatomic) NSArray *reuseIdentifiers;
- (id)initWithAdUI:(id)arg1;

@end

