//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YMAdDiagnosing.h"

@interface YMAdBeaconManager : YMAdDiagnosing
{
}

+ (id)createWithDiagnostics:(id)arg1;
- (void)followClickBeacon:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (id)requestFromURL:(id)arg1;
- (id)buildURLFromFormat:(id)arg1 paramsDictionary:(id)arg2 encodedByMethod:(int)arg3;
- (void)sendBeaconNamed:(id)arg1 URLFormat:(id)arg2 paramsDictionary:(id)arg3 encodedByMethod:(int)arg4 complete:(CDUnknownBlockType)arg5;
- (void)sendBeaconNamed:(id)arg1 URLFormat:(id)arg2 params:(id)arg3 encodedByMethod:(int)arg4 complete:(CDUnknownBlockType)arg5;

@end

