//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface YMAdPolicyAssetInfo : NSObject
{
    NSURL *_fetchURL;
    NSString *_assetType;
    NSString *_signatureY64;
}

+ (id)createWithFetchURL:(id)arg1 assetType:(id)arg2 signatureY64:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *signatureY64; // @synthesize signatureY64=_signatureY64;
@property(retain, nonatomic) NSString *assetType; // @synthesize assetType=_assetType;
@property(retain, nonatomic) NSURL *fetchURL; // @synthesize fetchURL=_fetchURL;
- (id)initWithFetchURL:(id)arg1 assetType:(id)arg2 signatureY64:(id)arg3;

@end

