//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YMAdJSONManifest.h"

@class NSNumber, NSString, YMAdMiddleTierAdImageManifest;

@interface YMAdMiddleTierAdAppManifest : YMAdJSONManifest
{
    YMAdMiddleTierAdImageManifest *_iconManifest;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YMAdMiddleTierAdImageManifest *iconManifest; // @synthesize iconManifest=_iconManifest;
- (id)fieldFromDictionary:(id)arg1 forKey:(id)arg2 ifOfType:(Class)arg3;
@property(readonly, copy, nonatomic) NSNumber *enableInstallCheck;
@property(readonly, copy, nonatomic) NSString *installedQualifier;
@property(readonly, copy, nonatomic) NSString *appStoreURL;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSString *category;
@property(readonly, copy, nonatomic) NSNumber *ratingCount;
@property(readonly, copy, nonatomic) NSNumber *ratingPercent;
@property(readonly, copy, nonatomic) NSString *ratingRaw;
@property(readonly, copy, nonatomic) NSNumber *storeIdentifier;

@end

