//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YMAdJSONManifest.h"

@class NSArray, NSString, YMAdMiddleTierConstraintsManifest;

@interface YMAdMiddleTierAdUnitManifest : YMAdJSONManifest
{
    YMAdMiddleTierConstraintsManifest *_constraintsManifest;
    NSArray *_adManifests;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *adManifests; // @synthesize adManifests=_adManifests;
@property(retain, nonatomic) YMAdMiddleTierConstraintsManifest *constraintsManifest; // @synthesize constraintsManifest=_constraintsManifest;
- (id)landingPageURL;
- (id)clickURL;
- (id)creativeID;
@property(readonly, copy, nonatomic) NSString *layoutType;
@property(readonly, copy, nonatomic) NSString *displayType;

@end

