//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "YMAdViewDelegates-Protocol.h"

@class NSArray, YMAdController, YMAdFeedbackComponent, YMAdVideoComponent;

@interface YMAdControllerComponents : NSObject <YMAdViewDelegates>
{
    YMAdFeedbackComponent *_feedbackComponent;
    YMAdVideoComponent *_videoComponent;
    YMAdController *_adController;
    NSArray *_components;
}

+ (id)createWithAdController:(id)arg1 feedbackComponent:(id)arg2 videoComponent:(id)arg3;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *components; // @synthesize components=_components;
@property(nonatomic) __weak YMAdController *adController; // @synthesize adController=_adController;
@property(retain, nonatomic) YMAdVideoComponent *videoComponent; // @synthesize videoComponent=_videoComponent;
@property(retain, nonatomic) YMAdFeedbackComponent *feedbackComponent; // @synthesize feedbackComponent=_feedbackComponent;
- (void)eachComponentNeedingControllerEvents:(CDUnknownBlockType)arg1;
- (void)eachComponentOfType:(id)arg1 doAction:(CDUnknownBlockType)arg2;
- (id)videoDelegate;
- (id)feedbackDelegate;
- (id)viewDelegate;
- (id)initWithAdController:(id)arg1 feedbackComponent:(id)arg2 videoComponent:(id)arg3;

@end

