//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

@interface YMAdVideoConfig : NSObject
{
    _Bool _initialAutoplayEnabled;
    _Bool _autoplaySkipsWifiCheck;
    int _autoRestartScenarios;
    NSSet *_allowedAutoplayViewStates;
}

+ (id)expandableVideoConfig;
+ (id)defaultVideoConfig;
- (void).cxx_destruct;
@property(retain, nonatomic) NSSet *allowedAutoplayViewStates; // @synthesize allowedAutoplayViewStates=_allowedAutoplayViewStates;
@property(nonatomic) _Bool autoplaySkipsWifiCheck; // @synthesize autoplaySkipsWifiCheck=_autoplaySkipsWifiCheck;
@property(nonatomic) int autoRestartScenarios; // @synthesize autoRestartScenarios=_autoRestartScenarios;
@property(nonatomic) _Bool initialAutoplayEnabled; // @synthesize initialAutoplayEnabled=_initialAutoplayEnabled;
- (id)initWithInitialAutoplayEnabled:(_Bool)arg1 autoRestartScenarios:(int)arg2 autoplaySkipsWifiCheck:(_Bool)arg3 allowedAutoplayViewStates:(id)arg4;
- (_Bool)autoplayAllowedInViewState:(int)arg1;

@end

