//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface YMAdExtensionViewProperties : NSObject
{
    int hitRegion;
    int viewStateForDictionary;
    NSString *identifier;
    NSSet *_presenceTags;
    NSSet *_goneTags;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSSet *goneTags; // @synthesize goneTags=_goneTags;
@property(retain, nonatomic) NSSet *presenceTags; // @synthesize presenceTags=_presenceTags;
@property(retain) NSString *viewStateStringForDictionary;
@property(retain) NSString *hitRegionString;
- (_Bool)intersectsGoneTag:(id)arg1;
- (_Bool)intersectsPresenceTag:(id)arg1;
- (_Bool)hasPresenceTag:(id)arg1;
- (id)parseTagSetFromCSV:(id)arg1;
- (void)setPresenceTagsCSV:(id)arg1;
- (void)setGoneTagsCSV:(id)arg1;
- (id)init;

@end

