//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YMAdCPCRegionView.h"

@class YMAdHorizontalDualLayout;

@interface YMAdCardCPCRegionView : YMAdCPCRegionView
{
    YMAdHorizontalDualLayout *_sponsorMoreAppContainerHorizontalLayout;
}

- (void).cxx_destruct;
@property(nonatomic) __weak YMAdHorizontalDualLayout *sponsorMoreAppContainerHorizontalLayout; // @synthesize sponsorMoreAppContainerHorizontalLayout=_sponsorMoreAppContainerHorizontalLayout;

@end

