//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "YMAdTransitionalButtonConfigSet-Protocol.h"

@class NSDictionary, NSString;

@interface YMAdTransitionalButtonConfigSet : NSObject <YMAdTransitionalButtonConfigSet>
{
    NSDictionary *_buttonConfigsForViewStates;
}

+ (id)configSetWithConfigs:(id)arg1;
+ (id)configSetWithConfig:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *buttonConfigsForViewStates; // @synthesize buttonConfigsForViewStates=_buttonConfigsForViewStates;
- (id)buttonConfigForViewState:(int)arg1;
- (id)initWithButtonConfigs:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

