//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YMAdJSONManifest.h"

@class NSArray, NSString, NSURL;

@interface YMAdRenderingPolicyTemplateManifest : YMAdJSONManifest
{
}

@property(readonly, nonatomic) NSString *reuseID;
@property(readonly, nonatomic) NSString *signatureY64;
@property(readonly, nonatomic) NSArray *maxSDKVersion;
@property(readonly, nonatomic) NSArray *minSDKVersion;
@property(readonly, nonatomic) NSURL *URL;

@end

