//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSLayoutConstraint, NSNumber, NSString;

@interface YMAdButton : UIButton
{
    NSNumber *_shouldSizeToText;
    NSString *_buttonAlignment;
    NSNumber *_horizontalPadding;
    NSNumber *_maxWidth;
    NSNumber *_isOldInstallButtonStyle;
    NSLayoutConstraint *_widthConstraint;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=_widthConstraint;
@property(retain, nonatomic) NSNumber *isOldInstallButtonStyle; // @synthesize isOldInstallButtonStyle=_isOldInstallButtonStyle;
@property(retain, nonatomic) NSNumber *maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) NSNumber *horizontalPadding; // @synthesize horizontalPadding=_horizontalPadding;
@property(retain, nonatomic) NSString *buttonAlignment; // @synthesize buttonAlignment=_buttonAlignment;
@property(retain, nonatomic) NSNumber *shouldSizeToText; // @synthesize shouldSizeToText=_shouldSizeToText;
- (id)createGradientLayerForOldInstallNowButtonStyle;
- (void)applyOldInstallNowButtonStyle;
- (void)layoutSubviews;
- (void)colorBorder;
- (void)sizeButtonIfRequired;
- (void)applyViewOptions:(id)arg1;
- (void)applyC2CViewOptions:(id)arg1;
- (void)setTextColor:(id)arg1 forState:(unsigned long long)arg2;
- (void)setBorderColor:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setText:(id)arg1;
@property(readonly) _Bool isCenterAlign;
@property(readonly) _Bool isRightAlign;
- (void)awakeFromNib;

@end

