//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface YMAdUtil : NSObject
{
}

+ (id)parseAppIdFromItunesUrl:(id)arg1;
+ (_Bool)parseARGBString:(id)arg1 toComponents:(unsigned long long [4])arg2;
+ (long long)compareVersion:(id)arg1 toVersion:(id)arg2;
+ (struct CGSize)sizeFromWidth:(double)arg1 aspectRatio:(double)arg2;
+ (double)calculateAspectRatio:(struct CGSize)arg1;
+ (void)performOnMainThread:(CDUnknownBlockType)arg1;
+ (id)readHexValue:(id)arg1;

@end

