//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSNumber;

@interface YMAdLabel : UILabel
{
    NSNumber *_shouldSizeToText;
    NSNumber *_sizeFrameToLabelSize;
    NSNumber *_originalFontSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *originalFontSize; // @synthesize originalFontSize=_originalFontSize;
@property(retain, nonatomic) NSNumber *sizeFrameToLabelSize; // @synthesize sizeFrameToLabelSize=_sizeFrameToLabelSize;
@property(retain, nonatomic) NSNumber *shouldSizeToText; // @synthesize shouldSizeToText=_shouldSizeToText;
- (id)fontForLabel;
- (void)setFontScale:(double)arg1;
- (void)sizeToFitIfRequired;
- (void)setAttributedText:(id)arg1;
- (void)setText:(id)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

