//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSString;

@interface YSNEventFactory : NSObject
{
    long long _lastScreenviewTimestamp;
    NSString *_lastScreenviewName;
    long long _lastLifecycleEventType;
    long long _lastLifecycleEventTimestamp;
    NSLock *_lock;
}

+ (id)sharedEventFactory;
- (void).cxx_destruct;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(nonatomic) long long lastLifecycleEventTimestamp; // @synthesize lastLifecycleEventTimestamp=_lastLifecycleEventTimestamp;
@property(nonatomic) long long lastLifecycleEventType; // @synthesize lastLifecycleEventType=_lastLifecycleEventType;
@property(copy, nonatomic) NSString *lastScreenviewName; // @synthesize lastScreenviewName=_lastScreenviewName;
@property(nonatomic) long long lastScreenviewTimestamp; // @synthesize lastScreenviewTimestamp=_lastScreenviewTimestamp;
- (id)lifecycleEventWithType:(long long)arg1 fromUserInteraction:(_Bool)arg2 sequenceNumber:(int)arg3 eventTrigger:(id)arg4 andParameters:(id)arg5;
- (id)eventWithType:(long long)arg1 name:(id)arg2 spaceId:(unsigned long long)arg3 fromUserInteraction:(_Bool)arg4 andParameters:(id)arg5 links:(id)arg6 sdkName:(id)arg7 eventTrigger:(id)arg8 parameterPriority:(id)arg9;
- (id)eventWithType:(long long)arg1 name:(id)arg2 fromUserInteraction:(_Bool)arg3 andParameters:(id)arg4 sdkName:(id)arg5 eventTrigger:(id)arg6;
- (void)dealloc;
- (id)init;
- (id)p_initEventWithType:(long long)arg1 andSpaceId:(unsigned long long)arg2 andName:(id)arg3 fromUserInteraction:(_Bool)arg4 andParameters:(id)arg5 links:(id)arg6 eventTrigger:(id)arg7 parameterPriority:(id)arg8;
- (id)p_screenviewEventDictionary;
- (id)p_lifecycleEventDictionary;
- (void)p_handleScreenviewEventOccurred:(id)arg1;
- (void)p_handleLifecycleEventOccurred:(id)arg1;

@end

