//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YSNEvent.h"

@interface YSNTimedEvent : YSNEvent
{
    _Bool _timed;
    double _createdAt;
}

@property(nonatomic) double createdAt; // @synthesize createdAt=_createdAt;
@property(nonatomic) _Bool timed; // @synthesize timed=_timed;
- (double)timeIntervalSinceCreation;
- (void)start;
- (id)initWithType:(long long)arg1 name:(id)arg2 spaceId:(unsigned long long)arg3 fromUserInteraction:(_Bool)arg4 andParameters:(id)arg5;
- (id)initWithType:(long long)arg1 name:(id)arg2 fromUserInteraction:(_Bool)arg3 eventTrigger:(id)arg4 andParameters:(id)arg5;

@end

