//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "VDMSAnalyticsObserver-Protocol.h"
#import "YVAnalyticsSessionDelegate-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol YVAnalyticsDelegate, YVExternalLoggerProtocol;

@interface YVAnalytics : NSObject <YVAnalyticsSessionDelegate, VDMSAnalyticsObserver>
{
    _Bool _loggingEnabled;
    id <YVAnalyticsDelegate> _delegate;
    NSString *_playerType;
    NSString *_version;
    unsigned long long _continuousPlayCount;
    NSMutableDictionary *_analyticsSessions;
    id <YVExternalLoggerProtocol> _logger;
}

+ (id)stringForVideoContentType:(long long)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <YVExternalLoggerProtocol> logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) NSMutableDictionary *analyticsSessions; // @synthesize analyticsSessions=_analyticsSessions;
@property(nonatomic) unsigned long long continuousPlayCount; // @synthesize continuousPlayCount=_continuousPlayCount;
@property(readonly, nonatomic) NSString *version; // @synthesize version=_version;
@property(readonly, nonatomic) NSString *playerType; // @synthesize playerType=_playerType;
@property(nonatomic) _Bool loggingEnabled; // @synthesize loggingEnabled=_loggingEnabled;
@property(nonatomic) __weak id <YVAnalyticsDelegate> delegate; // @synthesize delegate=_delegate;
- (void)logEventWithName:(id)arg1 parameters:(id)arg2;
- (void)handleChromecastEvent:(id)arg1;
- (void)handleAirplayEvent:(id)arg1;
- (void)handlePlayPauseEvent:(id)arg1;
- (void)handleUserChangedAudioStreamEvent:(id)arg1;
- (void)handleUserChangedCaptionsLanguageEvent:(id)arg1;
- (void)handleSeekCompletedEvent:(id)arg1;
- (void)handleBitrateChangedEvent:(id)arg1;
- (void)handleStallEvent:(id)arg1;
- (void)handleCompletedEvent:(id)arg1;
- (void)handleProgressEvent:(id)arg1;
- (void)handleStreamViewEvent:(id)arg1;
- (void)handleStartEvent:(id)arg1;
- (void)handleRequestEvent:(id)arg1;
- (void)newAnalyticsEvent:(id)arg1;
- (void)logAdEventOnVideo:(id)arg1 withName:(id)arg2 withParameters:(id)arg3;
- (void)userToggledChrome:(_Bool)arg1 onVideo:(id)arg2;
- (void)userPressedUnmuteButtonOnVideo:(id)arg1;
- (void)userPressedMuteButtonOnVideo:(id)arg1;
- (void)logError:(id)arg1 onVideoSession:(id)arg2 willRetry:(_Bool)arg3;
- (void)logVideoViewError:(id)arg1 willRetry:(_Bool)arg2;
- (void)playlistScrolled:(id)arg1;
- (void)playlistApiRequestCompletedWithUrl:(id)arg1 httpStatusCode:(long long)arg2 contentLength:(unsigned long long)arg3 latency:(double)arg4 instrumentationInfo:(id)arg5 performanceMetrics:(id)arg6;
- (void)video:(id)arg1 apiRequestCompletedWithUrl:(id)arg2 httpStatusCode:(long long)arg3 contentLength:(unsigned long long)arg4 latency:(double)arg5 instrumentationInfo:(id)arg6 performanceMetrics:(id)arg7 recovery:(_Bool)arg8;
- (void)trackVideo:(id)arg1 windowState:(long long)arg2 fromUserInteraction:(_Bool)arg3;
- (void)newPlaybackSession:(id)arg1;
- (id)analyticsForVideoSession:(id)arg1;
- (id)initWithPlayerType:(id)arg1 version:(id)arg2 logger:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

