//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface YVAPGeminiViewabilityManager : NSObject
{
    double _totalTime;
    double _timeAudibleAndFocused;
    NSDictionary *_playerData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *playerData; // @synthesize playerData=_playerData;
@property(nonatomic) double timeAudibleAndFocused; // @synthesize timeAudibleAndFocused=_timeAudibleAndFocused;
@property(nonatomic) double totalTime; // @synthesize totalTime=_totalTime;
- (_Bool)playerBoolForKey:(id)arg1;
- (int)playerIntForKey:(id)arg1;
- (id)getGeminiMacrosWith:(id)arg1;
- (id)intToString:(int)arg1;
- (void)updateViewabilityForTime:(double)arg1 geminiTrackingBeacons:(id)arg2;
- (void)updateBeaconTimers:(id)arg1 timeDelta:(double)arg2;
- (void)updatePlayerData:(id)arg1;

@end

