//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YVResourceNode.h"

#import "YVBoolProtocol-Protocol.h"

@class NSString;

@interface YVBoolNode : YVResourceNode <YVBoolProtocol>
{
}

- (void)forceUpdateBool:(_Bool)arg1;
- (void)updateBool:(_Bool)arg1;
@property(readonly) _Bool boolValue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

