//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UILabel.h>

@class CAGradientLayer, NSString;

@interface YVChromeLiveIndicatorView : UILabel
{
    NSString *_customFontname;
}

+ (Class)layerClass;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *customFontname; // @synthesize customFontname=_customFontname;
- (void)sizeToFit;
- (id)initWithFrame:(struct CGRect)arg1 andFontname:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(retain, nonatomic) CAGradientLayer *layer; // @dynamic layer;

@end

