//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, UIColor, UIImage;

@protocol YVCustomChromeProvider <NSObject>

@optional
- (NSArray *)seekBarLayout;
- (NSArray *)bottomRightRowLayout;
- (NSArray *)bottomLeftRowLayout;
- (NSArray *)topRightRowLayout;
- (NSArray *)topLeftRowLayout;
- (_Bool)customRowLayoutsEnabled;
- (UIImage *)seekbarThumbIcon;
- (UIColor *)seekbarMaximumTrackTintColor;
- (UIColor *)seekbarMinimumTrackTintColor;
- (UIImage *)audioSelectionIcon;
- (UIImage *)captionsOffIcon;
- (UIImage *)captionsOnIcon;
- (UIImage *)exitFullscreenIcon;
- (UIImage *)enterFullscreenIcon;
- (UIImage *)muteOffIcon;
- (UIImage *)muteOnIcon;
- (UIImage *)pauseIcon;
- (UIImage *)playIcon;
- (UIImage *)backgroundGradient;
- (UIImage *)popoutIcon;
- (UIImage *)replayIconLarge;
- (UIImage *)playIconLarge;
@end

