//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YVTargetValue.h"

@interface YVDynamicSourceValue : YVTargetValue
{
    CDUnknownBlockType _updateSources;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) CDUnknownBlockType updateSources; // @synthesize updateSources=_updateSources;
- (id)initWithName:(id)arg1 updateValue:(CDUnknownBlockType)arg2 upateSources:(CDUnknownBlockType)arg3;

@end

