//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, YVAudioStreamOption;

@interface YVEventCaptionStreamsBecameAvailable : NSObject
{
    NSArray *_availableCaptionStreams;
    YVAudioStreamOption *_selectedCaptionStream;
}

- (void).cxx_destruct;
@property(retain, nonatomic) YVAudioStreamOption *selectedCaptionStream; // @synthesize selectedCaptionStream=_selectedCaptionStream;
@property(retain, nonatomic) NSArray *availableCaptionStreams; // @synthesize availableCaptionStreams=_availableCaptionStreams;

@end

