//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;
@protocol YVExternalLoggerProtocol;

@protocol YVExternalAPIProtocol <NSObject>
@property(readonly, nonatomic) id <YVExternalLoggerProtocol> logger;
- (NSString *)authQueryParamsValueForVideoUUID:(NSString *)arg1 geoHeader:(NSString *)arg2;
- (NSString *)authHeaderValueForVideoUUID:(NSString *)arg1 geoHeader:(NSString *)arg2;
- (NSString *)configUpdatedNotificationName;
- (NSDictionary *)configDictionary;
- (void)removeConsentObserver;
- (void)addConsentObserverWithUpdateBlock:(void (^)(void))arg1;
- (_Bool)hasUserConsentedForNielsen;
- (_Bool)hasUserOptedOutOfAdTracking;
- (NSDictionary *)userConsentRecord;
- (NSString *)sapiBCookie;
@end

