//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class YVideoMP4CacheLoadingHandler;

@protocol YVideoMP4CacheLoadingHandlerDelegate
- (void)loadingHandler:(YVideoMP4CacheLoadingHandler *)arg1 servedBytesFromCache:(unsigned long long)arg2;
- (void)loadingDidComplete:(YVideoMP4CacheLoadingHandler *)arg1;
@end

