//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class CLLocation, NSArray, NSDate, NSDictionary, NSMutableDictionary, NSNumber, NSString, NSURL, UIImage, YVPlaybackInfo, YVPlayerConfiguration, YVVisualSeekMetadata;
@protocol VDMSAdMetadata;

@interface YVideoMetadata : NSObject <NSCopying>
{
    _Bool _wifiPlaybackRestriction;
    _Bool _nielsenEnabled;
    NSString *_uuid;
    NSString *_desc;
    NSString *_title;
    NSString *_thumbnailURL;
    NSString *_showName;
    NSString *_watchToken;
    long long _contentType;
    NSDate *_publishDate;
    NSString *_preferredRegion;
    NSString *_preferredLang;
    NSURL *_sharingURL;
    NSString *_provider;
    NSDictionary *_timelapseInfo;
    NSMutableDictionary *_relatedMetadata;
    NSArray *_markers;
    NSNumber *_metadataDuration;
    NSNumber *_preferredAspectRatio;
    NSString *_externalId;
    NSString *_requestId;
    YVPlayerConfiguration *_playerConfiguration;
    YVPlaybackInfo *_playbackInfo;
    NSURL *_metadataSystemUrl;
    long long _metadataSystemType;
    NSString *_providerId;
    UIImage *_thumbnailImage;
    NSObject<VDMSAdMetadata> *_adMetadata;
    NSString *_uplynkSessionID;
    NSString *_uplynkZonePrefix;
    NSString *_pageSpaceId;
    NSString *_streamTypeGuess;
    NSString *_playlistInstrumentationData;
    NSString *_playlistId;
    double _metadataLatency;
    NSURL *_requestUrl;
    long long _externalPlaybackRestriction;
    NSString *_licensorId;
    NSString *_adProvider;
    NSArray *_cues;
    NSString *_liveState;
    NSDate *_liveStartDate;
    unsigned long long _sapiEndpointType;
    YVVisualSeekMetadata *_visualSeekMetadata;
    NSString *_mmActivityID;
    NSArray *_customQueryParams;
}

+ (id)searchForStringsWithKeyPath:(id)arg1 inJsonObject:(id)arg2;
+ (id)searchForDictionariesWithKeyPath:(id)arg1 inJsonObject:(id)arg2;
+ (void)searchForObjectsOfClass:(Class)arg1 withKeys:(id)arg2 keyIndex:(unsigned long long)arg3 inObject:(id)arg4 results:(id)arg5;
+ (id)searchForObjectsOfClass:(Class)arg1 withKeyPath:(id)arg2 inJsonObject:(id)arg3;
+ (id)urlOrNilForKeyPath:(id)arg1 inDictionary:(id)arg2;
+ (id)stringOrNilForKeyPath:(id)arg1 inDictionary:(id)arg2;
+ (id)numberOrNilForKeyPath:(id)arg1 inDictionary:(id)arg2;
+ (id)dictionaryOrNilForKeyPath:(id)arg1 inDictionary:(id)arg2;
+ (id)arrayOrNilOfType:(Class)arg1 forKeyPath:(id)arg2 inDictionary:(id)arg3;
+ (id)arrayOrNilForKeyPath:(id)arg1 inDictionary:(id)arg2;
+ (id)objectOrNilForKeyPath:(id)arg1 inDictionary:(id)arg2 expectingType:(Class)arg3;
+ (id)serializeDictionaryFromResponseData:(id)arg1 error:(id *)arg2;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *customQueryParams; // @synthesize customQueryParams=_customQueryParams;
@property(retain, nonatomic) NSString *mmActivityID; // @synthesize mmActivityID=_mmActivityID;
@property(retain, nonatomic) YVVisualSeekMetadata *visualSeekMetadata; // @synthesize visualSeekMetadata=_visualSeekMetadata;
@property(nonatomic) unsigned long long sapiEndpointType; // @synthesize sapiEndpointType=_sapiEndpointType;
@property(retain, nonatomic) NSDate *liveStartDate; // @synthesize liveStartDate=_liveStartDate;
@property(retain, nonatomic) NSString *liveState; // @synthesize liveState=_liveState;
@property(retain, nonatomic) NSArray *cues; // @synthesize cues=_cues;
@property(retain, nonatomic) NSString *adProvider; // @synthesize adProvider=_adProvider;
@property(nonatomic) _Bool nielsenEnabled; // @synthesize nielsenEnabled=_nielsenEnabled;
@property(retain, nonatomic) NSString *licensorId; // @synthesize licensorId=_licensorId;
@property(nonatomic) _Bool wifiPlaybackRestriction; // @synthesize wifiPlaybackRestriction=_wifiPlaybackRestriction;
@property(nonatomic) long long externalPlaybackRestriction; // @synthesize externalPlaybackRestriction=_externalPlaybackRestriction;
@property(retain, nonatomic) NSURL *requestUrl; // @synthesize requestUrl=_requestUrl;
@property(nonatomic) double metadataLatency; // @synthesize metadataLatency=_metadataLatency;
@property(retain, nonatomic) NSString *playlistId; // @synthesize playlistId=_playlistId;
@property(retain, nonatomic) NSString *playlistInstrumentationData; // @synthesize playlistInstrumentationData=_playlistInstrumentationData;
@property(readonly, nonatomic) NSString *streamTypeGuess; // @synthesize streamTypeGuess=_streamTypeGuess;
@property(retain, nonatomic) NSString *pageSpaceId; // @synthesize pageSpaceId=_pageSpaceId;
@property(retain, nonatomic) NSString *uplynkZonePrefix; // @synthesize uplynkZonePrefix=_uplynkZonePrefix;
@property(retain, nonatomic) NSString *uplynkSessionID; // @synthesize uplynkSessionID=_uplynkSessionID;
@property(retain, nonatomic) NSObject<VDMSAdMetadata> *adMetadata; // @synthesize adMetadata=_adMetadata;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage=_thumbnailImage;
@property(copy, nonatomic) NSString *providerId; // @synthesize providerId=_providerId;
@property(nonatomic) long long metadataSystemType; // @synthesize metadataSystemType=_metadataSystemType;
@property(retain, nonatomic) NSURL *metadataSystemUrl; // @synthesize metadataSystemUrl=_metadataSystemUrl;
@property(retain, nonatomic) YVPlaybackInfo *playbackInfo; // @synthesize playbackInfo=_playbackInfo;
@property(retain, nonatomic) YVPlayerConfiguration *playerConfiguration; // @synthesize playerConfiguration=_playerConfiguration;
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(retain, nonatomic) NSString *externalId; // @synthesize externalId=_externalId;
@property(copy, nonatomic) NSNumber *preferredAspectRatio; // @synthesize preferredAspectRatio=_preferredAspectRatio;
@property(retain, nonatomic) NSNumber *metadataDuration; // @synthesize metadataDuration=_metadataDuration;
@property(retain, nonatomic) NSArray *markers; // @synthesize markers=_markers;
@property(retain, nonatomic) NSMutableDictionary *relatedMetadata; // @synthesize relatedMetadata=_relatedMetadata;
@property(copy, nonatomic) NSDictionary *timelapseInfo; // @synthesize timelapseInfo=_timelapseInfo;
@property(retain, nonatomic) NSString *provider; // @synthesize provider=_provider;
@property(copy, nonatomic) NSURL *sharingURL; // @synthesize sharingURL=_sharingURL;
@property(retain, nonatomic) NSString *preferredLang; // @synthesize preferredLang=_preferredLang;
@property(retain, nonatomic) NSString *preferredRegion; // @synthesize preferredRegion=_preferredRegion;
@property(retain, nonatomic) NSDate *publishDate; // @synthesize publishDate=_publishDate;
@property(nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) NSString *watchToken; // @synthesize watchToken=_watchToken;
@property(copy, nonatomic) NSString *showName; // @synthesize showName=_showName;
@property(copy, nonatomic) NSString *thumbnailURL; // @synthesize thumbnailURL=_thumbnailURL;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)runOnMain:(CDUnknownBlockType)arg1 withParm:(id)arg2;
- (void)updateContentTypeForDuration:(double)arg1;
@property(readonly, nonatomic) NSDate *displayDate;
@property(readonly, copy, nonatomic) NSString *identifier;
- (unsigned long long)hash;
@property(nonatomic) _Bool is360;
@property(nonatomic) _Bool isLive;
@property(readonly, copy, nonatomic) NSURL *videoURL;
- (void)addCustomQueryParams:(id)arg1;
@property(retain, nonatomic) CLLocation *physicalLocation;
@property(nonatomic) _Bool adsDisabled;
@property(nonatomic) _Bool inAutoplayContext;
@property(copy, nonatomic) NSString *yvapAccountId;
@property(copy, nonatomic) NSString *section;
@property(copy, nonatomic) NSString *streamPosition;
@property(copy, nonatomic) NSString *devType;
@property(copy, nonatomic) NSString *site;
@property(copy, nonatomic) NSString *experienceType;
@property(copy, nonatomic) NSString *experienceName;
- (_Bool)isEqualToMetadata:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)copyBaseConfigurationFromMetadata:(id)arg1;
- (id)copyToSubclass:(Class)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopy;
- (id)copy;
- (id)initWithUuid:(id)arg1 metadataSystemUrl:(id)arg2 metadataSystemType:(long long)arg3;
- (id)initWithUuid:(id)arg1 preferredAspectRatio:(id)arg2;
- (id)initWithUuid:(id)arg1;
- (id)initWithVideoUrl:(id)arg1;
- (id)initWithMetadataSystemType:(long long)arg1;
- (id)init;

@end

