//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, NSTimer, UIButton, UITextView, VDMSGlobalState, YVideoSession;

@interface YVideoLiveStatsOverlayView : UIView <UIGestureRecognizerDelegate, MFMailComposeViewControllerDelegate>
{
    VDMSGlobalState *_globalState;
    YVideoSession *_videoSession;
    NSTimer *_updateTimer;
    UITextView *_textView;
    UIButton *_statsCopyButton;
    UIButton *_statsCloseButton;
    NSString *_lastStatsText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *lastStatsText; // @synthesize lastStatsText=_lastStatsText;
@property(retain, nonatomic) UIButton *statsCloseButton; // @synthesize statsCloseButton=_statsCloseButton;
@property(retain, nonatomic) UIButton *statsCopyButton; // @synthesize statsCopyButton=_statsCopyButton;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(nonatomic) __weak YVideoSession *videoSession; // @synthesize videoSession=_videoSession;
@property(readonly, nonatomic) __weak VDMSGlobalState *globalState; // @synthesize globalState=_globalState;
- (_Bool)canResignFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (id)playIntentionStringForVideoSession:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
- (void)presentViewController:(id)arg1;
- (void)copyButtonPressed:(id)arg1;
- (id)statsText;
- (void)update;
- (void)dismiss;
- (void)addToFrontOfWindow;
- (void)presentForVideoSession:(id)arg1;
- (void)setupSubviews:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

