//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CAMetalLayer;
@protocol MTLBuffer, MTLCommandQueue, MTLDevice, MTLSamplerState;

@interface YVideo360Renderer : NSObject
{
    CAMetalLayer *_metalLayer;
    id <MTLCommandQueue> _commandQueue;
    id <MTLSamplerState> _sampler;
    id <MTLBuffer> _uniformBuffer;
    CDStruct_14d5dc5e _projectionMatrix;
    CDStruct_14d5dc5e _modelViewMatrix;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) id <MTLBuffer> uniformBuffer; // @synthesize uniformBuffer=_uniformBuffer;
@property(retain, nonatomic) id <MTLSamplerState> sampler; // @synthesize sampler=_sampler;
@property(retain, nonatomic) id <MTLCommandQueue> commandQueue; // @synthesize commandQueue=_commandQueue;
@property(nonatomic) __weak CAMetalLayer *metalLayer; // @synthesize metalLayer=_metalLayer;
@property(nonatomic) CDStruct_14d5dc5e modelViewMatrix; // @synthesize modelViewMatrix=_modelViewMatrix;
@property(nonatomic) CDStruct_14d5dc5e projectionMatrix; // @synthesize projectionMatrix=_projectionMatrix;
- (void)drawMesh:(id)arg1 withMaterial:(id)arg2;
- (void)updateUniforms;
@property(readonly, nonatomic) id <MTLDevice> device;
- (id)initWithMetalLayer:(id)arg1;

@end

