//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSFastEnumeration-Protocol.h"

@class NSMutableArray, NSMutableDictionary;

@interface YVideoOrderedMap : NSObject <NSFastEnumeration>
{
    NSMutableDictionary *_dictionary;
    NSMutableArray *_array;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *array; // @synthesize array=_array;
@property(retain, nonatomic) NSMutableDictionary *dictionary; // @synthesize dictionary=_dictionary;
- (id)description;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (void)removeObjectsAtIndexes:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)moveKeyToEnd:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)lastObject;
- (void)enumerateAtIndexes:(id)arg1 options:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)objectsAtIndexes:(id)arg1;
- (id)objectForKey:(id)arg1;
- (id)objectAtIndex:(long long)arg1;
- (id)keyAtIndex:(long long)arg1;
@property(readonly, nonatomic) unsigned long long count;
- (id)init;

@end

