//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SceneKit/SCNView.h>

@class SCNCamera, SCNNode;

@interface YVideo360SceneKitView : SCNView
{
    SCNCamera *_sceneCamera;
    SCNNode *_cameraPanXNode;
    SCNNode *_cameraMotionNode;
    SCNNode *_cameraPanYNode;
    SCNNode *_sphereNode;
}

+ (id)createSceneKitView;
- (void).cxx_destruct;
@property(retain, nonatomic) SCNNode *sphereNode; // @synthesize sphereNode=_sphereNode;
@property(retain, nonatomic) SCNNode *cameraPanYNode; // @synthesize cameraPanYNode=_cameraPanYNode;
@property(retain, nonatomic) SCNNode *cameraMotionNode; // @synthesize cameraMotionNode=_cameraMotionNode;
@property(retain, nonatomic) SCNNode *cameraPanXNode; // @synthesize cameraPanXNode=_cameraPanXNode;
@property(retain, nonatomic) SCNCamera *sceneCamera; // @synthesize sceneCamera=_sceneCamera;
- (union _GLKQuaternion)reorientCameraWith:(long long)arg1 andQuaternion:(union _GLKQuaternion)arg2;
- (void)adjustProjectionForPanX:(double)arg1 andPanY:(double)arg2;
- (void)adjustProjectionForDeviceAttitude:(id)arg1;
- (void)adjustCameraZoom:(float)arg1;
- (void)configureSceneWith:(id)arg1;
- (id)createSphereNode:(id)arg1;
- (void)setUpPlayer:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 options:(id)arg2;

@end

