//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSBundle;

@interface YVideoAutoplaySettings : NSObject
{
    long long _optionCount;
    CDUnknownBlockType _migrationBlock;
    NSArray *_indexedOptions;
    NSArray *_optionText;
    NSBundle *_bundle;
}

+ (id)sharedSettings;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(readonly, nonatomic) NSArray *optionText; // @synthesize optionText=_optionText;
@property(readonly, nonatomic) NSArray *indexedOptions; // @synthesize indexedOptions=_indexedOptions;
@property(copy, nonatomic) CDUnknownBlockType migrationBlock; // @synthesize migrationBlock=_migrationBlock;
@property(nonatomic) long long optionCount; // @synthesize optionCount=_optionCount;
- (void)presentOptionsPopupInViewController:(id)arg1;
- (id)shortNameForAutoplayType:(long long)arg1;
- (id)textForOptionIndex:(long long)arg1;
- (long long)optionIndexToType:(long long)arg1;
- (long long)typeToOptionIndex:(long long)arg1;
@property(nonatomic) long long autoplayPreferenceByOptionIndex;
- (void)setAutoplayPreference:(long long)arg1 sendNotification:(_Bool)arg2;
@property(nonatomic) long long autoplayPreference;
- (_Bool)isValidPreference:(long long)arg1;
- (void)setSavedValue:(id)arg1 forKey:(id)arg2;
- (id)savedValueForKey:(id)arg1;
- (long long)defaultPreference;
- (id)init;

@end

