//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "VDMSPingClientDelegate-Protocol.h"
#import "YVChromeDelegate-Protocol.h"
#import "YVPlayerErrorOverlayDelegate-Protocol.h"
#import "YVideoAdControllerDelegate-Protocol.h"
#import "YVideoAlternateOverlaysDelegate-Protocol.h"
#import "YVideoSessionDelegate-Protocol.h"

@class NSDate, NSMapTable, NSNumber, NSString, NSTimer, VDMSGlobalState, VDMSPingClient, YVAnalytics, YVChrome, YVContainerExtent, YVPlayer, YVideoAdController, YVideoAlternateOverlays, YVideoDefaultErrorOverlay, YVideoPlayerControlOptions, YVideoSession, YVideoSessionState, YVideoView;
@protocol YVideoContainerViewDelegate;

@interface YVideoContainerView : UIView <YVideoSessionDelegate, YVideoAdControllerDelegate, YVChromeDelegate, YVideoAlternateOverlaysDelegate, VDMSPingClientDelegate, YVPlayerErrorOverlayDelegate>
{
    _Bool _hasBeenSetUp;
    _Bool _chromeVisible;
    _Bool _chromeAllowed;
    _Bool _wantsToLoadBeforeSetup;
    _Bool _prepareContentVideoNeeded;
    _Bool _seekPendingforLiveMidrolls;
    YVideoView *_videoView;
    id <YVideoContainerViewDelegate> _delegate;
    YVContainerExtent *_containerExtent;
    YVideoPlayerControlOptions *_controlOptions;
    YVideoSession *_contentVideoSession;
    YVideoSession *_activeVideoSession;
    YVideoAlternateOverlays *_alternateOverlays;
    YVideoAdController *_adController;
    NSString *_initializationStackTrace;
    unsigned long long _wantsToPlayBeforeSetup;
    YVideoSession *_preparedAdVideoSession;
    NSMapTable *_preparedBreakItems;
    NSNumber *_adBreakDurationActual;
    NSDate *_playerItemDateAtAdBreakStart;
    NSDate *_adBreakStartTime;
    VDMSGlobalState *_globalState;
    YVPlayer *_player;
    YVChrome *_chrome;
    NSTimer *_chromeAutohideTimer;
    YVideoDefaultErrorOverlay *_defaultErrorOverlay;
    VDMSPingClient *_pingClient;
    YVAnalytics *_analytics;
}

+ (id)supportedMimeTypes;
- (void).cxx_destruct;
@property(retain, nonatomic) YVAnalytics *analytics; // @synthesize analytics=_analytics;
@property(retain, nonatomic) VDMSPingClient *pingClient; // @synthesize pingClient=_pingClient;
@property(retain, nonatomic) YVideoDefaultErrorOverlay *defaultErrorOverlay; // @synthesize defaultErrorOverlay=_defaultErrorOverlay;
@property(retain, nonatomic) NSTimer *chromeAutohideTimer; // @synthesize chromeAutohideTimer=_chromeAutohideTimer;
@property(readonly, nonatomic) YVChrome *chrome; // @synthesize chrome=_chrome;
@property(readonly, nonatomic) __weak YVPlayer *player; // @synthesize player=_player;
@property(readonly, nonatomic) __weak VDMSGlobalState *globalState; // @synthesize globalState=_globalState;
@property(nonatomic) _Bool seekPendingforLiveMidrolls; // @synthesize seekPendingforLiveMidrolls=_seekPendingforLiveMidrolls;
@property(retain, nonatomic) NSDate *adBreakStartTime; // @synthesize adBreakStartTime=_adBreakStartTime;
@property(retain, nonatomic) NSDate *playerItemDateAtAdBreakStart; // @synthesize playerItemDateAtAdBreakStart=_playerItemDateAtAdBreakStart;
@property(retain, nonatomic) NSNumber *adBreakDurationActual; // @synthesize adBreakDurationActual=_adBreakDurationActual;
@property(nonatomic) _Bool prepareContentVideoNeeded; // @synthesize prepareContentVideoNeeded=_prepareContentVideoNeeded;
@property(retain, nonatomic) NSMapTable *preparedBreakItems; // @synthesize preparedBreakItems=_preparedBreakItems;
@property(retain, nonatomic) YVideoSession *preparedAdVideoSession; // @synthesize preparedAdVideoSession=_preparedAdVideoSession;
@property(nonatomic) _Bool wantsToLoadBeforeSetup; // @synthesize wantsToLoadBeforeSetup=_wantsToLoadBeforeSetup;
@property(nonatomic) unsigned long long wantsToPlayBeforeSetup; // @synthesize wantsToPlayBeforeSetup=_wantsToPlayBeforeSetup;
@property(retain, nonatomic) NSString *initializationStackTrace; // @synthesize initializationStackTrace=_initializationStackTrace;
@property(retain, nonatomic) YVideoAdController *adController; // @synthesize adController=_adController;
@property(readonly, nonatomic) YVideoAlternateOverlays *alternateOverlays; // @synthesize alternateOverlays=_alternateOverlays;
@property(readonly, nonatomic) _Bool chromeAllowed; // @synthesize chromeAllowed=_chromeAllowed;
@property(nonatomic) _Bool chromeVisible; // @synthesize chromeVisible=_chromeVisible;
@property(retain, nonatomic) YVideoSession *activeVideoSession; // @synthesize activeVideoSession=_activeVideoSession;
@property(retain, nonatomic) YVideoSession *contentVideoSession; // @synthesize contentVideoSession=_contentVideoSession;
@property(copy, nonatomic) YVideoPlayerControlOptions *controlOptions; // @synthesize controlOptions=_controlOptions;
@property(nonatomic) _Bool hasBeenSetUp; // @synthesize hasBeenSetUp=_hasBeenSetUp;
@property(retain, nonatomic) YVContainerExtent *containerExtent; // @synthesize containerExtent=_containerExtent;
@property(nonatomic) __weak id <YVideoContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak YVideoView *videoView; // @synthesize videoView=_videoView;
- (_Bool)userCanActToEnableLocation;
- (long long)thumbnailImageContentMode;
- (id)thumbnailImage;
- (id)currentError;
- (_Bool)canResignFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)doNothing;
- (void)setupRemoteControls;
- (void)pingClient:(id)arg1 didRecieveError:(id)arg2;
- (void)pingClient:(id)arg1 didFetchAds:(id)arg2 extensions:(id)arg3 adsJson:(id)arg4;
- (void)bottomRightToolbarWidthUpdatedTo:(struct CGRect)arg1;
@property(readonly, nonatomic) _Bool chromeDisplayingCaptions;
@property(readonly, nonatomic) _Bool chromeCaptionsAvailable;
@property(readonly, nonatomic) _Bool chromeStoppedAtEnd;
@property(readonly, nonatomic) _Bool chromeWifiRestricted;
- (void)chromeCenterPlaybackControlState:(long long *)arg1 toolbarPlaybackControlState:(long long *)arg2;
- (_Bool)chromeShouldShowMoreInfoButton;
- (_Bool)chromeShouldShowMuteButton:(_Bool)arg1;
- (id)chromeRequestsErrorOverlay;
- (id)chromeRequestsCurrentError;
- (id)customLogoImage;
- (id)chromeAdChoicesImage;
@property(readonly, nonatomic) _Bool chromeSeekable;
@property(readonly, nonatomic) CDStruct_1b6d18a9 chromePlaybackPosition;
@property(readonly, nonatomic) CDStruct_1b6d18a9 chromePlaybackDuration;
- (long long)chromeThumbnailImageContentMode;
- (id)chromePostVideoOverlay;
- (double)chromeTopContentInsets;
- (double)chromeTopRightContentInsets;
- (double)chromeTopLeftContentInsets;
- (id)chromeCurrentWindowTransition;
- (_Bool)chromeless;
- (_Bool)chromeControlsVisible;
- (_Bool)chromeIsFullscreenPortrait;
- (_Bool)chromeIsFullscreenLandscape;
- (id)chromeControlOptions;
- (id)chromeActiveVideoSession;
- (id)chromeContentVideoSession;
- (void)chromeStopCastingButtonPressed;
- (void)chromeCastingOverlayTapped;
- (void)chromeScrubEnded;
- (void)chromeScrubStart;
- (void)chromeScrubPositionChanged:(double)arg1;
- (id)selectedBitrateVariant;
- (void)chromeManualBitrateButtonPressed:(id)arg1;
- (void)chromeFeedbackButtonPressed:(id)arg1;
- (void)chromeVoiceOverChromeToggleButtonPressed;
- (void)chromeSkipBackButtonPressed;
- (void)chromeSkipForwardButtonPressed;
- (void)chromePopoutPressed;
- (void)chromeAdChoiceButtonPressed;
- (void)chromeMoreInfoButtonPressed;
- (void)analyicsForMuteAction:(_Bool)arg1;
- (void)chromeMuteButtonPressed;
- (void)chromeFullscreenButtonPressed;
- (void)chromeClosedCaptionsButtonPressed:(id)arg1;
- (void)chromeAudioSelectionButtonPressed:(id)arg1;
- (void)chromePauseButtonPressed;
- (void)chromeReplayButtonPressed;
- (void)chromePlayButtonPressed;
- (void)chromeViewCreated:(id)arg1;
- (void)refreshChromeAutohideTimer;
- (void)clearChromeAutohideTimer;
- (void)startChromeAutohideTimer;
- (void)setChromeVisible:(_Bool)arg1 fromUserAction:(_Bool)arg2 animated:(_Bool)arg3;
- (void)toggleChromeVisibleFromUserAction:(_Bool)arg1;
- (void)setChromeAllowed:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateChrome;
- (_Bool)isVideoFrameMeasureable;
- (void)showLiveStatsOverlay;
- (void)handlePlayButtonPressed;
- (_Bool)shouldContinueWithUserInteraction:(long long)arg1;
- (void)recoverFromMissingLocationError;
- (id)postVideoOverlay:(id)arg1;
- (id)midVideoOverlay:(id)arg1;
- (id)preVideoOverlay:(id)arg1;
- (void)updateOverlays;
- (void)handleLongDoublePress:(id)arg1;
- (void)handlePinch:(id)arg1;
- (void)handleTap;
- (_Bool)autoplayingOrExpectedToAutoplay;
- (double)adVisibilityPercentage;
- (void)logAdEvent:(id)arg1 withParameters:(id)arg2;
- (_Bool)isLiveMidrollAdBreak;
- (void)resumeContentVideo;
- (void)waitForAds;
- (void)playBreakItem:(id)arg1;
- (void)prepareBreakItem:(id)arg1;
- (void)prepareAdVideoSession;
- (_Bool)canPlayBreakItem:(id)arg1 error:(id *)arg2;
- (id)assembleGeminiAdViewabilityData;
- (_Bool)isAdStreamPlayable:(id)arg1;
- (double)finalPositionForSeekableRange:(CDStruct_5c5366e1)arg1 currentPlaybackPosition:(double)arg2 currentPlayerTime:(id)arg3 adStartPlayerTime:(id)arg4;
- (id)currentTime;
- (void)seekToCorrectPositionForLiveMidrolls;
- (void)videoSession:(id)arg1 highFrequencyPositionUpdate:(CDStruct_1b6d18a9)arg2;
- (void)videoSession:(id)arg1 videoFrameOutput:(id)arg2;
- (void)videoSessionCastingPermissionsChanged:(id)arg1;
- (void)videoSession:(id)arg1 cuesSkipped:(id)arg2;
- (void)videoSession:(id)arg1 cuesPlayedThrough:(id)arg2;
- (void)videoSession:(id)arg1 inRangeCuesChangedTo:(id)arg2 from:(id)arg3;
- (void)videoSession:(id)arg1 cuesChangedTo:(id)arg2 from:(id)arg3;
- (void)videoSession:(id)arg1 playerOutputCaptionAttributedStrings:(id)arg2 nativeSampleBuffers:(id)arg3 forItemTime:(CDStruct_1b6d18a9)arg4;
- (void)videoSession:(id)arg1 selectedCaptionStreamChanged:(id)arg2;
- (void)videoSession:(id)arg1 availableCaptionStreamsChanged:(id)arg2;
- (_Bool)videoSessionIsVisible:(id)arg1;
- (void)videoSessionStartedAirplaying:(id)arg1;
- (id)topViewController;
- (void)videoSession:(id)arg1 receivedMidrollPlayCue:(id)arg2;
- (void)videoSession:(id)arg1 receivedMidrollLoadCue:(id)arg2;
- (void)videoSessionPlayIntentionChanged:(id)arg1;
- (id)errorOverlayForVideoSession:(id)arg1;
- (id)postVideoOverlayForVideoSession:(id)arg1;
- (id)midVideoOverlayForVideoSession:(id)arg1;
- (id)preVideoOverlayForVideoSession:(id)arg1;
- (void)videoSession:(id)arg1 playbackReadyChanged:(_Bool)arg2;
- (void)videoSessionMetadataLoaded:(id)arg1;
- (void)videoSession:(id)arg1 receivedPinchGestureOpen:(_Bool)arg2;
- (_Bool)videoSession:(id)arg1 shouldContinueWithUserInteraction:(long long)arg2;
- (void)videoSessionPlaybackReachedEnd:(id)arg1;
- (void)videoSessionPlayerStarted:(id)arg1;
- (void)videoSessionSeekBegan:(id)arg1;
- (void)videoSession:(id)arg1 mutedChanged:(_Bool)arg2;
- (void)videoSession:(id)arg1 tryingToPlayChanged:(_Bool)arg2;
- (void)playbackFirstBegan:(id)arg1;
- (void)videoSession:(id)arg1 playbackStatusChanged:(long long)arg2 userInfo:(id)arg3;
- (void)videoSession:(id)arg1 playbackPositionChanged:(double)arg2;
- (void)videoSession:(id)arg1 playbackPositionChangedTo:(CDStruct_1b6d18a9)arg2 fromProgress:(_Bool)arg3;
- (void)setInitialThumbnail:(id)arg1;
- (void)handleAirplayDisconnected;
- (void)handleAirplayConnected;
- (void)handleChromecastDisconnected;
- (void)handleChromecastConnected;
- (void)handleBecomeActive;
- (void)handleResignActive;
- (void)configureControlOptionsForVideoSession:(id)arg1 clientSideAd:(_Bool)arg2;
- (_Bool)expectedToAutoplay;
- (_Bool)autoplayConditionsMet;
- (_Bool)autoplayOnUserScroll;
- (_Bool)autoplay;
- (void)tearDown;
- (void)stepDown;
- (void)loadVideo;
- (void)pauseOnAutoScroll;
- (void)pauseOnUserScroll;
- (void)pause;
- (void)pauseWithIntention:(unsigned long long)arg1;
- (void)playOnWindowTransition;
- (void)play;
- (void)playWithIntention:(unsigned long long)arg1;
- (id)createPingClientWithZonePrefix:(id)arg1 sessionID:(id)arg2;
- (id)createAlternateOverlays;
- (id)createChrome;
- (id)createMetadataWithUrl:(id)arg1;
- (id)createAdController;
- (id)allocVideoSession;
- (void)runOnAllVideoSessions:(CDUnknownBlockType)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) long long maxAllowedBitrateForAds;
@property(readonly, nonatomic) double targetAdBitrate;
@property(readonly, nonatomic) double timeBeforeBreakEndsToPrepareContent;
@property(readonly, nonatomic) _Bool isPlaying;
@property(readonly, nonatomic) long long playbackStatus;
@property(readonly, nonatomic) YVideoSessionState *sessionState;
- (id)createConfiguredVideoSession;
- (void)setupWithVideoSessionState:(id)arg1;
- (void)setupInitializationStackTrace;
- (void)dealloc;
- (id)initWithVideoView:(id)arg1 analytics:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

