//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVURLAsset, YVideoUnderlyingCache;
@protocol YVideoCacheLoaderDelegate;

@interface YVideoCacheLoader : NSObject
{
    YVideoUnderlyingCache *_underlyingCache;
    AVURLAsset *_asset;
    id <YVideoCacheLoaderDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <YVideoCacheLoaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) AVURLAsset *asset; // @synthesize asset=_asset;
@property(readonly, nonatomic) YVideoUnderlyingCache *underlyingCache; // @synthesize underlyingCache=_underlyingCache;
@property(readonly, nonatomic) unsigned long long bytesToPreload;
@property(readonly, nonatomic) unsigned long long cachedByteSize;
- (void)loadingDidServeBytesFromCache:(unsigned long long)arg1;
- (id)initWithUnderlyingCache:(id)arg1;
- (id)init;

@end

