//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CLLocation, NSMapTable, NSMutableArray, YVLocation;

@interface YVLocationCore : NSObject
{
    _Bool _locationServicesEnabled;
    _Bool _plistAuthorized;
    _Bool _locationPermissionRequestedByUser;
    int _authorizationStatus;
    NSMutableArray *_completionQueue;
    NSMapTable *_locationSubscriptions;
    NSMapTable *_permissionSubscriptions;
    CLLocation *_location;
    YVLocation *_locationDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool locationPermissionRequestedByUser; // @synthesize locationPermissionRequestedByUser=_locationPermissionRequestedByUser;
@property(nonatomic) _Bool plistAuthorized; // @synthesize plistAuthorized=_plistAuthorized;
@property(nonatomic) _Bool locationServicesEnabled; // @synthesize locationServicesEnabled=_locationServicesEnabled;
@property(nonatomic) __weak YVLocation *locationDelegate; // @synthesize locationDelegate=_locationDelegate;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) int authorizationStatus; // @synthesize authorizationStatus=_authorizationStatus;
@property(retain, nonatomic) NSMapTable *permissionSubscriptions; // @synthesize permissionSubscriptions=_permissionSubscriptions;
@property(retain, nonatomic) NSMapTable *locationSubscriptions; // @synthesize locationSubscriptions=_locationSubscriptions;
@property(retain, nonatomic) NSMutableArray *completionQueue; // @synthesize completionQueue=_completionQueue;
- (void)runPermisionSideEffects;
- (void)runLocationCompletions;
- (void)runLocationSideEffectsWithRequestTime:(id)arg1 locationWasError:(_Bool)arg2;
- (void)userRequestedLocation;
- (void)unsubscribeToUpdatesFor:(id)arg1;
- (void)subscribeToPermissionUpdatesUntilGrantedFor:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)subscribeToLocationUpdatesUntilFoundAtTime:(id)arg1 for:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (void)subscribeToLocationUpdatesAtTime:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)failLocationRequest;
- (void)updateLocationWith:(id)arg1;
- (void)updateAuthorizationStatus:(int)arg1 locationServicesEnabled:(_Bool)arg2;
- (void)runOnMain:(CDUnknownBlockType)arg1;
- (_Bool)locationIsDesired;
- (_Bool)userActionAvailableToDetermineLocation;
- (_Bool)locationPermissionDisabled;
- (_Bool)locationServicesDisabled;
- (_Bool)canAskForLocationPermission;
- (_Bool)canAskForLocation;
- (_Bool)currentLocationIsTooOldFor:(id)arg1;
- (_Bool)needLocation;
- (_Bool)hasLocationPermission;
- (_Bool)needLocationPermission;
- (id)initWithLocationDelegate:(id)arg1 authorizationStatus:(int)arg2 locationServicesEnabled:(_Bool)arg3 plistAuthorized:(_Bool)arg4;

@end

