//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSString, UIViewController, YVLocationCore;

@interface YVLocation : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_locationManager;
    YVLocationCore *_locationCore;
    UIViewController *_userRequestViewController;
}

+ (void)setLocationProxy:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak UIViewController *userRequestViewController; // @synthesize userRequestViewController=_userRequestViewController;
@property(retain, nonatomic) YVLocationCore *locationCore; // @synthesize locationCore=_locationCore;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (_Bool)authorizationInPlistEnabled;
- (_Bool)locationServicesEnabled;
- (id)currentTime;
- (int)authorizationStatus;
- (void)presentLocationServicesAlert;
- (void)openLinkTo:(id)arg1;
- (void)requestLocation;
- (void)requestPermission;
- (void)userRequestedLocationPermissionFrom:(id)arg1;
- (void)unsubscribeToUpdatesFor:(id)arg1;
- (void)subscribeToPermissionUpdatesUntilGrantedFor:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)subscribeToLocationUpdatesUntilFoundFor:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)subscribeToLocationUpdates:(CDUnknownBlockType)arg1;
- (void)applicationDidBecomeActive;
- (id)allocLocationManager;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

