//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "YVResource.h"

#import "YVProcess-Protocol.h"
#import "YVProcessPrivate-Protocol.h"

@class NSString, YVProcessGraph;

@interface YVMeasure : YVResource <YVProcessPrivate, YVProcess>
{
    _Bool _forceUpdatePushedValues;
    YVProcessGraph *_graph;
    unsigned long long _lastUpdateSequence;
    unsigned long long _removedSequence;
    CDUnknownBlockType _runBlock;
    id _pushedValue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id pushedValue; // @synthesize pushedValue=_pushedValue;
@property(nonatomic) _Bool forceUpdatePushedValues; // @synthesize forceUpdatePushedValues=_forceUpdatePushedValues;
@property(copy, nonatomic) CDUnknownBlockType runBlock; // @synthesize runBlock=_runBlock;
@property(nonatomic) unsigned long long removedSequence; // @synthesize removedSequence=_removedSequence;
@property(nonatomic) unsigned long long lastUpdateSequence; // @synthesize lastUpdateSequence=_lastUpdateSequence;
@property(retain, nonatomic) YVProcessGraph *graph; // @synthesize graph=_graph;
- (void)remove;
- (void)performRunBlock;
- (id)suppliesEnumerator;
- (id)process;
- (void)submitValue:(id)arg1 impulse:(id)arg2;
- (void)pushValue:(id)arg1;
- (id)initWithRunBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *staticDebugName;
@property(readonly) Class superclass;

@end

