//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface YVOMAdVerification : NSObject
{
    NSURL *_url;
    NSString *_vendorKey;
    NSString *_parameters;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *parameters; // @synthesize parameters=_parameters;
@property(readonly, nonatomic) NSString *vendorKey; // @synthesize vendorKey=_vendorKey;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
- (id)initWithUrl:(id)arg1 vendorKey:(id)arg2 parameters:(id)arg3;

@end

