//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class YVideoView;

@interface YVPopoutPresentEvent : NSObject
{
    _Bool _animated;
    YVideoView *_videoView;
    CDUnknownBlockType _completion;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool animated; // @synthesize animated=_animated;
@property(nonatomic) __weak YVideoView *videoView; // @synthesize videoView=_videoView;

@end

