//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class YVResource;
@protocol YVProcessRangeProtocol;

@protocol YVProcessRangeProtocol <NSObject>
@property(readonly, nonatomic) _Bool holds;
@property(readonly, nonatomic) id <YVProcessRangeProtocol> opRange;
@property(readonly, nonatomic) YVResource *exit;
@property(readonly, nonatomic) YVResource *enter;
@property(readonly, nonatomic) YVResource *inside;
@end

