//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString, YVEvent, YVValueStoreTransaction;

@interface YVValueStore : NSObject
{
    YVEvent *_currentEvent;
    NSMutableSet *_nodes;
    YVValueStoreTransaction *_currentTransaction;
    NSString *_debugStoreId;
    NSString *_debugStoreType;
    unsigned long long _elementIdCounter;
    NSMutableSet *_dynamicNodes;
    NSMutableSet *_eventStartUpdateNodes;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableSet *eventStartUpdateNodes; // @synthesize eventStartUpdateNodes=_eventStartUpdateNodes;
@property(readonly, nonatomic) NSMutableSet *dynamicNodes; // @synthesize dynamicNodes=_dynamicNodes;
@property(nonatomic) unsigned long long elementIdCounter; // @synthesize elementIdCounter=_elementIdCounter;
@property(retain, nonatomic) NSString *debugStoreType; // @synthesize debugStoreType=_debugStoreType;
@property(retain, nonatomic) NSString *debugStoreId; // @synthesize debugStoreId=_debugStoreId;
@property(retain, nonatomic) YVValueStoreTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
@property(retain, nonatomic) NSMutableSet *nodes; // @synthesize nodes=_nodes;
@property(retain, nonatomic) YVEvent *currentEvent; // @synthesize currentEvent=_currentEvent;
- (void)dealloc;
- (id)dfs:(id)arg1 currentPriority:(unsigned long long *)arg2;
- (void)topologicalSort;
- (id)nextId;
- (void)indexNewRelationsAndSort;
- (void)beginTransactionWithSequence:(unsigned long long)arg1 timestamp:(id)arg2 impulse:(id)arg3 transactionBlock:(CDUnknownBlockType)arg4 beforeEffectsHook:(CDUnknownBlockType)arg5;
- (id)initWithType:(id)arg1;

@end

