//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 29 2020 16:17:50).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, NSString, YVEvent;

@interface YVValue : NSObject
{
    id _value;
    YVEvent *_event;
    NSString *_debugName;
    CDUnknownBlockType _equalValues;
    unsigned long long _dfsState;
    NSString *_debugNodeId;
    NSHashTable *_targets;
    unsigned long long _priority;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) NSHashTable *targets; // @synthesize targets=_targets;
@property(retain, nonatomic) NSString *debugNodeId; // @synthesize debugNodeId=_debugNodeId;
@property(nonatomic) unsigned long long dfsState; // @synthesize dfsState=_dfsState;
@property(copy, nonatomic) CDUnknownBlockType equalValues; // @synthesize equalValues=_equalValues;
@property(readonly, nonatomic) NSString *debugName; // @synthesize debugName=_debugName;
@property(retain, nonatomic) YVEvent *event; // @synthesize event=_event;
@property(retain, nonatomic) id value; // @synthesize value=_value;
@property(readonly, nonatomic) _Bool justChanged;
- (id)debugDescription;
- (id)initWithName:(id)arg1;

@end

